; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface people_vt
  Get_name.s()
  Set_name(val.s)
  Get_first_name.s()
  Set_first_name(val.s)
  say_hello()
  Free()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure people_Inst
  *VTable.people_vt
  name.s
  first_name.s
EndStructure

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Procedure people_Init(*This.people_Inst, name.s, first_name.s)
      *This\name = name
      *This\first_name = first_name
EndProcedure

Procedure.s people_Get_name(*This.people_Inst)
      ProcedureReturn *This\name
EndProcedure

Procedure people_Set_name(*This.people_Inst, val.s)
      *This\name = val
EndProcedure

Procedure.s people_Get_first_name(*This.people_Inst)
      ProcedureReturn *This\first_name
EndProcedure

Procedure people_Set_first_name(*This.people_Inst, val.s)
      *This\first_name = val
EndProcedure

Procedure people_say_hello(*This.people_Inst)
      MessageRequester("Hello", "Hello " + *This\VTable\Get_first_name() + " " + *This\VTable\Get_name())
EndProcedure

Procedure people_Free(*This.people_Inst)
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  people_VTable_Data:
    Data.i @people_Get_name()
    Data.i @people_Set_name()
    Data.i @people_Get_first_name()
    Data.i @people_Set_first_name()
    Data.i @people_say_hello()
    Data.i @people_Free()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_people(name.s, first_name.s)
  Protected *obj.people_Inst = AllocateStructure(people_Inst)
  If *obj
    *obj\VTable = ?people_VTable_Data
    people_Init(*obj, name, first_name)
  EndIf
  ProcedureReturn *obj
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------


Procedure Main()
  Protected *dev.people_vt = New_people("Bielen", "Pierre")
  If *dev
    *dev\say_hello()
    *dev\Set_first_name("Jean")
    *dev\say_hello()
  EndIf
EndProcedure

Main()
