; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface UI_Component_vt
  GetID.i()
  GetTag.s()
  SetTag(t.s)
  GetX.i()
  GetY.i()
  GetWidth.i()
  GetHeight.i()
  IsVisible.b()
  IsEnabled.b()
  GetUserData.i()
  SetUserData(val.i)
EndInterface

Interface UI_Gadget_vt Extends UI_Component_vt
  GetText.s()
  SetText(t.s)
  SetToolTip(tip.s)
  GetToolTip.s()
  SetPosition(nx.i, ny.i, nw.i, nh.i)
  SetVisible(v.b)
  SetEnabled(e.b)
  SetColor(colorType.i, color.i)
  GetColor.i(colorType.i)
  SetFont(font.i)
  SetFocus()
  Free()
  OnClick()
  OnChange()
  OnFocus()
  OnLostFocus()
  OnRightClick()
  OnCustomEvent(eventType.i)
EndInterface

Interface UI_Window_vt Extends UI_Component_vt
  SetTitle(t.s)
  GetTitle.s()
  SetPosition(nx.i, ny.i, nw.i, nh.i)
  SetVisible(v.b)
  SetEnabled(e.b)
  Close()
  Free()
  OnClose.b()
  OnResize(newW.i, newH.i)
  OnMove(newX.i, newY.i)
  OnMinimize()
  OnMaximize()
  OnRestore()
  OnChildEvent(*child.UI_Gadget_vt, eventType.i)
EndInterface

Interface UI_Application_vt
  SetMainWindow(*win_p.UI_Window_vt)
  GetMainWindow.i()
  Run(*mainWin_p.UI_Window_vt = 0)
  Quit()
EndInterface

Interface UI_CustomGadget_vt Extends UI_Gadget_vt
  OnPaint(w.i, h.i)
  Redraw()
  OnMouseEnter()
  OnMouseLeave()
  OnMouseDown(mx.i, my.i, button.i)
  OnMouseUp(mx.i, my.i, button.i)
  OnMouseMove(mx.i, my.i)
  OnKeyDown(key.i)
EndInterface

Interface UI_Button_vt Extends UI_Gadget_vt
EndInterface

Interface UI_TextBox_vt Extends UI_Gadget_vt
  IsReadOnly.b()
  SetReadOnly(ro.b)
EndInterface

Interface UI_Label_vt Extends UI_Gadget_vt
EndInterface

Interface UI_CheckBox_vt Extends UI_Gadget_vt
  IsChecked.b()
  SetChecked(checked.b)
EndInterface

Interface UI_ProgressBar_vt Extends UI_Gadget_vt
  GetValue.i()
  SetValue(v.i)
EndInterface

Interface UI_Slider_vt Extends UI_Gadget_vt
  GetValue.i()
  SetValue(v.i)
EndInterface

Interface UI_ComboBox_vt Extends UI_Gadget_vt
  AddItem(text.s)
  GetSelectedIndex.i()
  SetSelectedIndex(idx.i)
  GetSelectedItem.s()
  Clear()
EndInterface

Interface UI_Controls_ToggleSwitch_vt Extends UI_CustomGadget_vt
  IsChecked.b()
  SetChecked(state.b)
EndInterface

Interface GreetButton_vt Extends UI_Button_vt
  BindControls(*input.UI_TextBox_vt, *lbl.UI_Label_vt)
EndInterface

Interface ModeSwitch_vt Extends UI_Controls_ToggleSwitch_vt
  BindLabel(*lbl.UI_Label_vt)
EndInterface

Interface VolumeSlider_vt Extends UI_Slider_vt
  BindProgress(*pb.UI_ProgressBar_vt, *lbl.UI_Label_vt)
EndInterface

Interface MainWindow_vt Extends UI_Window_vt
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure UI_Component_Inst
  *VTable.UI_Component_vt
  id.i
  tag.s
  x.i
  y.i
  width.i
  height.i
  isVisible.b
  isEnabled.b
  userData.i
EndStructure

Structure UI_Gadget_Inst Extends UI_Component_Inst
  tooltip.s
  fontID.i
EndStructure

Structure UI_Window_Inst Extends UI_Component_Inst
  title.s
  flags.i
  parentID.i
EndStructure

Structure UI_Application_Inst
  *VTable.UI_Application_vt
  isRunning.b
  *mainWindow.UI_Window_vt
EndStructure

Structure UI_CustomGadget_Inst Extends UI_Gadget_Inst
  isHovered.b
  isPressed.b
  mouseX.i
  mouseY.i
EndStructure

Structure UI_Button_Inst Extends UI_Gadget_Inst
EndStructure

Structure UI_TextBox_Inst Extends UI_Gadget_Inst
EndStructure

Structure UI_Label_Inst Extends UI_Gadget_Inst
EndStructure

Structure UI_CheckBox_Inst Extends UI_Gadget_Inst
EndStructure

Structure UI_ProgressBar_Inst Extends UI_Gadget_Inst
  minVal.i
  maxVal.i
EndStructure

Structure UI_Slider_Inst Extends UI_Gadget_Inst
  minVal.i
  maxVal.i
EndStructure

Structure UI_ComboBox_Inst Extends UI_Gadget_Inst
EndStructure

Structure UI_Controls_ToggleSwitch_Inst Extends UI_CustomGadget_Inst
  isChecked.b
  activeColor.i
  inactiveColor.i
EndStructure

Structure GreetButton_Inst Extends UI_Button_Inst
  *nameInput.UI_TextBox_vt
  *statusLabel.UI_Label_vt
EndStructure

Structure ModeSwitch_Inst Extends UI_Controls_ToggleSwitch_Inst
  *statusLabel.UI_Label_vt
EndStructure

Structure VolumeSlider_Inst Extends UI_Slider_Inst
  *progress.UI_ProgressBar_vt
  *valLabel.UI_Label_vt
EndStructure

Structure MainWindow_Inst Extends UI_Window_Inst
  *lblTitle.UI_Label_vt
  *lblPrompt.UI_Label_vt
  *txtInput.UI_TextBox_vt
  *btnGreet.GreetButton_vt
  *lblStatus.UI_Label_vt
  *lblSwitch.UI_Label_vt
  *switchTurbo.ModeSwitch_vt
  *lblSlider.UI_Label_vt
  *sliderVol.VolumeSlider_vt
  *progBar.UI_ProgressBar_vt
  *comboTheme.UI_ComboBox_vt
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL DECLARATIONS & CONSTANTS
; ----------------------------------------------------------------------------

Global NewMap UI_GadgetMap.i()
Global NewMap UI_WindowMap.i()
Macro UI_RegisterGadget(id_p, g_p)
  If (id_p >= 0 And g_p)
    UI_GadgetMap(Str(id_p)) = g_p
  EndIf
EndMacro
Macro UI_UnregisterGadget(id_p)
  If (FindMapElement(UI_GadgetMap(), Str(id_p)))
    DeleteMapElement(UI_GadgetMap(), Str(id_p))
  EndIf
EndMacro
Macro UI_RegisterWindow(id_p, w_p)
  If (id_p >= 0 And w_p)
    UI_WindowMap(Str(id_p)) = w_p
  EndIf
EndMacro
Macro UI_UnregisterWindow(id_p)
  If (FindMapElement(UI_WindowMap(), Str(id_p)))
    DeleteMapElement(UI_WindowMap(), Str(id_p))
  EndIf
EndMacro

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare.i UI_Component_GetID(*This.UI_Component_Inst)
Declare.s UI_Component_GetTag(*This.UI_Component_Inst)
Declare UI_Component_SetTag(*This.UI_Component_Inst, t.s)
Declare.i UI_Component_GetX(*This.UI_Component_Inst)
Declare.i UI_Component_GetY(*This.UI_Component_Inst)
Declare.i UI_Component_GetWidth(*This.UI_Component_Inst)
Declare.i UI_Component_GetHeight(*This.UI_Component_Inst)
Declare.b UI_Component_IsVisible(*This.UI_Component_Inst)
Declare.b UI_Component_IsEnabled(*This.UI_Component_Inst)
Declare.i UI_Component_GetUserData(*This.UI_Component_Inst)
Declare UI_Component_SetUserData(*This.UI_Component_Inst, val.i)
Declare.s UI_Gadget_GetText(*This.UI_Gadget_Inst)
Declare UI_Gadget_SetText(*This.UI_Gadget_Inst, t.s)
Declare UI_Gadget_SetToolTip(*This.UI_Gadget_Inst, tip.s)
Declare.s UI_Gadget_GetToolTip(*This.UI_Gadget_Inst)
Declare UI_Gadget_SetPosition(*This.UI_Gadget_Inst, nx.i, ny.i, nw.i, nh.i)
Declare UI_Gadget_SetVisible(*This.UI_Gadget_Inst, v.b)
Declare UI_Gadget_SetEnabled(*This.UI_Gadget_Inst, e.b)
Declare UI_Gadget_SetColor(*This.UI_Gadget_Inst, colorType.i, color.i)
Declare.i UI_Gadget_GetColor(*This.UI_Gadget_Inst, colorType.i)
Declare UI_Gadget_SetFont(*This.UI_Gadget_Inst, font.i)
Declare UI_Gadget_SetFocus(*This.UI_Gadget_Inst)
Declare UI_Gadget_Free(*This.UI_Gadget_Inst)
Declare UI_Gadget_OnClick(*This.UI_Gadget_Inst)
Declare UI_Gadget_OnChange(*This.UI_Gadget_Inst)
Declare UI_Gadget_OnFocus(*This.UI_Gadget_Inst)
Declare UI_Gadget_OnLostFocus(*This.UI_Gadget_Inst)
Declare UI_Gadget_OnRightClick(*This.UI_Gadget_Inst)
Declare UI_Gadget_OnCustomEvent(*This.UI_Gadget_Inst, eventType.i)
Declare UI_Window_Init(*This.UI_Window_Inst, title_p.s, x_p.i = #PB_Ignore, y_p.i = #PB_Ignore, w_p.i = 640, h_p.i = 480, flags_p.i = #PB_Window_SystemMenu | #PB_Window_ScreenCentered | #PB_Window_SizeGadget | #PB_Window_MinimizeGadget | #PB_Window_MaximizeGadget, parent_p.i = 0)
Declare UI_Window_SetTitle(*This.UI_Window_Inst, t.s)
Declare.s UI_Window_GetTitle(*This.UI_Window_Inst)
Declare UI_Window_SetPosition(*This.UI_Window_Inst, nx.i, ny.i, nw.i, nh.i)
Declare UI_Window_SetVisible(*This.UI_Window_Inst, v.b)
Declare UI_Window_SetEnabled(*This.UI_Window_Inst, e.b)
Declare UI_Window_Close(*This.UI_Window_Inst)
Declare UI_Window_Free(*This.UI_Window_Inst)
Declare.b UI_Window_OnClose(*This.UI_Window_Inst)
Declare UI_Window_OnResize(*This.UI_Window_Inst, newW.i, newH.i)
Declare UI_Window_OnMove(*This.UI_Window_Inst, newX.i, newY.i)
Declare UI_Window_OnMinimize(*This.UI_Window_Inst)
Declare UI_Window_OnMaximize(*This.UI_Window_Inst)
Declare UI_Window_OnRestore(*This.UI_Window_Inst)
Declare UI_Window_OnChildEvent(*This.UI_Window_Inst, *child.UI_Gadget_vt, eventType.i)
Declare UI_Application_Init(*This.UI_Application_Inst)
Declare UI_Application_SetMainWindow(*This.UI_Application_Inst, *win_p.UI_Window_vt)
Declare.i UI_Application_GetMainWindow(*This.UI_Application_Inst)
Declare UI_Application_Run(*This.UI_Application_Inst, *mainWin_p.UI_Window_vt = 0)
Declare UI_Application_Quit(*This.UI_Application_Inst)
Declare UI_CustomGadget_Init(*This.UI_CustomGadget_Inst, x_p.i, y_p.i, w_p.i = 100, h_p.i = 30, flags_p.i = 0)
Declare UI_CustomGadget_Redraw(*This.UI_CustomGadget_Inst)
Declare UI_CustomGadget_OnMouseEnter(*This.UI_CustomGadget_Inst)
Declare UI_CustomGadget_OnMouseLeave(*This.UI_CustomGadget_Inst)
Declare UI_CustomGadget_OnMouseDown(*This.UI_CustomGadget_Inst, mx.i, my.i, button.i)
Declare UI_CustomGadget_OnMouseUp(*This.UI_CustomGadget_Inst, mx.i, my.i, button.i)
Declare UI_CustomGadget_OnMouseMove(*This.UI_CustomGadget_Inst, mx.i, my.i)
Declare UI_CustomGadget_OnKeyDown(*This.UI_CustomGadget_Inst, key.i)
Declare UI_CustomGadget_OnCustomEvent(*This.UI_CustomGadget_Inst, eventType.i)
Declare UI_CustomGadget_Free(*This.UI_CustomGadget_Inst)
Declare UI_Button_Init(*This.UI_Button_Inst, x_p.i, y_p.i, w_p.i = 120, h_p.i = 30, text_p.s = "Button", flags_p.i = 0)
Declare UI_Button_Free(*This.UI_Button_Inst)
Declare UI_TextBox_Init(*This.UI_TextBox_Inst, x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, defaultText_p.s = "", flags_p.i = 0)
Declare.b UI_TextBox_IsReadOnly(*This.UI_TextBox_Inst)
Declare UI_TextBox_SetReadOnly(*This.UI_TextBox_Inst, ro.b)
Declare UI_TextBox_Free(*This.UI_TextBox_Inst)
Declare UI_Label_Init(*This.UI_Label_Inst, x_p.i, y_p.i, w_p.i = 150, h_p.i = 20, text_p.s = "", flags_p.i = 0)
Declare UI_Label_Free(*This.UI_Label_Inst)
Declare UI_CheckBox_Init(*This.UI_CheckBox_Inst, x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, text_p.s = "CheckBox", flags_p.i = 0)
Declare.b UI_CheckBox_IsChecked(*This.UI_CheckBox_Inst)
Declare UI_CheckBox_SetChecked(*This.UI_CheckBox_Inst, checked.b)
Declare UI_CheckBox_Free(*This.UI_CheckBox_Inst)
Declare UI_ProgressBar_Init(*This.UI_ProgressBar_Inst, x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
Declare.i UI_ProgressBar_GetValue(*This.UI_ProgressBar_Inst)
Declare UI_ProgressBar_SetValue(*This.UI_ProgressBar_Inst, v.i)
Declare UI_ProgressBar_Free(*This.UI_ProgressBar_Inst)
Declare UI_Slider_Init(*This.UI_Slider_Inst, x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
Declare.i UI_Slider_GetValue(*This.UI_Slider_Inst)
Declare UI_Slider_SetValue(*This.UI_Slider_Inst, v.i)
Declare UI_Slider_Free(*This.UI_Slider_Inst)
Declare UI_ComboBox_Init(*This.UI_ComboBox_Inst, x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, flags_p.i = 0)
Declare UI_ComboBox_AddItem(*This.UI_ComboBox_Inst, text.s)
Declare.i UI_ComboBox_GetSelectedIndex(*This.UI_ComboBox_Inst)
Declare UI_ComboBox_SetSelectedIndex(*This.UI_ComboBox_Inst, idx.i)
Declare.s UI_ComboBox_GetSelectedItem(*This.UI_ComboBox_Inst)
Declare UI_ComboBox_Clear(*This.UI_ComboBox_Inst)
Declare UI_ComboBox_Free(*This.UI_ComboBox_Inst)
Declare UI_Controls_ToggleSwitch_Init(*This.UI_Controls_ToggleSwitch_Inst, x_p.i, y_p.i, w_p.i = 50, h_p.i = 26, defaultState_p.b = #False)
Declare.b UI_Controls_ToggleSwitch_IsChecked(*This.UI_Controls_ToggleSwitch_Inst)
Declare UI_Controls_ToggleSwitch_SetChecked(*This.UI_Controls_ToggleSwitch_Inst, state.b)
Declare UI_Controls_ToggleSwitch_OnClick(*This.UI_Controls_ToggleSwitch_Inst)
Declare UI_Controls_ToggleSwitch_OnPaint(*This.UI_Controls_ToggleSwitch_Inst, w.i, h.i)
Declare GreetButton_BindControls(*This.GreetButton_Inst, *input.UI_TextBox_vt, *lbl.UI_Label_vt)
Declare GreetButton_OnClick(*This.GreetButton_Inst)
Declare ModeSwitch_BindLabel(*This.ModeSwitch_Inst, *lbl.UI_Label_vt)
Declare ModeSwitch_OnChange(*This.ModeSwitch_Inst)
Declare VolumeSlider_BindProgress(*This.VolumeSlider_Inst, *pb.UI_ProgressBar_vt, *lbl.UI_Label_vt)
Declare VolumeSlider_OnCustomEvent(*This.VolumeSlider_Inst, eventType.i)
Declare MainWindow_Init(*This.MainWindow_Inst)
Declare.b MainWindow_OnClose(*This.MainWindow_Inst)

Declare.i New_UI_Window(title_p.s, x_p.i = #PB_Ignore, y_p.i = #PB_Ignore, w_p.i = 640, h_p.i = 480, flags_p.i = #PB_Window_SystemMenu | #PB_Window_ScreenCentered | #PB_Window_SizeGadget | #PB_Window_MinimizeGadget | #PB_Window_MaximizeGadget, parent_p.i = 0)
Declare Free_UI_Window(*obj.UI_Window_Inst)
Declare.i New_UI_Application()
Declare Free_UI_Application(*obj.UI_Application_Inst)
Declare.i New_UI_Button(x_p.i, y_p.i, w_p.i = 120, h_p.i = 30, text_p.s = "Button", flags_p.i = 0)
Declare Free_UI_Button(*obj.UI_Button_Inst)
Declare.i New_UI_TextBox(x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, defaultText_p.s = "", flags_p.i = 0)
Declare Free_UI_TextBox(*obj.UI_TextBox_Inst)
Declare.i New_UI_Label(x_p.i, y_p.i, w_p.i = 150, h_p.i = 20, text_p.s = "", flags_p.i = 0)
Declare Free_UI_Label(*obj.UI_Label_Inst)
Declare.i New_UI_CheckBox(x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, text_p.s = "CheckBox", flags_p.i = 0)
Declare Free_UI_CheckBox(*obj.UI_CheckBox_Inst)
Declare.i New_UI_ProgressBar(x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
Declare Free_UI_ProgressBar(*obj.UI_ProgressBar_Inst)
Declare.i New_UI_Slider(x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
Declare Free_UI_Slider(*obj.UI_Slider_Inst)
Declare.i New_UI_ComboBox(x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, flags_p.i = 0)
Declare Free_UI_ComboBox(*obj.UI_ComboBox_Inst)
Declare.i New_UI_Controls_ToggleSwitch(x_p.i, y_p.i, w_p.i = 50, h_p.i = 26, defaultState_p.b = #False)
Declare Free_UI_Controls_ToggleSwitch(*obj.UI_Controls_ToggleSwitch_Inst)
Declare.i New_GreetButton(x_p.i, y_p.i, w_p.i = 120, h_p.i = 30, text_p.s = "Button", flags_p.i = 0)
Declare Free_GreetButton(*obj.GreetButton_Inst)
Declare.i New_ModeSwitch(x_p.i, y_p.i, w_p.i = 50, h_p.i = 26, defaultState_p.b = #False)
Declare Free_ModeSwitch(*obj.ModeSwitch_Inst)
Declare.i New_VolumeSlider(x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
Declare Free_VolumeSlider(*obj.VolumeSlider_Inst)
Declare.i New_MainWindow()
Declare Free_MainWindow(*obj.MainWindow_Inst)

Procedure.i UI_Component_GetID(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\id
EndProcedure

Procedure.s UI_Component_GetTag(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\tag
EndProcedure

Procedure UI_Component_SetTag(*This.UI_Component_Inst, t.s)
  Protected *This_vt.UI_Component_vt = *This
        *This\tag = t
EndProcedure

Procedure.i UI_Component_GetX(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\x
EndProcedure

Procedure.i UI_Component_GetY(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\y
EndProcedure

Procedure.i UI_Component_GetWidth(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\width
EndProcedure

Procedure.i UI_Component_GetHeight(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\height
EndProcedure

Procedure.b UI_Component_IsVisible(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\isVisible
EndProcedure

Procedure.b UI_Component_IsEnabled(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\isEnabled
EndProcedure

Procedure.i UI_Component_GetUserData(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\userData
EndProcedure

Procedure UI_Component_SetUserData(*This.UI_Component_Inst, val.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\userData = val
EndProcedure

Procedure.s UI_Gadget_GetText(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
  If (*This\id And IsGadget(*This\id))
          ProcedureReturn GetGadgetText(*This\id)
  EndIf
        ProcedureReturn ""
EndProcedure

Procedure UI_Gadget_SetText(*This.UI_Gadget_Inst, t.s)
  Protected *This_vt.UI_Gadget_vt = *This
  If (*This\id And IsGadget(*This\id))
          SetGadgetText(*This\id, t)
  EndIf
EndProcedure

Procedure UI_Gadget_SetToolTip(*This.UI_Gadget_Inst, tip.s)
  Protected *This_vt.UI_Gadget_vt = *This
        *This\tooltip = tip
  If (*This\id And IsGadget(*This\id))
          GadgetToolTip(*This\id, tip)
  EndIf
EndProcedure

Procedure.s UI_Gadget_GetToolTip(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
        ProcedureReturn *This\tooltip
EndProcedure

Procedure UI_Gadget_SetPosition(*This.UI_Gadget_Inst, nx.i, ny.i, nw.i, nh.i)
  Protected *This_vt.UI_Gadget_vt = *This
        *This\x = nx : *This\y = ny : *This\width = nw : *This\height = nh
  If (*This\id And IsGadget(*This\id))
          ResizeGadget(*This\id, nx, ny, nw, nh)
  EndIf
EndProcedure

Procedure UI_Gadget_SetVisible(*This.UI_Gadget_Inst, v.b)
  Protected *This_vt.UI_Gadget_vt = *This
        *This\isVisible = v
  If (*This\id And IsGadget(*This\id))
          HideGadget(*This\id, 1 - v)
  EndIf
EndProcedure

Procedure UI_Gadget_SetEnabled(*This.UI_Gadget_Inst, e.b)
  Protected *This_vt.UI_Gadget_vt = *This
        *This\isEnabled = e
  If (*This\id And IsGadget(*This\id))
          DisableGadget(*This\id, 1 - e)
  EndIf
EndProcedure

Procedure UI_Gadget_SetColor(*This.UI_Gadget_Inst, colorType.i, color.i)
  Protected *This_vt.UI_Gadget_vt = *This
  If (*This\id And IsGadget(*This\id))
          SetGadgetColor(*This\id, colorType, color)
  EndIf
EndProcedure

Procedure.i UI_Gadget_GetColor(*This.UI_Gadget_Inst, colorType.i)
  Protected *This_vt.UI_Gadget_vt = *This
  If (*This\id And IsGadget(*This\id))
          ProcedureReturn GetGadgetColor(*This\id, colorType)
  EndIf
        ProcedureReturn -1
EndProcedure

Procedure UI_Gadget_SetFont(*This.UI_Gadget_Inst, font.i)
  Protected *This_vt.UI_Gadget_vt = *This
        *This\fontID = font
  If (*This\id And IsGadget(*This\id))
          SetGadgetFont(*This\id, font)
  EndIf
EndProcedure

Procedure UI_Gadget_SetFocus(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
  If (*This\id And IsGadget(*This\id))
          SetActiveGadget(*This\id)
  EndIf
EndProcedure

Procedure UI_Gadget_Free(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
  If (*This\id And IsGadget(*This\id))
          FreeGadget(*This\id)
          *This\id = 0
  EndIf
EndProcedure

Procedure UI_Gadget_OnClick(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
EndProcedure

Procedure UI_Gadget_OnChange(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
EndProcedure

Procedure UI_Gadget_OnFocus(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
EndProcedure

Procedure UI_Gadget_OnLostFocus(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
EndProcedure

Procedure UI_Gadget_OnRightClick(*This.UI_Gadget_Inst)
  Protected *This_vt.UI_Gadget_vt = *This
EndProcedure

Procedure UI_Gadget_OnCustomEvent(*This.UI_Gadget_Inst, eventType.i)
  Protected *This_vt.UI_Gadget_vt = *This
EndProcedure

Procedure UI_Window_Init(*This.UI_Window_Inst, title_p.s, x_p.i = #PB_Ignore, y_p.i = #PB_Ignore, w_p.i = 640, h_p.i = 480, flags_p.i = #PB_Window_SystemMenu | #PB_Window_ScreenCentered | #PB_Window_SizeGadget | #PB_Window_MinimizeGadget | #PB_Window_MaximizeGadget, parent_p.i = 0)
  Protected *This_vt.UI_Window_vt = *This
        *This\title = title_p
        *This\flags = flags_p
        *This\parentID = parent_p
        *This\id = OpenWindow(#PB_Any, x_p, y_p, w_p, h_p, title_p, flags_p, parent_p)
  If (*This\id)
          UI_RegisterWindow(*This\id, @*This)
          *This\x = WindowX(*This\id)
          *This\y = WindowY(*This\id)
          *This\width = WindowWidth(*This\id)
          *This\height = WindowHeight(*This\id)
          *This\isVisible = #True
          *This\isEnabled = #True
  EndIf
EndProcedure

Procedure UI_Window_SetTitle(*This.UI_Window_Inst, t.s)
  Protected *This_vt.UI_Window_vt = *This
        *This\title = t
  If (*This\id And IsWindow(*This\id))
          SetWindowTitle(*This\id, t)
  EndIf
EndProcedure

Procedure.s UI_Window_GetTitle(*This.UI_Window_Inst)
  Protected *This_vt.UI_Window_vt = *This
  If (*This\id And IsWindow(*This\id))
          ProcedureReturn GetWindowTitle(*This\id)
  EndIf
        ProcedureReturn *This\title
EndProcedure

Procedure UI_Window_SetPosition(*This.UI_Window_Inst, nx.i, ny.i, nw.i, nh.i)
  Protected *This_vt.UI_Window_vt = *This
        *This\x = nx : *This\y = ny : *This\width = nw : *This\height = nh
  If (*This\id And IsWindow(*This\id))
          ResizeWindow(*This\id, nx, ny, nw, nh)
  EndIf
EndProcedure

Procedure UI_Window_SetVisible(*This.UI_Window_Inst, v.b)
  Protected *This_vt.UI_Window_vt = *This
        *This\isVisible = v
  If (*This\id And IsWindow(*This\id))
          HideWindow(*This\id, 1 - v)
  EndIf
EndProcedure

Procedure UI_Window_SetEnabled(*This.UI_Window_Inst, e.b)
  Protected *This_vt.UI_Window_vt = *This
        *This\isEnabled = e
  If (*This\id And IsWindow(*This\id))
          DisableWindow(*This\id, 1 - e)
  EndIf
EndProcedure

Procedure UI_Window_Close(*This.UI_Window_Inst)
  Protected *This_vt.UI_Window_vt = *This
  If (*This\id And IsWindow(*This\id))
          UI_UnregisterWindow(*This\id)
          CloseWindow(*This\id)
          *This\id = 0
  EndIf
EndProcedure

Procedure UI_Window_Free(*This.UI_Window_Inst)
  Protected *This_vt.UI_Window_vt = *This
        *This_vt\Close()
EndProcedure

Procedure.b UI_Window_OnClose(*This.UI_Window_Inst)
  Protected *This_vt.UI_Window_vt = *This
        ; Return #True to allow window closing, #False to prevent
        ProcedureReturn #True
EndProcedure

Procedure UI_Window_OnResize(*This.UI_Window_Inst, newW.i, newH.i)
  Protected *This_vt.UI_Window_vt = *This
        *This\width = newW
        *This\height = newH
EndProcedure

Procedure UI_Window_OnMove(*This.UI_Window_Inst, newX.i, newY.i)
  Protected *This_vt.UI_Window_vt = *This
        *This\x = newX
        *This\y = newY
EndProcedure

Procedure UI_Window_OnMinimize(*This.UI_Window_Inst)
  Protected *This_vt.UI_Window_vt = *This
EndProcedure

Procedure UI_Window_OnMaximize(*This.UI_Window_Inst)
  Protected *This_vt.UI_Window_vt = *This
EndProcedure

Procedure UI_Window_OnRestore(*This.UI_Window_Inst)
  Protected *This_vt.UI_Window_vt = *This
EndProcedure

Procedure UI_Window_OnChildEvent(*This.UI_Window_Inst, *child.UI_Gadget_vt, eventType.i)
  Protected *This_vt.UI_Window_vt = *This
EndProcedure

Procedure UI_Application_Init(*This.UI_Application_Inst)
  Protected *This_vt.UI_Application_vt = *This
        *This\isRunning = #False
        *This\mainWindow = #Null
EndProcedure

Procedure UI_Application_SetMainWindow(*This.UI_Application_Inst, *win_p.UI_Window_vt)
  Protected *This_vt.UI_Application_vt = *This
        *This\mainWindow = *win_p
EndProcedure

Procedure.i UI_Application_GetMainWindow(*This.UI_Application_Inst)
  Protected *This_vt.UI_Application_vt = *This
        ProcedureReturn *This\mainWindow
EndProcedure

Procedure UI_Application_Run(*This.UI_Application_Inst, *mainWin_p.UI_Window_vt = 0)
  Protected *This_vt.UI_Application_vt = *This
  If (*mainWin_p)
          *This\mainWindow = *mainWin_p
  EndIf
        *This\isRunning = #True
        Protected ev.i, evGadget.i, evWin.i, evType.i
  
  While (*This\isRunning)
          ev = WaitWindowEvent()
          evWin = EventWindow()
          evType = EventType()
  
  Select (ev)
            Case #PB_Event_Gadget:
              evGadget = EventGadget()
  If (FindMapElement(UI_GadgetMap(), Str(evGadget)))
                Protected *targetGadget.UI_Gadget_vt = UI_GadgetMap()
  If (*targetGadget)
  Select (evType)
                    Case #PB_EventType_LeftClick:   *targetGadget\OnClick()
                    Case #PB_EventType_Change:      *targetGadget\OnChange()
                    Case #PB_EventType_Focus:       *targetGadget\OnFocus()
                    Case #PB_EventType_LostFocus:   *targetGadget\OnLostFocus()
                    Case #PB_EventType_RightClick:  *targetGadget\OnRightClick()
                    Default:                        *targetGadget\OnCustomEvent(evType)
  EndSelect
  EndIf
  EndIf
  
            Case #PB_Event_CloseWindow:
  If (FindMapElement(UI_WindowMap(), Str(evWin)))
                Protected *targetWin.UI_Window_vt = UI_WindowMap()
  If (*targetWin)
  If (*targetWin\OnClose())
                    *targetWin\Close()
                    UI_UnregisterWindow(evWin)
  If (*targetWin = *This\mainWindow Or MapSize(UI_WindowMap()) = 0)
                      *This\isRunning = #False
  EndIf
  EndIf
  EndIf
  Else
                CloseWindow(evWin)
  EndIf
  
            Case #PB_Event_SizeWindow:
  If (FindMapElement(UI_WindowMap(), Str(evWin)))
                Protected *targetWinSize.UI_Window_vt = UI_WindowMap()
  If (*targetWinSize)
                  *targetWinSize\OnResize(WindowWidth(evWin), WindowHeight(evWin))
  EndIf
  EndIf
  
            Case #PB_Event_MoveWindow:
  If (FindMapElement(UI_WindowMap(), Str(evWin)))
                Protected *targetWinMove.UI_Window_vt = UI_WindowMap()
  If (*targetWinMove)
                  *targetWinMove\OnMove(WindowX(evWin), WindowY(evWin))
  EndIf
  EndIf
  
            Case #PB_Event_MinimizeWindow:
  If (FindMapElement(UI_WindowMap(), Str(evWin)))
                Protected *targetWinMin.UI_Window_vt = UI_WindowMap()
  If (*targetWinMin)
                  *targetWinMin\OnMinimize()
  EndIf
  EndIf
  
            Case #PB_Event_MaximizeWindow:
  If (FindMapElement(UI_WindowMap(), Str(evWin)))
                Protected *targetWinMax.UI_Window_vt = UI_WindowMap()
  If (*targetWinMax)
                  *targetWinMax\OnMaximize()
  EndIf
  EndIf
  
            Case #PB_Event_RestoreWindow:
  If (FindMapElement(UI_WindowMap(), Str(evWin)))
                Protected *targetWinRest.UI_Window_vt = UI_WindowMap()
  If (*targetWinRest)
                  *targetWinRest\OnRestore()
  EndIf
  EndIf
  EndSelect
  Wend
EndProcedure

Procedure UI_Application_Quit(*This.UI_Application_Inst)
  Protected *This_vt.UI_Application_vt = *This
        *This\isRunning = #False
EndProcedure

Procedure UI_CustomGadget_Init(*This.UI_CustomGadget_Inst, x_p.i, y_p.i, w_p.i = 100, h_p.i = 30, flags_p.i = 0)
  Protected *This_vt.UI_CustomGadget_vt = *This
        *This\x = x_p : *This\y = y_p : *This\width = w_p : *This\height = h_p
        *This\isVisible = #True : *This\isEnabled = #True
        *This\isHovered = #False : *This\isPressed = #False
        *This\id = CanvasGadget(#PB_Any, x_p, y_p, w_p, h_p, flags_p | #PB_Canvas_Keyboard)
  If (*This\id)
          UI_RegisterGadget(*This\id, *This)
          *This_vt\Redraw()
  EndIf
EndProcedure

Procedure UI_CustomGadget_Redraw(*This.UI_CustomGadget_Inst)
  Protected *This_vt.UI_CustomGadget_vt = *This
  If (*This\id And IsGadget(*This\id))
  If (StartDrawing(CanvasOutput(*This\id)))
            *This_vt\OnPaint(OutputWidth(), OutputHeight())
            StopDrawing()
  EndIf
  EndIf
EndProcedure

Procedure UI_CustomGadget_OnMouseEnter(*This.UI_CustomGadget_Inst)
  Protected *This_vt.UI_CustomGadget_vt = *This
EndProcedure

Procedure UI_CustomGadget_OnMouseLeave(*This.UI_CustomGadget_Inst)
  Protected *This_vt.UI_CustomGadget_vt = *This
EndProcedure

Procedure UI_CustomGadget_OnMouseDown(*This.UI_CustomGadget_Inst, mx.i, my.i, button.i)
  Protected *This_vt.UI_CustomGadget_vt = *This
EndProcedure

Procedure UI_CustomGadget_OnMouseUp(*This.UI_CustomGadget_Inst, mx.i, my.i, button.i)
  Protected *This_vt.UI_CustomGadget_vt = *This
EndProcedure

Procedure UI_CustomGadget_OnMouseMove(*This.UI_CustomGadget_Inst, mx.i, my.i)
  Protected *This_vt.UI_CustomGadget_vt = *This
EndProcedure

Procedure UI_CustomGadget_OnKeyDown(*This.UI_CustomGadget_Inst, key.i)
  Protected *This_vt.UI_CustomGadget_vt = *This
EndProcedure

Procedure UI_CustomGadget_OnCustomEvent(*This.UI_CustomGadget_Inst, eventType.i)
  Protected *This_vt.UI_CustomGadget_vt = *This
  Select (eventType)
          Case #PB_EventType_MouseEnter:
            *This\isHovered = #True
            *This_vt\OnMouseEnter()
            *This_vt\Redraw()
  
          Case #PB_EventType_MouseLeave:
            *This\isHovered = #False
            *This\isPressed = #False
            *This_vt\OnMouseLeave()
            *This_vt\Redraw()
  
          Case #PB_EventType_LeftButtonDown:
            *This\isPressed = #True
            *This\mouseX = GetGadgetAttribute(*This\id, #PB_Canvas_MouseX)
            *This\mouseY = GetGadgetAttribute(*This\id, #PB_Canvas_MouseY)
            *This_vt\OnMouseDown(*This\mouseX, *This\mouseY, 1)
            *This_vt\Redraw()
  
          Case #PB_EventType_LeftButtonUp:
            Protected wasPressed.b = *This\isPressed
            *This\isPressed = #False
            *This\mouseX = GetGadgetAttribute(*This\id, #PB_Canvas_MouseX)
            *This\mouseY = GetGadgetAttribute(*This\id, #PB_Canvas_MouseY)
            *This_vt\OnMouseUp(*This\mouseX, *This\mouseY, 1)
  If (wasPressed)
              *This_vt\OnClick()
  EndIf
            *This_vt\Redraw()
  
          Case #PB_EventType_MouseMove:
            *This\mouseX = GetGadgetAttribute(*This\id, #PB_Canvas_MouseX)
            *This\mouseY = GetGadgetAttribute(*This\id, #PB_Canvas_MouseY)
            *This_vt\OnMouseMove(*This\mouseX, *This\mouseY)
            *This_vt\Redraw()
  
          Case #PB_EventType_KeyDown:
            *This_vt\OnKeyDown(GetGadgetAttribute(*This\id, #PB_Canvas_Key))
            *This_vt\Redraw()
  EndSelect
EndProcedure

Procedure UI_CustomGadget_Free(*This.UI_CustomGadget_Inst)
  Protected *This_vt.UI_CustomGadget_vt = *This
  If (*This\id)
          UI_UnregisterGadget(*This\id)
          UI_Gadget_Free(*This)
  EndIf
EndProcedure

Procedure UI_Button_Init(*This.UI_Button_Inst, x_p.i, y_p.i, w_p.i = 120, h_p.i = 30, text_p.s = "Button", flags_p.i = 0)
  Protected *This_vt.UI_Button_vt = *This
        *This\x = x_p : *This\y = y_p : *This\width = w_p : *This\height = h_p
        *This\isVisible = #True : *This\isEnabled = #True
        *This\id = ButtonGadget(#PB_Any, x_p, y_p, w_p, h_p, text_p, flags_p)
  If (*This\id)
          UI_RegisterGadget(*This\id, *This)
  EndIf
EndProcedure

Procedure UI_Button_Free(*This.UI_Button_Inst)
  Protected *This_vt.UI_Button_vt = *This
  If (*This\id)
          UI_UnregisterGadget(*This\id)
          UI_Gadget_Free(*This)
  EndIf
EndProcedure

Procedure UI_TextBox_Init(*This.UI_TextBox_Inst, x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, defaultText_p.s = "", flags_p.i = 0)
  Protected *This_vt.UI_TextBox_vt = *This
        *This\x = x_p : *This\y = y_p : *This\width = w_p : *This\height = h_p
        *This\isVisible = #True : *This\isEnabled = #True
        *This\id = StringGadget(#PB_Any, x_p, y_p, w_p, h_p, defaultText_p, flags_p)
  If (*This\id)
          UI_RegisterGadget(*This\id, *This)
  EndIf
EndProcedure

Procedure.b UI_TextBox_IsReadOnly(*This.UI_TextBox_Inst)
  Protected *This_vt.UI_TextBox_vt = *This
  If (*This\id And IsGadget(*This\id))
          ProcedureReturn GetGadgetAttribute(*This\id, #PB_String_ReadOnly)
  EndIf
        ProcedureReturn #False
EndProcedure

Procedure UI_TextBox_SetReadOnly(*This.UI_TextBox_Inst, ro.b)
  Protected *This_vt.UI_TextBox_vt = *This
  If (*This\id And IsGadget(*This\id))
          SetGadgetAttribute(*This\id, #PB_String_ReadOnly, ro)
  EndIf
EndProcedure

Procedure UI_TextBox_Free(*This.UI_TextBox_Inst)
  Protected *This_vt.UI_TextBox_vt = *This
  If (*This\id)
          UI_UnregisterGadget(*This\id)
          UI_Gadget_Free(*This)
  EndIf
EndProcedure

Procedure UI_Label_Init(*This.UI_Label_Inst, x_p.i, y_p.i, w_p.i = 150, h_p.i = 20, text_p.s = "", flags_p.i = 0)
  Protected *This_vt.UI_Label_vt = *This
        *This\x = x_p : *This\y = y_p : *This\width = w_p : *This\height = h_p
        *This\isVisible = #True : *This\isEnabled = #True
        *This\id = TextGadget(#PB_Any, x_p, y_p, w_p, h_p, text_p, flags_p)
  If (*This\id)
          UI_RegisterGadget(*This\id, *This)
  EndIf
EndProcedure

Procedure UI_Label_Free(*This.UI_Label_Inst)
  Protected *This_vt.UI_Label_vt = *This
  If (*This\id)
          UI_UnregisterGadget(*This\id)
          UI_Gadget_Free(*This)
  EndIf
EndProcedure

Procedure UI_CheckBox_Init(*This.UI_CheckBox_Inst, x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, text_p.s = "CheckBox", flags_p.i = 0)
  Protected *This_vt.UI_CheckBox_vt = *This
        *This\x = x_p : *This\y = y_p : *This\width = w_p : *This\height = h_p
        *This\isVisible = #True : *This\isEnabled = #True
        *This\id = CheckBoxGadget(#PB_Any, x_p, y_p, w_p, h_p, text_p, flags_p)
  If (*This\id)
          UI_RegisterGadget(*This\id, *This)
  EndIf
EndProcedure

Procedure.b UI_CheckBox_IsChecked(*This.UI_CheckBox_Inst)
  Protected *This_vt.UI_CheckBox_vt = *This
  If (*This\id And IsGadget(*This\id))
          ProcedureReturn GetGadgetState(*This\id)
  EndIf
        ProcedureReturn #False
EndProcedure

Procedure UI_CheckBox_SetChecked(*This.UI_CheckBox_Inst, checked.b)
  Protected *This_vt.UI_CheckBox_vt = *This
  If (*This\id And IsGadget(*This\id))
          SetGadgetState(*This\id, checked)
  EndIf
EndProcedure

Procedure UI_CheckBox_Free(*This.UI_CheckBox_Inst)
  Protected *This_vt.UI_CheckBox_vt = *This
  If (*This\id)
          UI_UnregisterGadget(*This\id)
          UI_Gadget_Free(*This)
  EndIf
EndProcedure

Procedure UI_ProgressBar_Init(*This.UI_ProgressBar_Inst, x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
  Protected *This_vt.UI_ProgressBar_vt = *This
        *This\x = x_p : *This\y = y_p : *This\width = w_p : *This\height = h_p
        *This\minVal = min_p : *This\maxVal = max_p
        *This\isVisible = #True : *This\isEnabled = #True
        *This\id = ProgressBarGadget(#PB_Any, x_p, y_p, w_p, h_p, min_p, max_p, flags_p)
  If (*This\id)
          UI_RegisterGadget(*This\id, *This)
  EndIf
EndProcedure

Procedure.i UI_ProgressBar_GetValue(*This.UI_ProgressBar_Inst)
  Protected *This_vt.UI_ProgressBar_vt = *This
  If (*This\id And IsGadget(*This\id))
          ProcedureReturn GetGadgetState(*This\id)
  EndIf
        ProcedureReturn 0
EndProcedure

Procedure UI_ProgressBar_SetValue(*This.UI_ProgressBar_Inst, v.i)
  Protected *This_vt.UI_ProgressBar_vt = *This
  If (*This\id And IsGadget(*This\id))
          SetGadgetState(*This\id, v)
  EndIf
EndProcedure

Procedure UI_ProgressBar_Free(*This.UI_ProgressBar_Inst)
  Protected *This_vt.UI_ProgressBar_vt = *This
  If (*This\id)
          UI_UnregisterGadget(*This\id)
          UI_Gadget_Free(*This)
  EndIf
EndProcedure

Procedure UI_Slider_Init(*This.UI_Slider_Inst, x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
  Protected *This_vt.UI_Slider_vt = *This
        *This\x = x_p : *This\y = y_p : *This\width = w_p : *This\height = h_p
        *This\minVal = min_p : *This\maxVal = max_p
        *This\isVisible = #True : *This\isEnabled = #True
        *This\id = TrackBarGadget(#PB_Any, x_p, y_p, w_p, h_p, min_p, max_p, flags_p)
  If (*This\id)
          UI_RegisterGadget(*This\id, *This)
  EndIf
EndProcedure

Procedure.i UI_Slider_GetValue(*This.UI_Slider_Inst)
  Protected *This_vt.UI_Slider_vt = *This
  If (*This\id And IsGadget(*This\id))
          ProcedureReturn GetGadgetState(*This\id)
  EndIf
        ProcedureReturn 0
EndProcedure

Procedure UI_Slider_SetValue(*This.UI_Slider_Inst, v.i)
  Protected *This_vt.UI_Slider_vt = *This
  If (*This\id And IsGadget(*This\id))
          SetGadgetState(*This\id, v)
  EndIf
EndProcedure

Procedure UI_Slider_Free(*This.UI_Slider_Inst)
  Protected *This_vt.UI_Slider_vt = *This
  If (*This\id)
          UI_UnregisterGadget(*This\id)
          UI_Gadget_Free(*This)
  EndIf
EndProcedure

Procedure UI_ComboBox_Init(*This.UI_ComboBox_Inst, x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, flags_p.i = 0)
  Protected *This_vt.UI_ComboBox_vt = *This
        *This\x = x_p : *This\y = y_p : *This\width = w_p : *This\height = h_p
        *This\isVisible = #True : *This\isEnabled = #True
        *This\id = ComboBoxGadget(#PB_Any, x_p, y_p, w_p, h_p, flags_p)
  If (*This\id)
          UI_RegisterGadget(*This\id, *This)
  EndIf
EndProcedure

Procedure UI_ComboBox_AddItem(*This.UI_ComboBox_Inst, text.s)
  Protected *This_vt.UI_ComboBox_vt = *This
  If (*This\id And IsGadget(*This\id))
          AddGadgetItem(*This\id, -1, text)
  EndIf
EndProcedure

Procedure.i UI_ComboBox_GetSelectedIndex(*This.UI_ComboBox_Inst)
  Protected *This_vt.UI_ComboBox_vt = *This
  If (*This\id And IsGadget(*This\id))
          ProcedureReturn GetGadgetState(*This\id)
  EndIf
        ProcedureReturn -1
EndProcedure

Procedure UI_ComboBox_SetSelectedIndex(*This.UI_ComboBox_Inst, idx.i)
  Protected *This_vt.UI_ComboBox_vt = *This
  If (*This\id And IsGadget(*This\id))
          SetGadgetState(*This\id, idx)
  EndIf
EndProcedure

Procedure.s UI_ComboBox_GetSelectedItem(*This.UI_ComboBox_Inst)
  Protected *This_vt.UI_ComboBox_vt = *This
        Protected idx.i = *This_vt\GetSelectedIndex()
  If (idx >= 0 And *This\id And IsGadget(*This\id))
          ProcedureReturn GetGadgetItemText(*This\id, idx)
  EndIf
        ProcedureReturn ""
EndProcedure

Procedure UI_ComboBox_Clear(*This.UI_ComboBox_Inst)
  Protected *This_vt.UI_ComboBox_vt = *This
  If (*This\id And IsGadget(*This\id))
          ClearGadgetItems(*This\id)
  EndIf
EndProcedure

Procedure UI_ComboBox_Free(*This.UI_ComboBox_Inst)
  Protected *This_vt.UI_ComboBox_vt = *This
  If (*This\id)
          UI_UnregisterGadget(*This\id)
          UI_Gadget_Free(*This)
  EndIf
EndProcedure

Procedure UI_Controls_ToggleSwitch_Init(*This.UI_Controls_ToggleSwitch_Inst, x_p.i, y_p.i, w_p.i = 50, h_p.i = 26, defaultState_p.b = #False)
  Protected *This_vt.UI_Controls_ToggleSwitch_vt = *This
        UI_CustomGadget_Init(*This, x_p, y_p, w_p, h_p)
        *This\isChecked = defaultState_p
        *This\activeColor = RGB(52, 199, 89)      ; iOS Green
        *This\inactiveColor = RGB(200, 200, 205)  ; Light Gray
        *This_vt\Redraw()
EndProcedure

Procedure.b UI_Controls_ToggleSwitch_IsChecked(*This.UI_Controls_ToggleSwitch_Inst)
  Protected *This_vt.UI_Controls_ToggleSwitch_vt = *This
        ProcedureReturn *This\isChecked
EndProcedure

Procedure UI_Controls_ToggleSwitch_SetChecked(*This.UI_Controls_ToggleSwitch_Inst, state.b)
  Protected *This_vt.UI_Controls_ToggleSwitch_vt = *This
        *This\isChecked = state
        *This_vt\Redraw()
EndProcedure

Procedure UI_Controls_ToggleSwitch_OnClick(*This.UI_Controls_ToggleSwitch_Inst)
  Protected *This_vt.UI_Controls_ToggleSwitch_vt = *This
        *This\isChecked = 1 - *This\isChecked
        *This_vt\Redraw()
        *This_vt\OnChange()
EndProcedure

Procedure UI_Controls_ToggleSwitch_OnPaint(*This.UI_Controls_ToggleSwitch_Inst, w.i, h.i)
  Protected *This_vt.UI_Controls_ToggleSwitch_vt = *This
        ; Background fill
        Box(0, 0, w, h, RGB(245, 245, 247))
  
        ; Main Pill
        Protected pillColor.i = *This\inactiveColor
  If (*This\isChecked)
          pillColor = *This\activeColor
  EndIf
  If (*This\isHovered)
          ; Slightly brighten on hover
          pillColor = RGB(Red(pillColor) + 15, Green(pillColor) + 15, Blue(pillColor) + 15)
  EndIf
  
        Protected radius.i = h / 2
        RoundBox(1, 1, w - 2, h - 2, radius, radius, pillColor)
  
        ; White circular thumb knob
        Protected knobPadding.i = 3
        Protected knobDiameter.i = h - (knobPadding * 2)
        Protected knobRadius.i = knobDiameter / 2
        Protected knobX.i = knobPadding
  If (*This\isChecked)
          knobX = w - knobDiameter - knobPadding
  EndIf
  
        ; Subtle shadow under knob
        Circle(knobX + knobRadius, radius + 1, knobRadius, RGB(180, 180, 180))
        ; Knob circle
        Circle(knobX + knobRadius, radius, knobRadius, RGB(255, 255, 255))
EndProcedure

Procedure GreetButton_BindControls(*This.GreetButton_Inst, *input.UI_TextBox_vt, *lbl.UI_Label_vt)
  Protected *This_vt.GreetButton_vt = *This
      *This\nameInput = *input
      *This\statusLabel = *lbl
EndProcedure

Procedure GreetButton_OnClick(*This.GreetButton_Inst)
  Protected *This_vt.GreetButton_vt = *This
      Protected userName.s = "Visiteur"
      If *This\nameInput
        Protected txt.s = *This\nameInput\GetText()
        If txt <> ""
          userName = txt
        EndIf
      EndIf
      If *This\statusLabel
        *This\statusLabel\SetText("Bonjour " + userName + " ! Heure : " + FormatDate("%hh:%ii:%ss", Date()))
      EndIf
EndProcedure

Procedure ModeSwitch_BindLabel(*This.ModeSwitch_Inst, *lbl.UI_Label_vt)
  Protected *This_vt.ModeSwitch_vt = *This
      *This\statusLabel = *lbl
EndProcedure

Procedure ModeSwitch_OnChange(*This.ModeSwitch_Inst)
  Protected *This_vt.ModeSwitch_vt = *This
      If *This\statusLabel
        If *This_vt\IsChecked()
          *This\statusLabel\SetText("Statut : Mode TURBO Active [ON]")
        Else
          *This\statusLabel\SetText("Statut : Mode Standard [OFF]")
        EndIf
      EndIf
EndProcedure

Procedure VolumeSlider_BindProgress(*This.VolumeSlider_Inst, *pb.UI_ProgressBar_vt, *lbl.UI_Label_vt)
  Protected *This_vt.VolumeSlider_vt = *This
      *This\progress = *pb
      *This\valLabel = *lbl
EndProcedure

Procedure VolumeSlider_OnCustomEvent(*This.VolumeSlider_Inst, eventType.i)
  Protected *This_vt.VolumeSlider_vt = *This
      Protected curVal.i = *This_vt\GetValue()
      If *This\progress
        *This\progress\SetValue(curVal)
      EndIf
      If *This\valLabel
        *This\valLabel\SetText("Niveau : " + Str(curVal) + "%")
      EndIf
EndProcedure

Procedure MainWindow_Init(*This.MainWindow_Inst)
  Protected *This_vt.MainWindow_vt = *This
      UI_Window_Init(*This, "PureBasic OOP - Framework GUI (Syntaxe Standard)", #PB_Ignore, #PB_Ignore, 480, 420, #PB_Window_SystemMenu | #PB_Window_ScreenCentered)
      UI_RegisterWindow(*This\id, *This)
  
      ; Titre
      *This\lblTitle = New_UI_Label(20, 15, 440, 25, "=== Demonstration GUI PureBasic OOP (Classique) ===")
      
      ; Section Saisie & Bouton
      *This\lblPrompt = New_UI_Label(20, 55, 100, 20, "Votre Nom :")
      *This\txtInput = New_UI_TextBox(120, 52, 200, 25, "Developpeur PureBasic")
      
      *This\btnGreet = New_GreetButton(330, 50, 130, 28, "Saluer !")
  
      ; Section Toggle Switch (Custom Gadget sur Canvas)
      *This\lblSwitch = New_UI_Label(20, 100, 200, 20, "Custom Toggle Switch :")
      *This\switchTurbo = New_ModeSwitch(230, 97, 50, 26, #False)
  
      ; Section Slider & ProgressBar
      *This\lblSlider = New_UI_Label(20, 145, 150, 20, "Niveau : 50%")
      *This\sliderVol = New_VolumeSlider(20, 170, 440, 25, 0, 100)
      *This\sliderVol\SetValue(50)
  
      *This\progBar = New_UI_ProgressBar(20, 210, 440, 20, 0, 100)
      *This\progBar\SetValue(50)
  
      ; Section Theme ComboBox
      Protected *lblCombo.UI_Label_vt = New_UI_Label(20, 250, 100, 20, "Theme UI :")
      *This\comboTheme = New_UI_ComboBox(120, 247, 180, 26)
      *This\comboTheme\AddItem("Theme Sombre Moderne")
      *This\comboTheme\AddItem("Theme Clair Classique")
      *This\comboTheme\AddItem("Theme PureBasic Silk")
      *This\comboTheme\SetSelectedIndex(0)
  
      ; Case a cocher
      Protected *chkOption.UI_CheckBox_vt = New_UI_CheckBox(20, 295, 250, 25, "Activer les notifications sonores")
      *chkOption\SetChecked(#True)
  
      ; Statut en bas
      *This\lblStatus = New_UI_Label(20, 340, 440, 30, "Pret. Cliquez sur le bouton ou interagissez avec les widgets.")
  
      ; Liaison des controles
      *This\btnGreet\BindControls(*This\txtInput, *This\lblStatus)
      *This\switchTurbo\BindLabel(*This\lblStatus)
      *This\sliderVol\BindProgress(*This\progBar, *This\lblSlider)
EndProcedure

Procedure.b MainWindow_OnClose(*This.MainWindow_Inst)
  Protected *This_vt.MainWindow_vt = *This
      ProcedureReturn #True ; Autorise la fermeture de la fenetre
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  UI_Window_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Window_SetTitle()
    Data.i @UI_Window_GetTitle()
    Data.i @UI_Window_SetPosition()
    Data.i @UI_Window_SetVisible()
    Data.i @UI_Window_SetEnabled()
    Data.i @UI_Window_Close()
    Data.i @UI_Window_Free()
    Data.i @UI_Window_OnClose()
    Data.i @UI_Window_OnResize()
    Data.i @UI_Window_OnMove()
    Data.i @UI_Window_OnMinimize()
    Data.i @UI_Window_OnMaximize()
    Data.i @UI_Window_OnRestore()
    Data.i @UI_Window_OnChildEvent()
  UI_Application_VTable_Data:
    Data.i @UI_Application_SetMainWindow()
    Data.i @UI_Application_GetMainWindow()
    Data.i @UI_Application_Run()
    Data.i @UI_Application_Quit()
  UI_Button_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_Button_Free()
    Data.i @UI_Gadget_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_Gadget_OnCustomEvent()
  UI_TextBox_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_TextBox_Free()
    Data.i @UI_Gadget_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_Gadget_OnCustomEvent()
    Data.i @UI_TextBox_IsReadOnly()
    Data.i @UI_TextBox_SetReadOnly()
  UI_Label_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_Label_Free()
    Data.i @UI_Gadget_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_Gadget_OnCustomEvent()
  UI_CheckBox_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_CheckBox_Free()
    Data.i @UI_Gadget_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_Gadget_OnCustomEvent()
    Data.i @UI_CheckBox_IsChecked()
    Data.i @UI_CheckBox_SetChecked()
  UI_ProgressBar_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_ProgressBar_Free()
    Data.i @UI_Gadget_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_Gadget_OnCustomEvent()
    Data.i @UI_ProgressBar_GetValue()
    Data.i @UI_ProgressBar_SetValue()
  UI_Slider_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_Slider_Free()
    Data.i @UI_Gadget_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_Gadget_OnCustomEvent()
    Data.i @UI_Slider_GetValue()
    Data.i @UI_Slider_SetValue()
  UI_ComboBox_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_ComboBox_Free()
    Data.i @UI_Gadget_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_Gadget_OnCustomEvent()
    Data.i @UI_ComboBox_AddItem()
    Data.i @UI_ComboBox_GetSelectedIndex()
    Data.i @UI_ComboBox_SetSelectedIndex()
    Data.i @UI_ComboBox_GetSelectedItem()
    Data.i @UI_ComboBox_Clear()
  UI_Controls_ToggleSwitch_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_CustomGadget_Free()
    Data.i @UI_Controls_ToggleSwitch_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_CustomGadget_OnCustomEvent()
    Data.i @UI_Controls_ToggleSwitch_OnPaint()
    Data.i @UI_CustomGadget_Redraw()
    Data.i @UI_CustomGadget_OnMouseEnter()
    Data.i @UI_CustomGadget_OnMouseLeave()
    Data.i @UI_CustomGadget_OnMouseDown()
    Data.i @UI_CustomGadget_OnMouseUp()
    Data.i @UI_CustomGadget_OnMouseMove()
    Data.i @UI_CustomGadget_OnKeyDown()
    Data.i @UI_Controls_ToggleSwitch_IsChecked()
    Data.i @UI_Controls_ToggleSwitch_SetChecked()
  GreetButton_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_Button_Free()
    Data.i @GreetButton_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_Gadget_OnCustomEvent()
    Data.i @GreetButton_BindControls()
  ModeSwitch_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_CustomGadget_Free()
    Data.i @UI_Controls_ToggleSwitch_OnClick()
    Data.i @ModeSwitch_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @UI_CustomGadget_OnCustomEvent()
    Data.i @UI_Controls_ToggleSwitch_OnPaint()
    Data.i @UI_CustomGadget_Redraw()
    Data.i @UI_CustomGadget_OnMouseEnter()
    Data.i @UI_CustomGadget_OnMouseLeave()
    Data.i @UI_CustomGadget_OnMouseDown()
    Data.i @UI_CustomGadget_OnMouseUp()
    Data.i @UI_CustomGadget_OnMouseMove()
    Data.i @UI_CustomGadget_OnKeyDown()
    Data.i @UI_Controls_ToggleSwitch_IsChecked()
    Data.i @UI_Controls_ToggleSwitch_SetChecked()
    Data.i @ModeSwitch_BindLabel()
  VolumeSlider_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Gadget_GetText()
    Data.i @UI_Gadget_SetText()
    Data.i @UI_Gadget_SetToolTip()
    Data.i @UI_Gadget_GetToolTip()
    Data.i @UI_Gadget_SetPosition()
    Data.i @UI_Gadget_SetVisible()
    Data.i @UI_Gadget_SetEnabled()
    Data.i @UI_Gadget_SetColor()
    Data.i @UI_Gadget_GetColor()
    Data.i @UI_Gadget_SetFont()
    Data.i @UI_Gadget_SetFocus()
    Data.i @UI_Slider_Free()
    Data.i @UI_Gadget_OnClick()
    Data.i @UI_Gadget_OnChange()
    Data.i @UI_Gadget_OnFocus()
    Data.i @UI_Gadget_OnLostFocus()
    Data.i @UI_Gadget_OnRightClick()
    Data.i @VolumeSlider_OnCustomEvent()
    Data.i @UI_Slider_GetValue()
    Data.i @UI_Slider_SetValue()
    Data.i @VolumeSlider_BindProgress()
  MainWindow_VTable_Data:
    Data.i @UI_Component_GetID()
    Data.i @UI_Component_GetTag()
    Data.i @UI_Component_SetTag()
    Data.i @UI_Component_GetX()
    Data.i @UI_Component_GetY()
    Data.i @UI_Component_GetWidth()
    Data.i @UI_Component_GetHeight()
    Data.i @UI_Component_IsVisible()
    Data.i @UI_Component_IsEnabled()
    Data.i @UI_Component_GetUserData()
    Data.i @UI_Component_SetUserData()
    Data.i @UI_Window_SetTitle()
    Data.i @UI_Window_GetTitle()
    Data.i @UI_Window_SetPosition()
    Data.i @UI_Window_SetVisible()
    Data.i @UI_Window_SetEnabled()
    Data.i @UI_Window_Close()
    Data.i @UI_Window_Free()
    Data.i @MainWindow_OnClose()
    Data.i @UI_Window_OnResize()
    Data.i @UI_Window_OnMove()
    Data.i @UI_Window_OnMinimize()
    Data.i @UI_Window_OnMaximize()
    Data.i @UI_Window_OnRestore()
    Data.i @UI_Window_OnChildEvent()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_UI_Window(title_p.s, x_p.i = #PB_Ignore, y_p.i = #PB_Ignore, w_p.i = 640, h_p.i = 480, flags_p.i = #PB_Window_SystemMenu | #PB_Window_ScreenCentered | #PB_Window_SizeGadget | #PB_Window_MinimizeGadget | #PB_Window_MaximizeGadget, parent_p.i = 0)
  Protected *obj.UI_Window_Inst = AllocateStructure(UI_Window_Inst)
  If *obj
    *obj\VTable = ?UI_Window_VTable_Data
    UI_Window_Init(*obj, title_p, x_p, y_p, w_p, h_p, flags_p, parent_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_Window(*obj.UI_Window_Inst)
  If *obj
    UI_Window_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_Application()
  Protected *obj.UI_Application_Inst = AllocateStructure(UI_Application_Inst)
  If *obj
    *obj\VTable = ?UI_Application_VTable_Data
    UI_Application_Init(*obj)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_Application(*obj.UI_Application_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_Button(x_p.i, y_p.i, w_p.i = 120, h_p.i = 30, text_p.s = "Button", flags_p.i = 0)
  Protected *obj.UI_Button_Inst = AllocateStructure(UI_Button_Inst)
  If *obj
    *obj\VTable = ?UI_Button_VTable_Data
    UI_Button_Init(*obj, x_p, y_p, w_p, h_p, text_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_Button(*obj.UI_Button_Inst)
  If *obj
    UI_Button_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_TextBox(x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, defaultText_p.s = "", flags_p.i = 0)
  Protected *obj.UI_TextBox_Inst = AllocateStructure(UI_TextBox_Inst)
  If *obj
    *obj\VTable = ?UI_TextBox_VTable_Data
    UI_TextBox_Init(*obj, x_p, y_p, w_p, h_p, defaultText_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_TextBox(*obj.UI_TextBox_Inst)
  If *obj
    UI_TextBox_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_Label(x_p.i, y_p.i, w_p.i = 150, h_p.i = 20, text_p.s = "", flags_p.i = 0)
  Protected *obj.UI_Label_Inst = AllocateStructure(UI_Label_Inst)
  If *obj
    *obj\VTable = ?UI_Label_VTable_Data
    UI_Label_Init(*obj, x_p, y_p, w_p, h_p, text_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_Label(*obj.UI_Label_Inst)
  If *obj
    UI_Label_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_CheckBox(x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, text_p.s = "CheckBox", flags_p.i = 0)
  Protected *obj.UI_CheckBox_Inst = AllocateStructure(UI_CheckBox_Inst)
  If *obj
    *obj\VTable = ?UI_CheckBox_VTable_Data
    UI_CheckBox_Init(*obj, x_p, y_p, w_p, h_p, text_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_CheckBox(*obj.UI_CheckBox_Inst)
  If *obj
    UI_CheckBox_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_ProgressBar(x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
  Protected *obj.UI_ProgressBar_Inst = AllocateStructure(UI_ProgressBar_Inst)
  If *obj
    *obj\VTable = ?UI_ProgressBar_VTable_Data
    UI_ProgressBar_Init(*obj, x_p, y_p, w_p, h_p, min_p, max_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_ProgressBar(*obj.UI_ProgressBar_Inst)
  If *obj
    UI_ProgressBar_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_Slider(x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
  Protected *obj.UI_Slider_Inst = AllocateStructure(UI_Slider_Inst)
  If *obj
    *obj\VTable = ?UI_Slider_VTable_Data
    UI_Slider_Init(*obj, x_p, y_p, w_p, h_p, min_p, max_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_Slider(*obj.UI_Slider_Inst)
  If *obj
    UI_Slider_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_ComboBox(x_p.i, y_p.i, w_p.i = 150, h_p.i = 25, flags_p.i = 0)
  Protected *obj.UI_ComboBox_Inst = AllocateStructure(UI_ComboBox_Inst)
  If *obj
    *obj\VTable = ?UI_ComboBox_VTable_Data
    UI_ComboBox_Init(*obj, x_p, y_p, w_p, h_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_ComboBox(*obj.UI_ComboBox_Inst)
  If *obj
    UI_ComboBox_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_UI_Controls_ToggleSwitch(x_p.i, y_p.i, w_p.i = 50, h_p.i = 26, defaultState_p.b = #False)
  Protected *obj.UI_Controls_ToggleSwitch_Inst = AllocateStructure(UI_Controls_ToggleSwitch_Inst)
  If *obj
    *obj\VTable = ?UI_Controls_ToggleSwitch_VTable_Data
    UI_Controls_ToggleSwitch_Init(*obj, x_p, y_p, w_p, h_p, defaultState_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_Controls_ToggleSwitch(*obj.UI_Controls_ToggleSwitch_Inst)
  If *obj
    UI_CustomGadget_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_GreetButton(x_p.i, y_p.i, w_p.i = 120, h_p.i = 30, text_p.s = "Button", flags_p.i = 0)
  Protected *obj.GreetButton_Inst = AllocateStructure(GreetButton_Inst)
  If *obj
    *obj\VTable = ?GreetButton_VTable_Data
    UI_Button_Init(*obj, x_p, y_p, w_p, h_p, text_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_GreetButton(*obj.GreetButton_Inst)
  If *obj
    UI_Button_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_ModeSwitch(x_p.i, y_p.i, w_p.i = 50, h_p.i = 26, defaultState_p.b = #False)
  Protected *obj.ModeSwitch_Inst = AllocateStructure(ModeSwitch_Inst)
  If *obj
    *obj\VTable = ?ModeSwitch_VTable_Data
    UI_Controls_ToggleSwitch_Init(*obj, x_p, y_p, w_p, h_p, defaultState_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_ModeSwitch(*obj.ModeSwitch_Inst)
  If *obj
    UI_CustomGadget_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_VolumeSlider(x_p.i, y_p.i, w_p.i = 200, h_p.i = 25, min_p.i = 0, max_p.i = 100, flags_p.i = 0)
  Protected *obj.VolumeSlider_Inst = AllocateStructure(VolumeSlider_Inst)
  If *obj
    *obj\VTable = ?VolumeSlider_VTable_Data
    UI_Slider_Init(*obj, x_p, y_p, w_p, h_p, min_p, max_p, flags_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_VolumeSlider(*obj.VolumeSlider_Inst)
  If *obj
    UI_Slider_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_MainWindow()
  Protected *obj.MainWindow_Inst = AllocateStructure(MainWindow_Inst)
  If *obj
    *obj\VTable = ?MainWindow_VTable_Data
    MainWindow_Init(*obj)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_MainWindow(*obj.MainWindow_Inst)
  If *obj
    UI_Window_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Demonstration du Framework GUI PureBasic OOP (Syntaxe PureBasic Standard)
; Fichier : src/demo_gui_classic.pb
; ============================================================================

; ============================================================================
; PureBasic OOP GUI Framework - UI.pbi (Master Header)
; Include this file to access the entire OOP UI subsystem
; ============================================================================

; ============================================================================
; PureBasic OOP GUI Framework - Component.pbi
; Base abstract class for all UI Windows and Gadgets
; ============================================================================



; ============================================================================
; PureBasic OOP GUI Framework - Gadget.pbi
; Base abstract class for all PureBasic UI Controls and Gadgets
; ============================================================================




; ============================================================================
; PureBasic OOP GUI Framework - Window.pbi
; Window component encapsulating PureBasic Windows
; ============================================================================




; ============================================================================
; PureBasic OOP GUI Framework - Application.pbi
; Application Manager & Central Event Dispatcher
; ============================================================================









; ============================================================================
; PureBasic OOP GUI Framework - CustomGadget.pbi
; Abstract Base Class for Canvas-Based Owner-Drawn Custom Gadgets
; ============================================================================





; Standard Controls
; ============================================================================
; PureBasic OOP GUI Framework - Button.pbi
; Standard Button and ImageButton wrapper
; ============================================================================




; ============================================================================
; PureBasic OOP GUI Framework - TextBox.pbi
; Standard Text Input / StringGadget wrapper
; ============================================================================




; ============================================================================
; PureBasic OOP GUI Framework - Label.pbi
; Standard Text / Label wrapper
; ============================================================================




; ============================================================================
; PureBasic OOP GUI Framework - CheckBox.pbi
; Standard CheckBox wrapper
; ============================================================================




; ============================================================================
; PureBasic OOP GUI Framework - ProgressBar.pbi
; Standard ProgressBar wrapper
; ============================================================================




; ============================================================================
; PureBasic OOP GUI Framework - Slider.pbi
; Standard TrackBar / Slider wrapper
; ============================================================================




; ============================================================================
; PureBasic OOP GUI Framework - ComboBox.pbi
; Standard ComboBox / Dropdown wrapper
; ============================================================================





; Custom Controls
; ============================================================================
; PureBasic OOP GUI Framework - ToggleSwitch.pbi
; Custom iOS-Style Toggle Switch Widget extending UI_CustomGadget
; ============================================================================






; ----------------------------------------------------------------------------
; 1. Classes Specialisees par Heritage (Mots-cles classiques PureBasic)
; ----------------------------------------------------------------------------

; Bouton avec logique et liaison de donnees

; Custom Toggle Switch sur Canvas avec callback OnChange

; Slider synchronise avec ProgressBar

; ----------------------------------------------------------------------------
; 2. Fenetre Principale Encapsulee (Syntaxe Standard)
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. Point d'Entree du Programme
; ----------------------------------------------------------------------------

Define *app.UI_Application_vt = New_UI_Application()
Define *mainWin.MainWindow_vt = New_MainWindow()

*app\Run(*mainWin)
