; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------

Structure Document_Inst
  *VTable.Document_vt
  titre.s
EndStructure

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------

Declare Document_Init(*This.Document_Inst, titre_p.s)
Declare Document_Afficher(*This.Document_Inst)
Declare Document_Free(*This.Document_Inst)
Declare.i New_Document(titre_p.s)
Declare Free_Document(*obj.Document_Inst)

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------



; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Document_vt
  Afficher()
  FreeStructure()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------



Procedure Document_Init(*This.Document_Inst, titre_p.s)
  Protected *This_vt.Document_vt = *This
      *This\titre = titre_p
EndProcedure

Procedure Document_Afficher(*This.Document_Inst)
  Protected *This_vt.Document_vt = *This
      PrintN("Document: " + *This\titre)
EndProcedure

Procedure Document_Free(*This.Document_Inst)
  Protected *This_vt.Document_vt = *This
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Document_VTable_Data:
    Data.i @Document_Afficher()
    Data.i @Document_Free()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Document(titre_p.s)
  Protected *obj.Document_Inst = AllocateStructure(Document_Inst)
  If *obj
    *obj\VTable = ?Document_VTable_Data
    Document_Init(*obj, titre_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Document(*obj.Document_Inst)
  If *obj
    Document_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Test: Static Memory Leak Detection System (Transpiler Warning)
; ============================================================================


Procedure TraiterRapport()
  ; CAS 1 : ALERTE ! Cette instance n'est jamais libérée avant la fin de la procédure
  Protected *docTemporaire.Document_vt = New_Document("Rapport Annuel")
  *docTemporaire\Afficher()
  ; -> Missing Free(*docTemporaire) or *docTemporaire\Free()
EndProcedure

Procedure.i CreerDocumentModele()
  ; CAS 2 : SAIN. L'objet est retourné (transfert de propriété à l'appelant)
  Protected *modele.Document_vt = New_Document("Modele V1")
  ProcedureReturn *modele
EndProcedure

; ============================================================================
; MAIN PROGRAM
; ============================================================================

; CAS 3 : SAIN dans Main (Alloué puis libéré)
Define *monDoc.Document_vt = New_Document("Doc Main")
*monDoc\Afficher()
*monDoc\Free()

; CAS 4 : ALERTE dans Main ! (Alloué mais jamais libéré)
Define *docOublie.Document_vt = New_Document("Oubli Final")
; -> Missing *docOublie\Free()
