; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Human_vt
  SayHello()
  Free()
EndInterface

Interface Developer_vt Extends Human_vt
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Human_Inst
  *VTable.Human_vt
  Name.s
  Age.i
EndStructure

Structure Developer_Inst Extends Human_Inst
  FavoriteLanguage.s
EndStructure

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Procedure Human_Init(*This.Human_Inst, Name.s, Age.i)
      *This\Name = Name
      *This\Age  = Age
EndProcedure

Procedure Human_SayHello(*This.Human_Inst)
      MessageRequester("Human", "Hello, my name is " + *This\Name + " and I am " + Str(*This\Age) + " years old.")
EndProcedure

Procedure Human_Free(*This.Human_Inst)
      ; Clean up resources
EndProcedure

Procedure Developer_Init(*This.Developer_Inst, Name.s, Age.i, FavoriteLanguage.s)
      Human_Init(*This, Name, Age)
      *This\FavoriteLanguage = FavoriteLanguage
EndProcedure

Procedure Developer_SayHello(*This.Developer_Inst)
      MessageRequester("Developer", "Hello world! I am " + *This\Name + ", coding with " + *This\FavoriteLanguage + "!")
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Human_VTable_Data:
    Data.i @Human_SayHello()
    Data.i @Human_Free()
  Developer_VTable_Data:
    Data.i @Developer_SayHello()
    Data.i @Human_Free()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Human(Name.s, Age.i)
  Protected *obj.Human_Inst = AllocateStructure(Human_Inst)
  If *obj
    *obj\VTable = ?Human_VTable_Data
    Human_Init(*obj, Name, Age)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure.i New_Developer(Name.s, Age.i, FavoriteLanguage.s)
  Protected *obj.Developer_Inst = AllocateStructure(Developer_Inst)
  If *obj
    *obj\VTable = ?Developer_VTable_Data
    Developer_Init(*obj, Name, Age, FavoriteLanguage)
  EndIf
  ProcedureReturn *obj
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ==============================================================================
; Application : PureBasic OOP - Exemple de Test Complet
; Author      : MicrodevWeb
; ==============================================================================

; --- 1. Définition de la Classe de Base : Human ---

; --- 2. Définition de la Classe Dérivée : Developer (Héritage) ---

; --- 3. Point d'Entrée Principal ---
Procedure Main()
  Protected *dev.Developer_vt = New_Developer( "DevMicro", 30, "PureBasic OOP")
  
  If *dev
    *dev\SayHello()
    *dev\Free()
  EndIf
EndProcedure

Main()
