; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------

#UI_Align_Left = 0
#UI_Align_Center = 1
#UI_Align_Right = 2
#UI_Align_Stretch = 3
#UI_Align_Top = 0
#UI_Align_Middle = 1
#UI_Align_Bottom = 2
#UI_Align_VStretch = 3
#UI_Orientation_Vertical = 0
#UI_Orientation_Horizontal = 1
#UI_Dock_Left = 0
#UI_Dock_Top = 1
#UI_Dock_Right = 2
#UI_Dock_Bottom = 3
#UI_Dock_Fill = 4
#UI_GridUnit_Pixel = 0
#UI_GridUnit_Auto  = 1
#UI_GridUnit_Star  = 2
Structure UI_DockItem
  *child
  dock.i
EndStructure
Structure UI_GridDef
  unitType.i
  val.f
  computedSize.i
  computedPos.i
EndStructure
Structure UI_GridItem
  *child
  row.i
  col.i
  rowSpan.i
  colSpan.i
EndStructure

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface UI_Component_vt
  GetID.i()
  GetHandle.i()
  GetTag.s()
  SetTag(t.s)
  GetX.i()
  SetX(nx.i)
  GetY.i()
  SetY(ny.i)
  GetWidth.i()
  SetWidth(nw.i)
  GetHeight.i()
  SetHeight(nh.i)
  SetLocation(nx.i, ny.i)
  SetSize(nw.i, nh.i)
  SetPosition(nx.i, ny.i, nw.i, nh.i)
  IsVisible.b()
  GetVisible.b()
  SetVisible(v.b)
  IsEnabled.b()
  GetEnabled.b()
  SetEnabled(e.b)
  GetUserData.i()
  SetUserData(val.i)
  SetMargin(l.i, t.i, r.i, b.i)
  SetMarginAll(m.i)
  GetMarginLeft.i()
  GetMarginTop.i()
  GetMarginRight.i()
  GetMarginBottom.i()
  SetHorizontalAlignment(align.i)
  GetHorizontalAlignment.i()
  SetVerticalAlignment(align.i)
  GetVerticalAlignment.i()
  SetMinWidth(mw.i)
  GetMinWidth.i()
  SetMaxWidth(mw.i)
  GetMaxWidth.i()
  SetMinHeight(mh.i)
  GetMinHeight.i()
  SetMaxHeight(mh.i)
  GetMaxHeight.i()
  GetDesiredWidth.i()
  GetDesiredHeight.i()
  Arrange(nx.i, ny.i, nw.i, nh.i)
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure UI_Component_Inst
  *VTable.UI_Component_vt
  id.i
  tag.s
  x.i
  y.i
  width.i
  height.i
  isVisible.b
  isEnabled.b
  userData.i
  marginLeft.i
  marginTop.i
  marginRight.i
  marginBottom.i
  horizontalAlignment.i
  verticalAlignment.i
  minWidth.i
  maxWidth.i
  minHeight.i
  maxHeight.i
  desiredWidth.i
  desiredHeight.i
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare UI_Component_Init(*This.UI_Component_Inst)
Declare.i UI_Component_GetID(*This.UI_Component_Inst)
Declare.i UI_Component_GetHandle(*This.UI_Component_Inst)
Declare.s UI_Component_GetTag(*This.UI_Component_Inst)
Declare UI_Component_SetTag(*This.UI_Component_Inst, t.s)
Declare.i UI_Component_GetX(*This.UI_Component_Inst)
Declare UI_Component_SetX(*This.UI_Component_Inst, nx.i)
Declare.i UI_Component_GetY(*This.UI_Component_Inst)
Declare UI_Component_SetY(*This.UI_Component_Inst, ny.i)
Declare.i UI_Component_GetWidth(*This.UI_Component_Inst)
Declare UI_Component_SetWidth(*This.UI_Component_Inst, nw.i)
Declare.i UI_Component_GetHeight(*This.UI_Component_Inst)
Declare UI_Component_SetHeight(*This.UI_Component_Inst, nh.i)
Declare UI_Component_SetLocation(*This.UI_Component_Inst, nx.i, ny.i)
Declare UI_Component_SetSize(*This.UI_Component_Inst, nw.i, nh.i)
Declare UI_Component_SetPosition(*This.UI_Component_Inst, nx.i, ny.i, nw.i, nh.i)
Declare.b UI_Component_IsVisible(*This.UI_Component_Inst)
Declare.b UI_Component_GetVisible(*This.UI_Component_Inst)
Declare UI_Component_SetVisible(*This.UI_Component_Inst, v.b)
Declare.b UI_Component_IsEnabled(*This.UI_Component_Inst)
Declare.b UI_Component_GetEnabled(*This.UI_Component_Inst)
Declare UI_Component_SetEnabled(*This.UI_Component_Inst, e.b)
Declare.i UI_Component_GetUserData(*This.UI_Component_Inst)
Declare UI_Component_SetUserData(*This.UI_Component_Inst, val.i)
Declare UI_Component_SetMargin(*This.UI_Component_Inst, l.i, t.i, r.i, b.i)
Declare UI_Component_SetMarginAll(*This.UI_Component_Inst, m.i)
Declare.i UI_Component_GetMarginLeft(*This.UI_Component_Inst)
Declare.i UI_Component_GetMarginTop(*This.UI_Component_Inst)
Declare.i UI_Component_GetMarginRight(*This.UI_Component_Inst)
Declare.i UI_Component_GetMarginBottom(*This.UI_Component_Inst)
Declare UI_Component_SetHorizontalAlignment(*This.UI_Component_Inst, align.i)
Declare.i UI_Component_GetHorizontalAlignment(*This.UI_Component_Inst)
Declare UI_Component_SetVerticalAlignment(*This.UI_Component_Inst, align.i)
Declare.i UI_Component_GetVerticalAlignment(*This.UI_Component_Inst)
Declare UI_Component_SetMinWidth(*This.UI_Component_Inst, mw.i)
Declare.i UI_Component_GetMinWidth(*This.UI_Component_Inst)
Declare UI_Component_SetMaxWidth(*This.UI_Component_Inst, mw.i)
Declare.i UI_Component_GetMaxWidth(*This.UI_Component_Inst)
Declare UI_Component_SetMinHeight(*This.UI_Component_Inst, mh.i)
Declare.i UI_Component_GetMinHeight(*This.UI_Component_Inst)
Declare UI_Component_SetMaxHeight(*This.UI_Component_Inst, mh.i)
Declare.i UI_Component_GetMaxHeight(*This.UI_Component_Inst)
Declare.i UI_Component_GetDesiredWidth(*This.UI_Component_Inst)
Declare.i UI_Component_GetDesiredHeight(*This.UI_Component_Inst)
Declare UI_Component_Arrange(*This.UI_Component_Inst, nx.i, ny.i, nw.i, nh.i)


Procedure UI_Component_Init(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        *This\isVisible = #True
        *This\isEnabled = #True
        *This\horizontalAlignment = #UI_Align_Stretch
        *This\verticalAlignment = #UI_Align_VStretch
        *This\desiredWidth = 100
        *This\desiredHeight = 30
EndProcedure

Procedure.i UI_Component_GetID(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\id
EndProcedure

Procedure.i UI_Component_GetHandle(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\id
EndProcedure

Procedure.s UI_Component_GetTag(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\tag
EndProcedure

Procedure UI_Component_SetTag(*This.UI_Component_Inst, t.s)
  Protected *This_vt.UI_Component_vt = *This
        *This\tag = t
EndProcedure

Procedure.i UI_Component_GetX(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\x
EndProcedure

Procedure UI_Component_SetX(*This.UI_Component_Inst, nx.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\x = nx
EndProcedure

Procedure.i UI_Component_GetY(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\y
EndProcedure

Procedure UI_Component_SetY(*This.UI_Component_Inst, ny.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\y = ny
EndProcedure

Procedure.i UI_Component_GetWidth(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\width
EndProcedure

Procedure UI_Component_SetWidth(*This.UI_Component_Inst, nw.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\width = nw
        *This\desiredWidth = nw
EndProcedure

Procedure.i UI_Component_GetHeight(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\height
EndProcedure

Procedure UI_Component_SetHeight(*This.UI_Component_Inst, nh.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\height = nh
        *This\desiredHeight = nh
EndProcedure

Procedure UI_Component_SetLocation(*This.UI_Component_Inst, nx.i, ny.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\x = nx
        *This\y = ny
EndProcedure

Procedure UI_Component_SetSize(*This.UI_Component_Inst, nw.i, nh.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\width = nw
        *This\height = nh
        *This\desiredWidth = nw
        *This\desiredHeight = nh
EndProcedure

Procedure UI_Component_SetPosition(*This.UI_Component_Inst, nx.i, ny.i, nw.i, nh.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\x = nx
        *This\y = ny
        *This\width = nw
        *This\height = nh
        *This\desiredWidth = nw
        *This\desiredHeight = nh
EndProcedure

Procedure.b UI_Component_IsVisible(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\isVisible
EndProcedure

Procedure.b UI_Component_GetVisible(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\isVisible
EndProcedure

Procedure UI_Component_SetVisible(*This.UI_Component_Inst, v.b)
  Protected *This_vt.UI_Component_vt = *This
        *This\isVisible = v
EndProcedure

Procedure.b UI_Component_IsEnabled(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\isEnabled
EndProcedure

Procedure.b UI_Component_GetEnabled(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\isEnabled
EndProcedure

Procedure UI_Component_SetEnabled(*This.UI_Component_Inst, e.b)
  Protected *This_vt.UI_Component_vt = *This
        *This\isEnabled = e
EndProcedure

Procedure.i UI_Component_GetUserData(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\userData
EndProcedure

Procedure UI_Component_SetUserData(*This.UI_Component_Inst, val.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\userData = val
EndProcedure

Procedure UI_Component_SetMargin(*This.UI_Component_Inst, l.i, t.i, r.i, b.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\marginLeft = l
        *This\marginTop = t
        *This\marginRight = r
        *This\marginBottom = b
EndProcedure

Procedure UI_Component_SetMarginAll(*This.UI_Component_Inst, m.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\marginLeft = m
        *This\marginTop = m
        *This\marginRight = m
        *This\marginBottom = m
EndProcedure

Procedure.i UI_Component_GetMarginLeft(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\marginLeft
EndProcedure

Procedure.i UI_Component_GetMarginTop(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\marginTop
EndProcedure

Procedure.i UI_Component_GetMarginRight(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\marginRight
EndProcedure

Procedure.i UI_Component_GetMarginBottom(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\marginBottom
EndProcedure

Procedure UI_Component_SetHorizontalAlignment(*This.UI_Component_Inst, align.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\horizontalAlignment = align
EndProcedure

Procedure.i UI_Component_GetHorizontalAlignment(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\horizontalAlignment
EndProcedure

Procedure UI_Component_SetVerticalAlignment(*This.UI_Component_Inst, align.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\verticalAlignment = align
EndProcedure

Procedure.i UI_Component_GetVerticalAlignment(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\verticalAlignment
EndProcedure

Procedure UI_Component_SetMinWidth(*This.UI_Component_Inst, mw.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\minWidth = mw
EndProcedure

Procedure.i UI_Component_GetMinWidth(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\minWidth
EndProcedure

Procedure UI_Component_SetMaxWidth(*This.UI_Component_Inst, mw.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\maxWidth = mw
EndProcedure

Procedure.i UI_Component_GetMaxWidth(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\maxWidth
EndProcedure

Procedure UI_Component_SetMinHeight(*This.UI_Component_Inst, mh.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\minHeight = mh
EndProcedure

Procedure.i UI_Component_GetMinHeight(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\minHeight
EndProcedure

Procedure UI_Component_SetMaxHeight(*This.UI_Component_Inst, mh.i)
  Protected *This_vt.UI_Component_vt = *This
        *This\maxHeight = mh
EndProcedure

Procedure.i UI_Component_GetMaxHeight(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
        ProcedureReturn *This\maxHeight
EndProcedure

Procedure.i UI_Component_GetDesiredWidth(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
  If (*This\desiredWidth > 0)
          ProcedureReturn *This\desiredWidth
  EndIf
  If (*This\width > 0)
          ProcedureReturn *This\width
  EndIf
        ProcedureReturn 100
EndProcedure

Procedure.i UI_Component_GetDesiredHeight(*This.UI_Component_Inst)
  Protected *This_vt.UI_Component_vt = *This
  If (*This\desiredHeight > 0)
          ProcedureReturn *This\desiredHeight
  EndIf
  If (*This\height > 0)
          ProcedureReturn *This\height
  EndIf
        ProcedureReturn 30
EndProcedure

Procedure UI_Component_Arrange(*This.UI_Component_Inst, nx.i, ny.i, nw.i, nh.i)
  Protected *This_vt.UI_Component_vt = *This
        *This_vt\SetPosition(nx, ny, nw, nh)
  If (*This\id And IsGadget(*This\id))
          ResizeGadget(*This\id, nx, ny, nw, nh)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; PureBasic OOP GUI Framework - Component.pbi
; Base abstract class for all PureBasic UI elements & Layouts
; Author:      MicrodevWeb
; ============================================================================











