; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface FormeGeometrique_vt
  CalculerAire.d()
  CalculerPerimetre.d()
  Dessiner()
  AfficherInfos()
  Free()
EndInterface

Interface Rectangle_vt Extends FormeGeometrique_vt
EndInterface

Interface Cercle_vt Extends FormeGeometrique_vt
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure FormeGeometrique_Inst
  *VTable.FormeGeometrique_vt
  nom.s
  couleur.s
EndStructure

Structure Rectangle_Inst Extends FormeGeometrique_Inst
  largeur.d
  hauteur.d
EndStructure

Structure Cercle_Inst Extends FormeGeometrique_Inst
  rayon.d
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------

NewList *formes.FormeGeometrique_vt()

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare FormeGeometrique_Init(*This.FormeGeometrique_Inst, nom_p.s, couleur_p.s)
Declare FormeGeometrique_AfficherInfos(*This.FormeGeometrique_Inst)
Declare FormeGeometrique_Free(*This.FormeGeometrique_Inst)
Declare Rectangle_Init(*This.Rectangle_Inst, nom_p.s, couleur_p.s, l.d, h.d)
Declare.d Rectangle_CalculerAire(*This.Rectangle_Inst)
Declare.d Rectangle_CalculerPerimetre(*This.Rectangle_Inst)
Declare Rectangle_Dessiner(*This.Rectangle_Inst)
Declare Rectangle_AfficherInfos(*This.Rectangle_Inst)
Declare Rectangle_Free(*This.Rectangle_Inst)
Declare Cercle_Init(*This.Cercle_Inst, nom_p.s, couleur_p.s, r.d)
Declare.d Cercle_CalculerAire(*This.Cercle_Inst)
Declare.d Cercle_CalculerPerimetre(*This.Cercle_Inst)
Declare Cercle_Dessiner(*This.Cercle_Inst)
Declare Cercle_AfficherInfos(*This.Cercle_Inst)
Declare Cercle_Free(*This.Cercle_Inst)

Declare.i New_Rectangle(nom_p.s, couleur_p.s, l.d, h.d)
Declare Free_Rectangle(*obj.Rectangle_Inst)
Declare.i New_Cercle(nom_p.s, couleur_p.s, r.d)
Declare Free_Cercle(*obj.Cercle_Inst)

Procedure FormeGeometrique_Init(*This.FormeGeometrique_Inst, nom_p.s, couleur_p.s)
  Protected *This_vt.FormeGeometrique_vt = *This
    *This\nom = nom_p
    *This\couleur = couleur_p
EndProcedure

Procedure FormeGeometrique_AfficherInfos(*This.FormeGeometrique_Inst)
  Protected *This_vt.FormeGeometrique_vt = *This
    PrintN("[Forme: " + *This\nom + " | Couleur: " + *This\couleur + "]")
EndProcedure

Procedure FormeGeometrique_Free(*This.FormeGeometrique_Inst)
  Protected *This_vt.FormeGeometrique_vt = *This
    PrintN("[FormeGeometrique_Free] Liberation de la forme : " + *This\nom)
    FreeStructure(*This)
EndProcedure

Procedure Rectangle_Init(*This.Rectangle_Inst, nom_p.s, couleur_p.s, l.d, h.d)
  Protected *This_vt.Rectangle_vt = *This
    FormeGeometrique_Init(*This, nom_p, couleur_p)
    *This\largeur = l
    *This\hauteur = h
EndProcedure

Procedure.d Rectangle_CalculerAire(*This.Rectangle_Inst)
  Protected *This_vt.Rectangle_vt = *This
    ProcedureReturn *This\largeur * *This\hauteur
EndProcedure

Procedure.d Rectangle_CalculerPerimetre(*This.Rectangle_Inst)
  Protected *This_vt.Rectangle_vt = *This
    ProcedureReturn 2 * (*This\largeur + *This\hauteur)
EndProcedure

Procedure Rectangle_Dessiner(*This.Rectangle_Inst)
  Protected *This_vt.Rectangle_vt = *This
    PrintN("   ==> [DESSIN] Rectangle (" + StrD(*This\largeur, 2) + " x " + StrD(*This\hauteur, 2) + ") en " + *This\couleur)
EndProcedure

Procedure Rectangle_AfficherInfos(*This.Rectangle_Inst)
  Protected *This_vt.Rectangle_vt = *This
    FormeGeometrique_AfficherInfos(*This)
    PrintN("       Details : Largeur=" + StrD(*This\largeur, 2) + ", Hauteur=" + StrD(*This\hauteur, 2) + " -> Aire=" + StrD(*This_vt\CalculerAire(), 2))
EndProcedure

Procedure Rectangle_Free(*This.Rectangle_Inst)
  Protected *This_vt.Rectangle_vt = *This
    PrintN("[Rectangle_Free] Destruction specifique rectangle " + *This\nom)
    FormeGeometrique_Free(*This)
EndProcedure

Procedure Cercle_Init(*This.Cercle_Inst, nom_p.s, couleur_p.s, r.d)
  Protected *This_vt.Cercle_vt = *This
    FormeGeometrique_Init(*This, nom_p, couleur_p)
    *This\rayon = r
EndProcedure

Procedure.d Cercle_CalculerAire(*This.Cercle_Inst)
  Protected *This_vt.Cercle_vt = *This
    ProcedureReturn 3.1415926535 * *This\rayon * *This\rayon
EndProcedure

Procedure.d Cercle_CalculerPerimetre(*This.Cercle_Inst)
  Protected *This_vt.Cercle_vt = *This
    ProcedureReturn 2 * 3.1415926535 * *This\rayon
EndProcedure

Procedure Cercle_Dessiner(*This.Cercle_Inst)
  Protected *This_vt.Cercle_vt = *This
    PrintN("   ==> [DESSIN] Cercle de rayon " + StrD(*This\rayon, 2) + " en " + *This\couleur)
EndProcedure

Procedure Cercle_AfficherInfos(*This.Cercle_Inst)
  Protected *This_vt.Cercle_vt = *This
    PrintN("[CERCLE SPECIAL " + *This\couleur + "] Rayon=" + StrD(*This\rayon, 2) + " | Aire=" + StrD(*This_vt\CalculerAire(), 2) + " | Perimetre=" + StrD(*This_vt\CalculerPerimetre(), 2))
EndProcedure

Procedure Cercle_Free(*This.Cercle_Inst)
  Protected *This_vt.Cercle_vt = *This
    PrintN("[Cercle_Free] Destruction specifique cercle " + *This\nom)
    FormeGeometrique_Free(*This)
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Rectangle_VTable_Data:
    Data.i @Rectangle_CalculerAire()
    Data.i @Rectangle_CalculerPerimetre()
    Data.i @Rectangle_Dessiner()
    Data.i @Rectangle_AfficherInfos()
    Data.i @Rectangle_Free()
  Cercle_VTable_Data:
    Data.i @Cercle_CalculerAire()
    Data.i @Cercle_CalculerPerimetre()
    Data.i @Cercle_Dessiner()
    Data.i @Cercle_AfficherInfos()
    Data.i @Cercle_Free()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Rectangle(nom_p.s, couleur_p.s, l.d, h.d)
  Protected *obj.Rectangle_Inst = AllocateStructure(Rectangle_Inst)
  If *obj
    *obj\VTable = ?Rectangle_VTable_Data
    Rectangle_Init(*obj, nom_p, couleur_p, l, h)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Rectangle(*obj.Rectangle_Inst)
  If *obj
    Rectangle_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Cercle(nom_p.s, couleur_p.s, r.d)
  Protected *obj.Cercle_Inst = AllocateStructure(Cercle_Inst)
  If *obj
    *obj\VTable = ?Cercle_VTable_Data
    Cercle_Init(*obj, nom_p, couleur_p, r)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Cercle(*obj.Cercle_Inst)
  If *obj
    Cercle_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Test PureBasic OOP : Classes Abstraites, Methodes Abstraites & Polymorphisme
; Fichier source : test_abstract_classes.pb
; ============================================================================

; ----------------------------------------------------------------------------
; 1. CLASSE ABSTRAITE : FormeGeometrique
; ----------------------------------------------------------------------------


; Implementation de la methode par defaut dans la classe abstraite


; ----------------------------------------------------------------------------
; 2. CLASSE DERIVEE CONCRETE : Rectangle (Herite de FormeGeometrique)
; ----------------------------------------------------------------------------





; Surcharge Partielle : appel du parent Super_AfficherInfos() puis ajout de details


; ----------------------------------------------------------------------------
; 3. CLASSE DERIVEE CONCRETE : Cercle (Herite de FormeGeometrique)
; ----------------------------------------------------------------------------





; Surcharge Totale : remplace completement l'affichage


; ============================================================================
; 4. PROGRAMME PRINCIPAL DE TEST & DEMONSTRATION DU POLYMORPHISME ABSTRAIT
; ============================================================================

OpenConsole()
CompilerIf #PB_Compiler_OS = #PB_OS_Windows
  SetConsoleOutputCP_(65001)
CompilerEndIf

PrintN("=================================================================")
PrintN("  TEST PUREBASIC OOP : CLASSES & METHODES ABSTRAITES            ")
PrintN("=================================================================")
PrintN("")

; A. Instanciations concretes
Define *rect.Rectangle_vt = New_Rectangle("MonRectangle", "Bleu", 10.0, 5.0)
Define *cercle.Cercle_vt = New_Cercle("MonCercle", "Rouge", 4.0)

PrintN("--- 1. Appels directs sur instances concretes ---")
*rect\AfficherInfos()
*rect\Dessiner()
PrintN("")
*cercle\AfficherInfos()
*cercle\Dessiner()
PrintN("")

; B. Polymorphisme via la classe abstraite FormeGeometrique
PrintN("--- 2. Polymorphisme dynamique via List FormeGeometrique ---")

AddElement(*formes()) : *formes() = *rect
AddElement(*formes()) : *formes() = *cercle
AddElement(*formes()) : *formes() = New_Rectangle("GrandRectangle", "Vert", 20.0, 15.0)
AddElement(*formes()) : *formes() = New_Cercle("PetitCercle", "Jaune", 1.5)

ForEach *formes()
  PrintN("-> Forme [Index " + Str(ListIndex(*formes())) + "] :")
  *formes()\AfficherInfos()
  *formes()\Dessiner()
  PrintN("   Aire calculee      : " + StrD(*formes()\CalculerAire(), 2))
  PrintN("   Perimetre calcule  : " + StrD(*formes()\CalculerPerimetre(), 2))
  PrintN("")
Next

; C. Nettoyage memoire
PrintN("--- 3. Nettoyage memoire polymorphe ---")
ForEach *formes()
  *formes()\Free()
Next
ClearList(*formes())

PrintN("")
PrintN("=================================================================")
PrintN("  TEST CLASSES ABSTRAITES TERMINE AVEC SUCCES                   ")
PrintN("=================================================================")
PrintN("")
PrintN("Appuyez sur Entree pour quitter...")
Input()
CloseConsole()
