; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------

Structure UI_Setter
  property.s
  value.s
EndStructure
Structure UI_Trigger
  property.s
  value.s
  List setters.UI_Setter()
EndStructure

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface UI_Style_vt
  AddSetter(prop.s, val.s)
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure UI_Style_Inst
  *VTable.UI_Style_vt
  targetType.s
  key.s
  basedOn.s
  List setters.UI_Setter()
  List triggers.UI_Trigger()
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare UI_Style_Init(*This.UI_Style_Inst)
Declare UI_Style_AddSetter(*This.UI_Style_Inst, prop.s, val.s)

Declare.i New_UI_Style()
Declare Free_UI_Style(*obj.UI_Style_Inst)

Procedure UI_Style_Init(*This.UI_Style_Inst)
  Protected *This_vt.UI_Style_vt = *This
        *This\targetType = ""
        *This\key = ""
        *This\basedOn = ""
EndProcedure

Procedure UI_Style_AddSetter(*This.UI_Style_Inst, prop.s, val.s)
  Protected *This_vt.UI_Style_vt = *This
        AddElement(*This\setters())
        *This\setters()\property = prop
        *This\setters()\value = val
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  UI_Style_VTable_Data:
    Data.i @UI_Style_AddSetter()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_UI_Style()
  Protected *obj.UI_Style_Inst = AllocateStructure(UI_Style_Inst)
  If *obj
    *obj\VTable = ?UI_Style_VTable_Data
    UI_Style_Init(*obj)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_UI_Style(*obj.UI_Style_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------



