; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

#OOP_PROJECT_DIR = "c:\PB\PB_PROJECT\PB_OOP_WORKSPACE\PUREBASIC_OOP_WORKSPACE\"
#OOP_WORKSPACE_DIR = "C:\PB\PB_PROJECT\PB_OOP_WORKSPACE\PUREBASIC_OOP_WORKSPACE\"

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Document_vt
  Afficher()
  Free()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Document_Inst
  *VTable.Document_vt
  titre.s
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare Document_Init(*This.Document_Inst, titre_p.s)
Declare Document_Afficher(*This.Document_Inst)
Declare Document_Free(*This.Document_Inst)

Declare.i New_Document(titre_p.s)
Declare Free_Document(*obj.Document_Inst)

Procedure Document_Init(*This.Document_Inst, titre_p.s)
  Protected *This_vt.Document_vt = *This
      *This\titre = titre_p
EndProcedure

Procedure Document_Afficher(*This.Document_Inst)
  Protected *This_vt.Document_vt = *This
      PrintN("Document: " + *This\titre)
EndProcedure

Procedure Document_Free(*This.Document_Inst)
  Protected *This_vt.Document_vt = *This
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Document_VTable_Data:
    Data.i @Document_Afficher()
    Data.i @Document_Free()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Document(titre_p.s)
  Protected *obj.Document_Inst = AllocateStructure(Document_Inst)
  If *obj
    *obj\VTable = ?Document_VTable_Data
    Document_Init(*obj, titre_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Document(*obj.Document_Inst)
  If *obj
    Document_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Test: Static Memory Leak Detection System (Transpiler Warning)
; ============================================================================

OpenConsole("PureBasic OOP - Test Leak Detection")


Procedure TraiterRapport()
  ; CAS 1 : ALERTE ! Cette instance n'est jamais liberee avant la fin de la procedure
  Protected *docTemporaire.Document_vt = New_Document("Rapport Annuel")
  *docTemporaire\Afficher()
  ; -> Manque Free(*docTemporaire) ou *docTemporaire\Free()
  *docTemporaire\Free()
EndProcedure

Procedure.i CreerDocumentModele()
  ; CAS 2 : SAIN. L'objet est retourne (transfert de propriete a l'appelant)
  Protected *modele.Document_vt = New_Document("Modele V1")
  ProcedureReturn *modele
EndProcedure

; ============================================================================
; MAIN PROGRAM
; ============================================================================

PrintN("--- Execution des tests ---")

; Execution de la procedure avec fuite
TraiterRapport()

; CAS 3 : SAIN dans Main (Alloue puis libere)
Define *monDoc.Document_vt = New_Document("Doc Main")
*monDoc\Afficher()
*monDoc\Free()

; CAS 4 : ALERTE dans Main ! (Alloue mais jamais libere)
Define *docOublie.Document_vt = New_Document("Oubli Final")
; -> Manque *docOublie\Free()
*docOublie\Free()
PrintN("")
PrintN("Tests termines ! Appuyez sur Entree pour quitter...")
Input()
CloseConsole()

; IDE Options = PureBasic 6.40 (Windows - x64)
; CursorPosition = 23
; FirstLine = 13
; Folding = -
; EnableXP
; DPIAware
