; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Robot_vt
  Beep()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Robot_Inst
  *VTable.Robot_vt
  name.s
EndStructure

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare Robot_Beep(*This.Robot_Inst)

Procedure Robot_Beep(*This.Robot_Inst)
  Protected *This_vt.Robot_vt = *This
      PrintN("Beep")
      PrintN(UnknownCompilerCall12345()) ; ERROR at line 6 in PBO
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Robot_VTable_Data:
    Data.i @Robot_Beep()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Robot()
  Protected *obj.Robot_Inst = AllocateStructure(Robot_Inst)
  If *obj
    *obj\VTable = ?Robot_VTable_Data
  EndIf
  ProcedureReturn *obj
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------


OpenConsole()
Define *r.Robot_vt = New_Robot()
*r\Beep()
CloseConsole()
