; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Calculatrice_vt
  Additionner_i_i.i(a.i, b.i)
  Additionner_s_s.s(a.s, b.s)
  Additionner_d_d.d(a.d, b.d)
EndInterface

Interface Formateur_vt
  Formater_i.s(val.i)
  Formater_i_s.s(val.i, prefixe.s)
  Formater_i_s_s.s(val.i, prefixe.s, suffixe.s)
EndInterface

Interface Point2D_vt
  ToString.s()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Calculatrice_Inst
  *VTable.Calculatrice_vt
EndStructure

Structure Formateur_Inst
  *VTable.Formateur_vt
EndStructure

Structure Point2D_Inst
  *VTable.Point2D_vt
  x.i
  y.i
  tag.s
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare.i Calculatrice_Additionner_i_i(*This.Calculatrice_Inst, a.i, b.i)
Declare.s Calculatrice_Additionner_s_s(*This.Calculatrice_Inst, a.s, b.s)
Declare.d Calculatrice_Additionner_d_d(*This.Calculatrice_Inst, a.d, b.d)
Declare.s Formateur_Formater_i(*This.Formateur_Inst, val.i)
Declare.s Formateur_Formater_i_s(*This.Formateur_Inst, val.i, prefixe.s)
Declare.s Formateur_Formater_i_s_s(*This.Formateur_Inst, val.i, prefixe.s, suffixe.s)
Declare Point2D_Init_void(*This.Point2D_Inst)
Declare Point2D_Init_i_i(*This.Point2D_Inst, px.i, py.i)
Declare Point2D_Init_i_i_s(*This.Point2D_Inst, px.i, py.i, ptag.s)
Declare.s Point2D_ToString(*This.Point2D_Inst)

Declare.i New_Calculatrice()
Declare Free_Calculatrice(*obj.Calculatrice_Inst)
Declare.i New_Formateur()
Declare Free_Formateur(*obj.Formateur_Inst)
Declare.i New_Point2D_void()
Declare.i New_Point2D_i_i(px.i, py.i)
Declare.i New_Point2D_i_i_s(px.i, py.i, ptag.s)
Declare Free_Point2D(*obj.Point2D_Inst)

Procedure.i Calculatrice_Additionner_i_i(*This.Calculatrice_Inst, a.i, b.i)
  Protected *This_vt.Calculatrice_vt = *This
      ProcedureReturn a + b
EndProcedure

Procedure.s Calculatrice_Additionner_s_s(*This.Calculatrice_Inst, a.s, b.s)
  Protected *This_vt.Calculatrice_vt = *This
      ProcedureReturn a + " " + b
EndProcedure

Procedure.d Calculatrice_Additionner_d_d(*This.Calculatrice_Inst, a.d, b.d)
  Protected *This_vt.Calculatrice_vt = *This
      ProcedureReturn a + b
EndProcedure

Procedure.s Formateur_Formater_i(*This.Formateur_Inst, val.i)
  Protected *This_vt.Formateur_vt = *This
      ProcedureReturn "Nombre: " + Str(val)
EndProcedure

Procedure.s Formateur_Formater_i_s(*This.Formateur_Inst, val.i, prefixe.s)
  Protected *This_vt.Formateur_vt = *This
      ProcedureReturn prefixe + ": " + Str(val)
EndProcedure

Procedure.s Formateur_Formater_i_s_s(*This.Formateur_Inst, val.i, prefixe.s, suffixe.s)
  Protected *This_vt.Formateur_vt = *This
      ProcedureReturn prefixe + ": " + Str(val) + " (" + suffixe + ")"
EndProcedure

Procedure Point2D_Init_void(*This.Point2D_Inst)
  Protected *This_vt.Point2D_vt = *This
      *This\x = 0
      *This\y = 0
      *This\tag = "Origine"
EndProcedure

Procedure Point2D_Init_i_i(*This.Point2D_Inst, px.i, py.i)
  Protected *This_vt.Point2D_vt = *This
      *This\x = px
      *This\y = py
      *This\tag = "Point"
EndProcedure

Procedure Point2D_Init_i_i_s(*This.Point2D_Inst, px.i, py.i, ptag.s)
  Protected *This_vt.Point2D_vt = *This
      *This\x = px
      *This\y = py
      *This\tag = ptag
EndProcedure

Procedure.s Point2D_ToString(*This.Point2D_Inst)
  Protected *This_vt.Point2D_vt = *This
      ProcedureReturn "[" + *This\tag + "] (" + Str(*This\x) + ", " + Str(*This\y) + ")"
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Calculatrice_VTable_Data:
    Data.i @Calculatrice_Additionner_i_i()
    Data.i @Calculatrice_Additionner_s_s()
    Data.i @Calculatrice_Additionner_d_d()
  Formateur_VTable_Data:
    Data.i @Formateur_Formater_i()
    Data.i @Formateur_Formater_i_s()
    Data.i @Formateur_Formater_i_s_s()
  Point2D_VTable_Data:
    Data.i @Point2D_ToString()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Calculatrice()
  Protected *obj.Calculatrice_Inst = AllocateStructure(Calculatrice_Inst)
  If *obj
    *obj\VTable = ?Calculatrice_VTable_Data
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Calculatrice(*obj.Calculatrice_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Formateur()
  Protected *obj.Formateur_Inst = AllocateStructure(Formateur_Inst)
  If *obj
    *obj\VTable = ?Formateur_VTable_Data
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Formateur(*obj.Formateur_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Point2D_void()
  Protected *obj.Point2D_Inst = AllocateStructure(Point2D_Inst)
  If *obj
    *obj\VTable = ?Point2D_VTable_Data
    Point2D_Init_void(*obj)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure.i New_Point2D_i_i(px.i, py.i)
  Protected *obj.Point2D_Inst = AllocateStructure(Point2D_Inst)
  If *obj
    *obj\VTable = ?Point2D_VTable_Data
    Point2D_Init_i_i(*obj, px, py)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure.i New_Point2D_i_i_s(px.i, py.i, ptag.s)
  Protected *obj.Point2D_Inst = AllocateStructure(Point2D_Inst)
  If *obj
    *obj\VTable = ?Point2D_VTable_Data
    Point2D_Init_i_i_s(*obj, px, py, ptag)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Point2D(*obj.Point2D_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Test Suite: Method Overloading & Multiple Constructors for PureBasic OOP
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; Class 1: Calculatrice (Type Overloading)
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; Class 2: Formateur (Arity Overloading)
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; Class 3: Point2D (Multiple Constructors: Overloaded Init)
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; Main Verification Program
; ----------------------------------------------------------------------------
OpenConsole()
CompilerIf #PB_Compiler_OS = #PB_OS_Windows
  SetConsoleOutputCP_(65001)
CompilerEndIf
PrintN("=== TEST SUITE: METHOD OVERLOADING & MULTI-CONSTRUCTORS ===")
PrintN("")

; 1. Test Calculatrice (Type Overloading)
Define *calc.Calculatrice_vt = New_Calculatrice()

Define resI.i = *calc\Additionner_i_i(15, 25)
If resI = 40
  PrintN("[PASS] Additionner(15, 25) = 40 (Integer)")
Else
  PrintN("[FAIL] Additionner integer returned " + Str(resI))
EndIf

Define resS.s = *calc\Additionner_s_s("PureBasic", "OOP")
If resS = "PureBasic OOP"
  PrintN("[PASS] Additionner('PureBasic', 'OOP') = 'PureBasic OOP' (String)")
Else
  PrintN("[FAIL] Additionner string returned '" + resS + "'")
EndIf

Define resD.d = *calc\Additionner_d_d(12.5, 7.5)
If resD = 20.0
  PrintN("[PASS] Additionner(12.5, 7.5) = 20.0 (Double)")
Else
  PrintN("[FAIL] Additionner double returned " + StrD(resD))
EndIf

PrintN("")

; 2. Test Formateur (Arity Overloading)
Define *fmt.Formateur_vt = New_Formateur()

Define f1.s = *fmt\Formater_i(42)
If f1 = "Nombre: 42"
  PrintN("[PASS] Formater(42) = 'Nombre: 42'")
Else
  PrintN("[FAIL] Formater(42) = '" + f1 + "'")
EndIf

Define f2.s = *fmt\Formater_i_s(42, "Score")
If f2 = "Score: 42"
  PrintN("[PASS] Formater(42, 'Score') = 'Score: 42'")
Else
  PrintN("[FAIL] Formater(42, 'Score') = '" + f2 + "'")
EndIf

Define f3.s = *fmt\Formater_i_s_s(42, "Score", "Points")
If f3 = "Score: 42 (Points)"
  PrintN("[PASS] Formater(42, 'Score', 'Points') = 'Score: 42 (Points)'")
Else
  PrintN("[FAIL] Formater 3 args = '" + f3 + "'")
EndIf

PrintN("")

; 3. Test Point2D (Multiple Constructors)
Define *p1.Point2D_vt = New_Point2D_void()
Define *p2.Point2D_vt = New_Point2D_i_i(100, 200)
Define *p3.Point2D_vt = New_Point2D_i_i_s(50, 75, "PlayerSpawn")

Define strP1.s = *p1\ToString()
If strP1 = "[Origine] (0, 0)"
  PrintN("[PASS] New_Point2D_void() -> " + strP1)
Else
  PrintN("[FAIL] New_Point2D_void() -> " + strP1)
EndIf

Define strP2.s = *p2\ToString()
If strP2 = "[Point] (100, 200)"
  PrintN("[PASS] New_Point2D_i_i(100, 200) -> " + strP2)
Else
  PrintN("[FAIL] New_Point2D_i_i(100, 200) -> " + strP2)
EndIf

Define strP3.s = *p3\ToString()
If strP3 = "[PlayerSpawn] (50, 75)"
  PrintN("[PASS] New_Point2D_i_i_s(50, 75, 'PlayerSpawn') -> " + strP3)
Else
  PrintN("[FAIL] New_Point2D_i_i_s(50, 75, 'PlayerSpawn') -> " + strP3)
EndIf

FreeStructure(*calc)
FreeStructure(*fmt)
FreeStructure(*p1)
FreeStructure(*p2)
FreeStructure(*p3)

PrintN("")
PrintN("Appuyez sur Entree pour quitter...")
Input()
CloseConsole()
