; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface App_Geometry_Shape_vt
  GetArea.d()
  Draw()
  PrintInfo()
EndInterface

Interface App_Geometry_Circle_vt Extends App_Geometry_Shape_vt
EndInterface

Interface App_Geometry_Rectangle_vt Extends App_Geometry_Shape_vt
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure App_Geometry_Shape_Inst
  *VTable.App_Geometry_Shape_vt
  name.s
EndStructure

Structure App_Geometry_Circle_Inst Extends App_Geometry_Shape_Inst
  radius.d
EndStructure

Structure App_Geometry_Rectangle_Inst Extends App_Geometry_Shape_Inst
  width.d
  height.d
EndStructure

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare App_Geometry_Shape_Init(*This.App_Geometry_Shape_Inst, nom.s)
Declare App_Geometry_Shape_PrintInfo(*This.App_Geometry_Shape_Inst)
Declare App_Geometry_Circle_Init(*This.App_Geometry_Circle_Inst, nom.s, r.d)
Declare.d App_Geometry_Circle_GetArea(*This.App_Geometry_Circle_Inst)
Declare App_Geometry_Circle_Draw(*This.App_Geometry_Circle_Inst)
Declare App_Geometry_Rectangle_Init(*This.App_Geometry_Rectangle_Inst, nom.s, w.d, h.d)
Declare.d App_Geometry_Rectangle_GetArea(*This.App_Geometry_Rectangle_Inst)
Declare App_Geometry_Rectangle_Draw(*This.App_Geometry_Rectangle_Inst)

Procedure App_Geometry_Shape_Init(*This.App_Geometry_Shape_Inst, nom.s)
  Protected *This_vt.App_Geometry_Shape_vt = *This
        *This\name = nom
EndProcedure

Procedure App_Geometry_Shape_PrintInfo(*This.App_Geometry_Shape_Inst)
  Protected *This_vt.App_Geometry_Shape_vt = *This
        PrintN("[Forme] " + *This\name + " | Aire = " + StrD(*This_vt\GetArea(), 2))
EndProcedure

Procedure App_Geometry_Circle_Init(*This.App_Geometry_Circle_Inst, nom.s, r.d)
  Protected *This_vt.App_Geometry_Circle_vt = *This
        App_Geometry_Shape_Init(*This, nom)
        *This\radius = r
EndProcedure

Procedure.d App_Geometry_Circle_GetArea(*This.App_Geometry_Circle_Inst)
  Protected *This_vt.App_Geometry_Circle_vt = *This
        ProcedureReturn 3.14159 * *This\radius * *This\radius
EndProcedure

Procedure App_Geometry_Circle_Draw(*This.App_Geometry_Circle_Inst)
  Protected *This_vt.App_Geometry_Circle_vt = *This
        PrintN("  -> Dessin du cercle (rayon = " + StrD(*This\radius, 2) + ")")
EndProcedure

Procedure App_Geometry_Rectangle_Init(*This.App_Geometry_Rectangle_Inst, nom.s, w.d, h.d)
  Protected *This_vt.App_Geometry_Rectangle_vt = *This
        App_Geometry_Shape_Init(*This, nom)
        *This\width = w
        *This\height = h
EndProcedure

Procedure.d App_Geometry_Rectangle_GetArea(*This.App_Geometry_Rectangle_Inst)
  Protected *This_vt.App_Geometry_Rectangle_vt = *This
        ProcedureReturn *This\width * *This\height
EndProcedure

Procedure App_Geometry_Rectangle_Draw(*This.App_Geometry_Rectangle_Inst)
  Protected *This_vt.App_Geometry_Rectangle_vt = *This
        PrintN("  -> Dessin du rectangle (" + StrD(*This\width, 2) + " x " + StrD(*This\height, 2) + ")")
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  App_Geometry_Circle_VTable_Data:
    Data.i @App_Geometry_Circle_GetArea()
    Data.i @App_Geometry_Circle_Draw()
    Data.i @App_Geometry_Shape_PrintInfo()
  App_Geometry_Rectangle_VTable_Data:
    Data.i @App_Geometry_Rectangle_GetArea()
    Data.i @App_Geometry_Rectangle_Draw()
    Data.i @App_Geometry_Shape_PrintInfo()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_App_Geometry_Circle(nom.s, r.d)
  Protected *obj.App_Geometry_Circle_Inst = AllocateStructure(App_Geometry_Circle_Inst)
  If *obj
    *obj\VTable = ?App_Geometry_Circle_VTable_Data
    App_Geometry_Circle_Init(*obj, nom, r)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_App_Geometry_Circle(*obj.App_Geometry_Circle_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_App_Geometry_Rectangle(nom.s, w.d, h.d)
  Protected *obj.App_Geometry_Rectangle_Inst = AllocateStructure(App_Geometry_Rectangle_Inst)
  If *obj
    *obj\VTable = ?App_Geometry_Rectangle_VTable_Data
    App_Geometry_Rectangle_Init(*obj, nom, w, h)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_App_Geometry_Rectangle(*obj.App_Geometry_Rectangle_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Test PureBasic OOP avec Syntaxe C-Style ({ })
; Fichier : src/test_c_style.pb
; ============================================================================






; Procédure C-Style avec If/Else et For
Procedure TestCalcul(facteur.i)
  PrintN("--- Execution Procedure TestCalcul(" + Str(facteur) + ") ---")
  Protected i.i
For i = 1 To 3
If (i % 2 = 0)
      PrintN("  Nombre pair : " + Str(i * facteur))
Else
      PrintN("  Nombre impair : " + Str(i * facteur))
EndIf
Next
EndProcedure

; Programme Principal

OpenConsole()
PrintN("=================================================================")
PrintN("        Test PureBasic OOP avec Double Syntaxe C-Style ({ })     ")
PrintN("=================================================================")

TestCalcul(10)
PrintN("")

Dim *shapes.App_Geometry_Shape_vt(1)
*shapes(0) = New_App_Geometry_Circle("MonCercle", 5.0)
*shapes(1) = New_App_Geometry_Rectangle("MonRectangle", 4.0, 6.0)

PrintN("--- Parcours Polymorphique ---")
Define j.i
For j = 0 To 1
  *shapes(j)\PrintInfo()
  *shapes(j)\Draw()
Next

PrintN("=================================================================")
PrintN("")
PrintN("Appuyez sur Entree pour quitter...")
Input()
CloseConsole()
