; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Game_Graphics_Renderer_vt
  Render()
EndInterface

Interface Game_Audio_SoundSystem_vt
  Play(soundName.s)
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Game_Graphics_Renderer_Inst
  *VTable.Game_Graphics_Renderer_vt
  width.i
  height.i
EndStructure

Structure Game_Audio_SoundSystem_Inst
  *VTable.Game_Audio_SoundSystem_vt
  volume.i
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare Game_Graphics_Renderer_Init(*This.Game_Graphics_Renderer_Inst, w.i, h.i)
Declare Game_Graphics_Renderer_Render(*This.Game_Graphics_Renderer_Inst)
Declare Game_Audio_SoundSystem_Init(*This.Game_Audio_SoundSystem_Inst, vol.i)
Declare Game_Audio_SoundSystem_Play(*This.Game_Audio_SoundSystem_Inst, soundName.s)

Declare.i New_Game_Graphics_Renderer(w.i, h.i)
Declare Free_Game_Graphics_Renderer(*obj.Game_Graphics_Renderer_Inst)
Declare.i New_Game_Audio_SoundSystem(vol.i)
Declare Free_Game_Audio_SoundSystem(*obj.Game_Audio_SoundSystem_Inst)

Procedure Game_Graphics_Renderer_Init(*This.Game_Graphics_Renderer_Inst, w.i, h.i)
  Protected *This_vt.Game_Graphics_Renderer_vt = *This
        *This\width = w
        *This\height = h
EndProcedure

Procedure Game_Graphics_Renderer_Render(*This.Game_Graphics_Renderer_Inst)
  Protected *This_vt.Game_Graphics_Renderer_vt = *This
        PrintN("[GFX Renderer] Rendering frame at " + Str(*This\width) + "x" + Str(*This\height))
EndProcedure

Procedure Game_Audio_SoundSystem_Init(*This.Game_Audio_SoundSystem_Inst, vol.i)
  Protected *This_vt.Game_Audio_SoundSystem_vt = *This
        *This\volume = vol
EndProcedure

Procedure Game_Audio_SoundSystem_Play(*This.Game_Audio_SoundSystem_Inst, soundName.s)
  Protected *This_vt.Game_Audio_SoundSystem_vt = *This
        PrintN("[Audio Engine] Playing '" + soundName + "' at volume " + Str(*This\volume) + "%")
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Game_Graphics_Renderer_VTable_Data:
    Data.i @Game_Graphics_Renderer_Render()
  Game_Audio_SoundSystem_VTable_Data:
    Data.i @Game_Audio_SoundSystem_Play()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Game_Graphics_Renderer(w.i, h.i)
  Protected *obj.Game_Graphics_Renderer_Inst = AllocateStructure(Game_Graphics_Renderer_Inst)
  If *obj
    *obj\VTable = ?Game_Graphics_Renderer_VTable_Data
    Game_Graphics_Renderer_Init(*obj, w, h)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Game_Graphics_Renderer(*obj.Game_Graphics_Renderer_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Game_Audio_SoundSystem(vol.i)
  Protected *obj.Game_Audio_SoundSystem_Inst = AllocateStructure(Game_Audio_SoundSystem_Inst)
  If *obj
    *obj\VTable = ?Game_Audio_SoundSystem_VTable_Data
    Game_Audio_SoundSystem_Init(*obj, vol)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Game_Audio_SoundSystem(*obj.Game_Audio_SoundSystem_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Test PureBasic OOP : Hierarchical Namespaces, Using & Aliases
; ============================================================================



; Namespace Alias: GFX -> Game_Graphics

; Using Directive: Import Game_Audio

OpenConsole()
PrintN("=== Test Namespaces, Using & Aliases ===")

; 1. Using fully qualified name
Define *ren1.Game_Graphics_Renderer_vt = New_Game_Graphics_Renderer(1920, 1080)
*ren1\Render()

; 2. Using Namespace Alias (GFX_Renderer)
Define *ren2.Game_Graphics_Renderer_vt = New_Game_Graphics_Renderer(800, 600)
*ren2\Render()

; 3. Using imported namespace via 'Using Game_Audio'
Define *audio.Game_Audio_SoundSystem_vt = New_Game_Audio_SoundSystem(85)
*audio\Play("intro.wav")

PrintN("=== End of Namespaces Test ===")
PrintN("")
PrintN("Appuyez sur Entree pour quitter...")
Input()
CloseConsole()
