; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Animal_vt
  Crier()
  Manger(nourriture.s)
  Free()
EndInterface

Interface Chien_vt Extends Animal_vt
  Rapporter(objet.s)
EndInterface

Interface Chat_vt Extends Animal_vt
  Ronronner()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Animal_Inst
  *VTable.Animal_vt
  nom.s
  age.i
EndStructure

Structure Chien_Inst Extends Animal_Inst
  race.s
EndStructure

Structure Chat_Inst Extends Animal_Inst
  nbVies.i
EndStructure

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Procedure Animal_Init(*This.Animal_Inst, nom_p.s, age_p.i)
    *This\nom = nom_p
    *This\age = age_p
EndProcedure

Procedure Animal_Crier(*This.Animal_Inst)
    PrintN("[Animal] " + *This\nom + " (" + Str(*This\age) + " ans) emet un son generique.")
EndProcedure

Procedure Animal_Manger(*This.Animal_Inst, nourriture.s)
    PrintN("[Animal] " + *This\nom + " mange avec appetit : " + nourriture)
EndProcedure

Procedure Animal_Free(*This.Animal_Inst)
    PrintN("[Animal::Free] Nettoyage memoire pour : " + *This\nom)
    FreeStructure(*This)
EndProcedure

Procedure Chien_Init(*This.Chien_Inst, nom_p.s, age_p.i, race_p.s)
    Animal_Init(*This, nom_p, age_p)
    *This\race = race_p
EndProcedure

Procedure Chien_Crier(*This.Chien_Inst)
    Animal_Crier(*This)
    PrintN("   ==> CHIEN (" + *This\race + ") : Wouaf ! Wouaf ! Grrr !")
EndProcedure

Procedure Chien_Rapporter(*This.Chien_Inst, objet.s)
    PrintN("   ==> " + *This\nom + " court et rapporte joyeusement : " + objet)
EndProcedure

Procedure Chien_Free(*This.Chien_Inst)
    PrintN("[Chien::Free] Liberation specifique du chien " + *This\nom)
    Animal_Free(*This)
EndProcedure

Procedure Chat_Init(*This.Chat_Inst, nom_p.s, age_p.i, nbVies_p.i)
    Animal_Init(*This, nom_p, age_p)
    *This\nbVies = nbVies_p
EndProcedure

Procedure Chat_Crier(*This.Chat_Inst)
    Animal_Crier(*This)
    PrintN("   ==> CHAT (Vies restantes: " + Str(*This\nbVies) + ") : Miaouuuu...")
EndProcedure

Procedure Chat_Ronronner(*This.Chat_Inst)
    PrintN("   ==> " + *This\nom + " fait ronron sur le canape.")
EndProcedure

Procedure Chat_Free(*This.Chat_Inst)
    PrintN("[Chat::Free] Liberation specifique du chat " + *This\nom)
    Animal_Free(*This)
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Animal_VTable_Data:
    Data.i @Animal_Crier()
    Data.i @Animal_Manger()
    Data.i @Animal_Free()
  Chien_VTable_Data:
    Data.i @Chien_Crier()
    Data.i @Animal_Manger()
    Data.i @Chien_Free()
    Data.i @Chien_Rapporter()
  Chat_VTable_Data:
    Data.i @Chat_Crier()
    Data.i @Animal_Manger()
    Data.i @Chat_Free()
    Data.i @Chat_Ronronner()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Animal(nom_p.s, age_p.i)
  Protected *obj.Animal_Inst = AllocateStructure(Animal_Inst)
  If *obj
    *obj\VTable = ?Animal_VTable_Data
    Animal_Init(*obj, nom_p, age_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure.i New_Chien(nom_p.s, age_p.i, race_p.s)
  Protected *obj.Chien_Inst = AllocateStructure(Chien_Inst)
  If *obj
    *obj\VTable = ?Chien_VTable_Data
    Chien_Init(*obj, nom_p, age_p, race_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure.i New_Chat(nom_p.s, age_p.i, nbVies_p.i)
  Protected *obj.Chat_Inst = AllocateStructure(Chat_Inst)
  If *obj
    *obj\VTable = ?Chat_VTable_Data
    Chat_Init(*obj, nom_p, age_p, nbVies_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; Test PureBasic OOP : Heritage, Polymorphisme & Super\
; Fichier source : test_polymorphisme.pb
; ============================================================================

; ----------------------------------------------------------------------------
; 1. CLASSE DE BASE : Animal
; ----------------------------------------------------------------------------





; ----------------------------------------------------------------------------
; 2. CLASSE DERIVEE : Chien (Herite de Animal)
; ----------------------------------------------------------------------------





; ----------------------------------------------------------------------------
; 3. CLASSE DERIVEE : Chat (Herite de Animal)
; ----------------------------------------------------------------------------





; ============================================================================
; 4. PROGRAMME PRINCIPAL DE TEST & DEMONSTRATION DU POLYMORPHISME
; ============================================================================

OpenConsole()
CompilerIf #PB_Compiler_OS = #PB_OS_Windows
  SetConsoleOutputCP_(65001) ; Support UTF-8 en console Windows
CompilerEndIf

PrintN("=================================================================")
PrintN("       DEMONSTRATION DU SYSTEME ORIENTE OBJET PUREBASIC          ")
PrintN("=================================================================")
PrintN("")

; A. Instanciations avec types concrets
PrintN("--- 1. Instanciations et appels de methodes directes ---")
Define *chien.Chien_vt = New_Chien("Medor", 4, "Golden Retriever")
Define *chat.Chat_vt = New_Chat("Felix", 2, 9)

If *chien
  *chien\Crier()
  *chien\Manger("un os a moelle")
  *chien\Rapporter("la balle de tennis")
EndIf

PrintN("")
If *chat
  *chat\Crier()
  *chat\Manger("une boite de thon")
  *chat\Ronronner()
EndIf

PrintN("")
PrintN("--- 2. Demonstration du Polymorphisme Dynamique (Liste d'Animal) ---")

; B. Polymorphisme : tableau / liste de pointeurs de type de base (Animal)
NewList *refuge.Animal_vt()

AddElement(*refuge()) : *refuge() = *chien
AddElement(*refuge()) : *refuge() = *chat
AddElement(*refuge()) : *refuge() = New_Chien("Rex", 7, "Berger Allemand")
AddElement(*refuge()) : *refuge() = New_Chat("Minouche", 1, 9)

PrintN("Nombre d'animaux dans le refuge : " + Str(ListSize(*refuge())))
PrintN("")

; Iteration polymorphe : chaque appel a Crier() et Free() dispatch vers la bonne classe !
ForEach *refuge()
  PrintN("-> Appel polymorphe sur animal [Index " + Str(ListIndex(*refuge())) + "] :")
  *refuge()\Crier()
  *refuge()\Manger("des croquettes")
  PrintN("")
Next

PrintN("--- 3. Nettoyage memoire polymorphe ---")
ForEach *refuge()
  *refuge()\Free()
Next
ClearList(*refuge())

PrintN("")
PrintN("=================================================================")
PrintN("               FIN DU TEST - TOUT S'EST DEROULE AVEC SUCCES      ")
PrintN("=================================================================")
PrintN("")
PrintN("Appuyez sur Entree pour quitter...")
Input()
CloseConsole()
