; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

#OOP_PROJECT_DIR = "c:\PB\PB_PROJECT\PB_OOP_WORKSPACE\PUREBASIC_OOP_WORKSPACE\"
#OOP_WORKSPACE_DIR = "C:\PB\PB_PROJECT\PB_OOP_WORKSPACE\PUREBASIC_OOP_WORKSPACE\"

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------

Structure DataObj
  f.f
  d.d
EndStructure

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------



; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------


Procedure SetMyDouble(*this.DataObj, val.d)
  *this\d = val
EndProcedure

Procedure SetMyFloat(*this.DataObj, val.f)
  *this\f = val
EndProcedure

Procedure TestSetter()
  Protected obj.DataObj
  Protected *fnSetD = @SetMyDouble()
  Protected valD.d = 99.45
  !movsd xmm1, [p.v_valD]
  CallFunctionFast(*fnSetD, @obj, 0)

  Protected *fnSetF = @SetMyFloat()
  Protected valF.f = 123.45
  !movss xmm1, [p.v_valF]
  CallFunctionFast(*fnSetF, @obj, 0)

  OpenConsole()
  PrintN("Set d: " + StrD(obj\d, 2))
  PrintN("Set f: " + StrF(obj\f, 2))
  CloseConsole()
EndProcedure

TestSetter()
