; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Chien_vt
  Aboyer()
  Free()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Chien_Inst
  *VTable.Chien_vt
  nom.s
  age.i
EndStructure

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Procedure Chien_Init(*This.Chien_Inst, nom_p.s, age_p.i)
    *This\nom = nom_p
    *This\age = age_p
EndProcedure

Procedure Chien_Aboyer(*This.Chien_Inst)
    PrintN(*This\nom + " dit : Wouaf ! Wouaf ! (Age : " + Str(*This\age) + " ans)")
EndProcedure

Procedure Chien_Free(*This.Chien_Inst)
  FreeStructure(*This)
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Chien_VTable_Data:
    Data.i @Chien_Aboyer()
    Data.i @Chien_Free()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Chien(nom_p.s, age_p.i)
  Protected *obj.Chien_Inst = AllocateStructure(Chien_Inst)
  If *obj
    *obj\VTable = ?Chien_VTable_Data
    Chien_Init(*obj, nom_p, age_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------




; ============================================================================
; EXEMPLE D'UTILISATION DE LA SYNTAXE POO (.pb)
; ============================================================================

; Instanciation simple de deux objets Chien
Define *chien1.Chien_vt = New_Chien("Médor", 3)
Define *chien2.Chien_vt = New_Chien("Rox", 5)

; Utilisation des méthodes
If *chien1
  *chien1\Aboyer()
  *chien1\Free()
EndIf

If *chien2
  *chien2\Aboyer()
  *chien2\Free()
EndIf
