; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine)
; Do not edit directly - modify the corresponding .pb source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Myname_Entities_Animal_vt
  Crier()
  GetNom.s()
  GetAge.i()
EndInterface

Interface Myname_Entities_Dog_vt Extends Myname_Entities_Animal_vt
EndInterface

Interface Myname_Entities_Cat_vt Extends Myname_Entities_Animal_vt
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Myname_Entities_Animal_Inst
  *VTable.Myname_Entities_Animal_vt
  nom.s
  age.i
EndStructure

Structure Myname_Entities_Dog_Inst Extends Myname_Entities_Animal_Inst
  race.s
EndStructure

Structure Myname_Entities_Cat_Inst Extends Myname_Entities_Animal_Inst
  couleur.s
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL DECLARATIONS & CONSTANTS
; ----------------------------------------------------------------------------

Dim *animaux.Myname_Entities_Animal_vt(1)

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare Myname_Entities_Animal_Init(*This.Myname_Entities_Animal_Inst, nom_p.s, age_p.i)
Declare.s Myname_Entities_Animal_GetNom(*This.Myname_Entities_Animal_Inst)
Declare.i Myname_Entities_Animal_GetAge(*This.Myname_Entities_Animal_Inst)
Declare Myname_Entities_Dog_Init(*This.Myname_Entities_Dog_Inst, nom_p.s, age_p.i, race_p.s)
Declare Myname_Entities_Dog_Crier(*This.Myname_Entities_Dog_Inst)
Declare Myname_Entities_Cat_Init(*This.Myname_Entities_Cat_Inst, nom_p.s, age_p.i, couleur_p.s)
Declare Myname_Entities_Cat_Crier(*This.Myname_Entities_Cat_Inst)

Declare.i New_Myname_Entities_Dog(nom_p.s, age_p.i, race_p.s)
Declare Free_Myname_Entities_Dog(*obj.Myname_Entities_Dog_Inst)
Declare.i New_Myname_Entities_Cat(nom_p.s, age_p.i, couleur_p.s)
Declare Free_Myname_Entities_Cat(*obj.Myname_Entities_Cat_Inst)

Procedure Myname_Entities_Animal_Init(*This.Myname_Entities_Animal_Inst, nom_p.s, age_p.i)
  Protected *This_vt.Myname_Entities_Animal_vt = *This
      *This\nom = nom_p
      *This\age = age_p
EndProcedure

Procedure.s Myname_Entities_Animal_GetNom(*This.Myname_Entities_Animal_Inst)
  Protected *This_vt.Myname_Entities_Animal_vt = *This
      ProcedureReturn *This\nom
EndProcedure

Procedure.i Myname_Entities_Animal_GetAge(*This.Myname_Entities_Animal_Inst)
  Protected *This_vt.Myname_Entities_Animal_vt = *This
      ProcedureReturn *This\age
EndProcedure

Procedure Myname_Entities_Dog_Init(*This.Myname_Entities_Dog_Inst, nom_p.s, age_p.i, race_p.s)
  Protected *This_vt.Myname_Entities_Dog_vt = *This
      Myname_Entities_Animal_Init(*This, nom_p, age_p)
      *This\race = race_p
EndProcedure

Procedure Myname_Entities_Dog_Crier(*This.Myname_Entities_Dog_Inst)
  Protected *This_vt.Myname_Entities_Dog_vt = *This
      PrintN("[Chien] " + *This_vt\GetNom() + " (" + *This\race + ", " + Str(*This_vt\GetAge()) + " ans) aboie : Wouaf ! Wouaf !")
EndProcedure

Procedure Myname_Entities_Cat_Init(*This.Myname_Entities_Cat_Inst, nom_p.s, age_p.i, couleur_p.s)
  Protected *This_vt.Myname_Entities_Cat_vt = *This
      Myname_Entities_Animal_Init(*This, nom_p, age_p)
      *This\couleur = couleur_p
EndProcedure

Procedure Myname_Entities_Cat_Crier(*This.Myname_Entities_Cat_Inst)
  Protected *This_vt.Myname_Entities_Cat_vt = *This
      PrintN("[Chat] " + *This_vt\GetNom() + " (pelage " + *This\couleur + ") miaule : Miaou...")
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Myname_Entities_Dog_VTable_Data:
    Data.i @Myname_Entities_Dog_Crier()
    Data.i @Myname_Entities_Animal_GetNom()
    Data.i @Myname_Entities_Animal_GetAge()
  Myname_Entities_Cat_VTable_Data:
    Data.i @Myname_Entities_Cat_Crier()
    Data.i @Myname_Entities_Animal_GetNom()
    Data.i @Myname_Entities_Animal_GetAge()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Myname_Entities_Dog(nom_p.s, age_p.i, race_p.s)
  Protected *obj.Myname_Entities_Dog_Inst = AllocateStructure(Myname_Entities_Dog_Inst)
  If *obj
    *obj\VTable = ?Myname_Entities_Dog_VTable_Data
    Myname_Entities_Dog_Init(*obj, nom_p, age_p, race_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Myname_Entities_Dog(*obj.Myname_Entities_Dog_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Myname_Entities_Cat(nom_p.s, age_p.i, couleur_p.s)
  Protected *obj.Myname_Entities_Cat_Inst = AllocateStructure(Myname_Entities_Cat_Inst)
  If *obj
    *obj\VTable = ?Myname_Entities_Cat_VTable_Data
    Myname_Entities_Cat_Init(*obj, nom_p, age_p, couleur_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Myname_Entities_Cat(*obj.Myname_Entities_Cat_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------


; ============================================================================
; Test Multi-Fichiers (1 fichier par classe) avec Namespaces & Polymorphisme
; Fichier principal : src/test_multifile_project.pb
; ============================================================================

; File: src/entities/Animal.pbi
; Single class file inside Namespace Myname_Entities




; IDE Options = PureBasic 6.40 (Windows - x64)
; CursorPosition = 1
; EnableXP
; DPIAware
; File: src/entities/Dog.pbi
; Dog class inheriting from Animal inside Namespace Myname_Entities





; IDE Options = PureBasic 6.40 (Windows - x64)
; CursorPosition = 3
; EnableXP
; DPIAware
; File: src/entities/Cat.pbi
; Cat class inheriting from Animal inside Namespace Myname_Entities





; IDE Options = PureBasic 6.40 (Windows - x64)
; CursorPosition = 1
; EnableXP
; DPIAware

; Import direct du namespace

OpenConsole()
PrintN("=================================================================")
PrintN("   Test Projet Multi-Fichiers & Namespaces (1 fichier/classe)   ")
PrintN("=================================================================")

; Instanciation des classes définies dans des fichiers séparés
Define *monChien.Myname_Entities_Dog_vt = New_Myname_Entities_Dog("Rex", 4, "Berger Allemand")
Define *monChat.Myname_Entities_Cat_vt = New_Myname_Entities_Cat("Félix", 2, "Gris tigré")

; Tableau polymorphique d'animaux
*animaux(0) = *monChien
*animaux(1) = *monChat

PrintN("--- Appel polymorphique Crier() ---")
Define i.i
For i = 0 To 1
  *animaux(i)\Crier()
Next

PrintN("=================================================================")
PrintN("")
PrintN("Appuyez sur Entree pour quitter...")
Input()
CloseConsole()

; IDE Options = PureBasic 6.40 (Windows - x64)
; CursorPosition = 16
; FirstLine = 5
; EnableXP
; DPIAware
