; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

#OOP_PROJECT_DIR = "tests\"
#OOP_WORKSPACE_DIR = "C:\PB\PB_PROJECT\PB_OOP_WORKSPACE\PUREBASIC_OOP_WORKSPACE\"

; PureBasic OOP Framework - Database & ORM Engine Integration
XIncludeFile #OOP_WORKSPACE_DIR + "framework/database/ORM.pbi"
UseModule Database
UseModule DatabaseEngine
UseModule DatabaseEntities
UseModule EntitySet
UseModule ORM_Schema

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Telephone_vt Extends DatabaseEntities::IDatabaseEntity
  Get_numero.s()
  Set_numero(val.s)
  Get_type.s()
  Set_type(val.s)
EndInterface

Interface Groupe_vt Extends DatabaseEntities::IDatabaseEntity
  Get_titre.s()
  Set_titre(val.s)
EndInterface

Interface Contact_vt Extends DatabaseEntities::IDatabaseEntity
  Get_nom.s()
  Set_nom(val.s)
  Get_email.s()
  Set_email(val.s)
  telephones.i()
  Add_telephones(*item)
  Count_telephones.i()
  groupes.i()
  Add_groupes(*item)
  Count_groupes.i()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Telephone_Inst
  *VTable.Telephone_vt
  id.i
  orm_isDirty.b
  orm_isNew.b
  numero.s
  type.s
  contact_id.i
EndStructure

Structure Groupe_Inst
  *VTable.Groupe_vt
  id.i
  orm_isDirty.b
  orm_isNew.b
  titre.s
EndStructure

Structure Contact_Inst
  *VTable.Contact_vt
  id.i
  orm_isDirty.b
  orm_isNew.b
  nom.s
  email.s
  telephones.EntitySet::IEntitySet
  groupes.EntitySet::IEntitySet
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


Declare Telephone_Serialize(*This.Telephone_Inst, Map values.s())
Declare Telephone_Deserialize(*This.Telephone_Inst, Map values.s())
Declare Groupe_Serialize(*This.Groupe_Inst, Map values.s())
Declare Groupe_Deserialize(*This.Groupe_Inst, Map values.s())
Declare Contact_Serialize(*This.Contact_Inst, Map values.s())
Declare Contact_Deserialize(*This.Contact_Inst, Map values.s())
Declare Contact_SaveChildren_telephones(*This.Contact_Inst, db.i)
Declare Contact_SaveChildren_groupes(*This.Contact_Inst, db.i)
Declare Register_All_Entities()

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare.s Telephone_Get_numero(*This.Telephone_Inst)
Declare Telephone_Set_numero(*This.Telephone_Inst, val.s)
Declare.s Telephone_Get_type(*This.Telephone_Inst)
Declare Telephone_Set_type(*This.Telephone_Inst, val.s)
Declare.i Telephone_GetId(*This.Telephone_Inst)
Declare Telephone_SetId(*This.Telephone_Inst, id.i)
Declare.b Telephone_IsDirty(*This.Telephone_Inst)
Declare Telephone_SetDirty(*This.Telephone_Inst, dirty.b)
Declare.b Telephone_IsNew(*This.Telephone_Inst)
Declare Telephone_SetNew(*This.Telephone_Inst, isNew.b)
Declare.b Telephone_Save(*This.Telephone_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Telephone_Delete(*This.Telephone_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Telephone_Reload(*This.Telephone_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.s Telephone_GetTableName(*This.Telephone_Inst)
Declare.s Telephone_GetEntityName(*This.Telephone_Inst)
Declare.s Groupe_Get_titre(*This.Groupe_Inst)
Declare Groupe_Set_titre(*This.Groupe_Inst, val.s)
Declare.i Groupe_GetId(*This.Groupe_Inst)
Declare Groupe_SetId(*This.Groupe_Inst, id.i)
Declare.b Groupe_IsDirty(*This.Groupe_Inst)
Declare Groupe_SetDirty(*This.Groupe_Inst, dirty.b)
Declare.b Groupe_IsNew(*This.Groupe_Inst)
Declare Groupe_SetNew(*This.Groupe_Inst, isNew.b)
Declare.b Groupe_Save(*This.Groupe_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Groupe_Delete(*This.Groupe_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Groupe_Reload(*This.Groupe_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.s Groupe_GetTableName(*This.Groupe_Inst)
Declare.s Groupe_GetEntityName(*This.Groupe_Inst)
Declare.s Contact_Get_nom(*This.Contact_Inst)
Declare Contact_Set_nom(*This.Contact_Inst, val.s)
Declare.s Contact_Get_email(*This.Contact_Inst)
Declare Contact_Set_email(*This.Contact_Inst, val.s)
Declare.i Contact_telephones(*This.Contact_Inst)
Declare Contact_Add_telephones(*This.Contact_Inst, *item)
Declare.i Contact_Count_telephones(*This.Contact_Inst)
Declare.i Contact_groupes(*This.Contact_Inst)
Declare Contact_Add_groupes(*This.Contact_Inst, *item)
Declare.i Contact_Count_groupes(*This.Contact_Inst)
Declare.i Contact_GetId(*This.Contact_Inst)
Declare Contact_SetId(*This.Contact_Inst, id.i)
Declare.b Contact_IsDirty(*This.Contact_Inst)
Declare Contact_SetDirty(*This.Contact_Inst, dirty.b)
Declare.b Contact_IsNew(*This.Contact_Inst)
Declare Contact_SetNew(*This.Contact_Inst, isNew.b)
Declare.b Contact_Save(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Contact_Delete(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Contact_Reload(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.s Contact_GetTableName(*This.Contact_Inst)
Declare.s Contact_GetEntityName(*This.Contact_Inst)

Declare.i New_Telephone()
Declare Free_Telephone(*obj.Telephone_Inst)
Declare.i New_Groupe()
Declare Free_Groupe(*obj.Groupe_Inst)
Declare.i New_Contact()
Declare Free_Contact(*obj.Contact_Inst)

Procedure.s Telephone_Get_numero(*This.Telephone_Inst)
  Protected *This_vt.Telephone_vt = *This
  ProcedureReturn *This\numero
EndProcedure

Procedure Telephone_Set_numero(*This.Telephone_Inst, val.s)
  Protected *This_vt.Telephone_vt = *This
  *This\numero = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.s Telephone_Get_type(*This.Telephone_Inst)
  Protected *This_vt.Telephone_vt = *This
  ProcedureReturn *This\type
EndProcedure

Procedure Telephone_Set_type(*This.Telephone_Inst, val.s)
  Protected *This_vt.Telephone_vt = *This
  *This\type = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.i Telephone_GetId(*This.Telephone_Inst)
  Protected *This_vt.Telephone_vt = *This
  ProcedureReturn *This\id
EndProcedure

Procedure Telephone_SetId(*This.Telephone_Inst, id.i)
  Protected *This_vt.Telephone_vt = *This
  *This\id = id
EndProcedure

Procedure.b Telephone_IsDirty(*This.Telephone_Inst)
  Protected *This_vt.Telephone_vt = *This
  ProcedureReturn *This\orm_isDirty
EndProcedure

Procedure Telephone_SetDirty(*This.Telephone_Inst, dirty.b)
  Protected *This_vt.Telephone_vt = *This
  *This\orm_isDirty = dirty
EndProcedure

Procedure.b Telephone_IsNew(*This.Telephone_Inst)
  Protected *This_vt.Telephone_vt = *This
  ProcedureReturn *This\orm_isNew
EndProcedure

Procedure Telephone_SetNew(*This.Telephone_Inst, isNew.b)
  Protected *This_vt.Telephone_vt = *This
  *This\orm_isNew = isNew
EndProcedure

Procedure.b Telephone_Save(*This.Telephone_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Telephone_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Save(*This)
EndProcedure

Procedure.b Telephone_Delete(*This.Telephone_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Telephone_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Delete(*This)
EndProcedure

Procedure.b Telephone_Reload(*This.Telephone_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Telephone_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 Or *This\id = 0 : ProcedureReturn #False : EndIf
  NewMap vals.s()
  If ORM_CRUD::SelectById(targetDb\GetHandle(), "Telephone", *This\id, vals())
    Telephone_Deserialize(*This, vals())
    *This\orm_isDirty = #False
    *This\orm_isNew = #False
    ProcedureReturn #True
  EndIf
  ProcedureReturn #False
EndProcedure

Procedure.s Telephone_GetTableName(*This.Telephone_Inst)
  Protected *This_vt.Telephone_vt = *This
  ProcedureReturn "telephones"
EndProcedure

Procedure.s Telephone_GetEntityName(*This.Telephone_Inst)
  Protected *This_vt.Telephone_vt = *This
  ProcedureReturn "Telephone"
EndProcedure

Procedure.s Groupe_Get_titre(*This.Groupe_Inst)
  Protected *This_vt.Groupe_vt = *This
  ProcedureReturn *This\titre
EndProcedure

Procedure Groupe_Set_titre(*This.Groupe_Inst, val.s)
  Protected *This_vt.Groupe_vt = *This
  *This\titre = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.i Groupe_GetId(*This.Groupe_Inst)
  Protected *This_vt.Groupe_vt = *This
  ProcedureReturn *This\id
EndProcedure

Procedure Groupe_SetId(*This.Groupe_Inst, id.i)
  Protected *This_vt.Groupe_vt = *This
  *This\id = id
EndProcedure

Procedure.b Groupe_IsDirty(*This.Groupe_Inst)
  Protected *This_vt.Groupe_vt = *This
  ProcedureReturn *This\orm_isDirty
EndProcedure

Procedure Groupe_SetDirty(*This.Groupe_Inst, dirty.b)
  Protected *This_vt.Groupe_vt = *This
  *This\orm_isDirty = dirty
EndProcedure

Procedure.b Groupe_IsNew(*This.Groupe_Inst)
  Protected *This_vt.Groupe_vt = *This
  ProcedureReturn *This\orm_isNew
EndProcedure

Procedure Groupe_SetNew(*This.Groupe_Inst, isNew.b)
  Protected *This_vt.Groupe_vt = *This
  *This\orm_isNew = isNew
EndProcedure

Procedure.b Groupe_Save(*This.Groupe_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Groupe_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Save(*This)
EndProcedure

Procedure.b Groupe_Delete(*This.Groupe_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Groupe_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Delete(*This)
EndProcedure

Procedure.b Groupe_Reload(*This.Groupe_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Groupe_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 Or *This\id = 0 : ProcedureReturn #False : EndIf
  NewMap vals.s()
  If ORM_CRUD::SelectById(targetDb\GetHandle(), "Groupe", *This\id, vals())
    Groupe_Deserialize(*This, vals())
    *This\orm_isDirty = #False
    *This\orm_isNew = #False
    ProcedureReturn #True
  EndIf
  ProcedureReturn #False
EndProcedure

Procedure.s Groupe_GetTableName(*This.Groupe_Inst)
  Protected *This_vt.Groupe_vt = *This
  ProcedureReturn "groupes"
EndProcedure

Procedure.s Groupe_GetEntityName(*This.Groupe_Inst)
  Protected *This_vt.Groupe_vt = *This
  ProcedureReturn "Groupe"
EndProcedure

Procedure.s Contact_Get_nom(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\nom
EndProcedure

Procedure Contact_Set_nom(*This.Contact_Inst, val.s)
  Protected *This_vt.Contact_vt = *This
  *This\nom = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.s Contact_Get_email(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\email
EndProcedure

Procedure Contact_Set_email(*This.Contact_Inst, val.s)
  Protected *This_vt.Contact_vt = *This
  *This\email = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.i Contact_telephones(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\telephones
EndProcedure

Procedure Contact_Add_telephones(*This.Contact_Inst, *item)
  Protected *This_vt.Contact_vt = *This
  If *This\telephones : *This\telephones\Add(*item) : EndIf
EndProcedure

Procedure.i Contact_Count_telephones(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  If *This\telephones : ProcedureReturn *This\telephones\Count() : EndIf : ProcedureReturn 0
EndProcedure

Procedure.i Contact_groupes(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\groupes
EndProcedure

Procedure Contact_Add_groupes(*This.Contact_Inst, *item)
  Protected *This_vt.Contact_vt = *This
  If *This\groupes : *This\groupes\Add(*item) : EndIf
EndProcedure

Procedure.i Contact_Count_groupes(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  If *This\groupes : ProcedureReturn *This\groupes\Count() : EndIf : ProcedureReturn 0
EndProcedure

Procedure.i Contact_GetId(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\id
EndProcedure

Procedure Contact_SetId(*This.Contact_Inst, id.i)
  Protected *This_vt.Contact_vt = *This
  *This\id = id
EndProcedure

Procedure.b Contact_IsDirty(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\orm_isDirty
EndProcedure

Procedure Contact_SetDirty(*This.Contact_Inst, dirty.b)
  Protected *This_vt.Contact_vt = *This
  *This\orm_isDirty = dirty
EndProcedure

Procedure.b Contact_IsNew(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\orm_isNew
EndProcedure

Procedure Contact_SetNew(*This.Contact_Inst, isNew.b)
  Protected *This_vt.Contact_vt = *This
  *This\orm_isNew = isNew
EndProcedure

Procedure.b Contact_Save(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Contact_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Save(*This)
EndProcedure

Procedure.b Contact_Delete(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Contact_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Delete(*This)
EndProcedure

Procedure.b Contact_Reload(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Contact_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 Or *This\id = 0 : ProcedureReturn #False : EndIf
  NewMap vals.s()
  If ORM_CRUD::SelectById(targetDb\GetHandle(), "Contact", *This\id, vals())
    Contact_Deserialize(*This, vals())
    *This\orm_isDirty = #False
    *This\orm_isNew = #False
    ProcedureReturn #True
  EndIf
  ProcedureReturn #False
EndProcedure

Procedure.s Contact_GetTableName(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn "contacts"
EndProcedure

Procedure.s Contact_GetEntityName(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn "Contact"
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Telephone_VTable_Data:
    Data.i @Telephone_GetId()
    Data.i @Telephone_SetId()
    Data.i @Telephone_IsDirty()
    Data.i @Telephone_SetDirty()
    Data.i @Telephone_IsNew()
    Data.i @Telephone_SetNew()
    Data.i @Telephone_Save()
    Data.i @Telephone_Delete()
    Data.i @Telephone_Reload()
    Data.i @Telephone_GetTableName()
    Data.i @Telephone_GetEntityName()
    Data.i @Telephone_Get_numero()
    Data.i @Telephone_Set_numero()
    Data.i @Telephone_Get_type()
    Data.i @Telephone_Set_type()
  Groupe_VTable_Data:
    Data.i @Groupe_GetId()
    Data.i @Groupe_SetId()
    Data.i @Groupe_IsDirty()
    Data.i @Groupe_SetDirty()
    Data.i @Groupe_IsNew()
    Data.i @Groupe_SetNew()
    Data.i @Groupe_Save()
    Data.i @Groupe_Delete()
    Data.i @Groupe_Reload()
    Data.i @Groupe_GetTableName()
    Data.i @Groupe_GetEntityName()
    Data.i @Groupe_Get_titre()
    Data.i @Groupe_Set_titre()
  Contact_VTable_Data:
    Data.i @Contact_GetId()
    Data.i @Contact_SetId()
    Data.i @Contact_IsDirty()
    Data.i @Contact_SetDirty()
    Data.i @Contact_IsNew()
    Data.i @Contact_SetNew()
    Data.i @Contact_Save()
    Data.i @Contact_Delete()
    Data.i @Contact_Reload()
    Data.i @Contact_GetTableName()
    Data.i @Contact_GetEntityName()
    Data.i @Contact_Get_nom()
    Data.i @Contact_Set_nom()
    Data.i @Contact_Get_email()
    Data.i @Contact_Set_email()
    Data.i @Contact_telephones()
    Data.i @Contact_Add_telephones()
    Data.i @Contact_Count_telephones()
    Data.i @Contact_groupes()
    Data.i @Contact_Add_groupes()
    Data.i @Contact_Count_groupes()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Telephone()
  Protected *obj.Telephone_Inst = AllocateStructure(Telephone_Inst)
  If *obj
    *obj\VTable = ?Telephone_VTable_Data
    *obj\orm_isNew = #True
    *obj\orm_isDirty = #False
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Telephone(*obj.Telephone_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Groupe()
  Protected *obj.Groupe_Inst = AllocateStructure(Groupe_Inst)
  If *obj
    *obj\VTable = ?Groupe_VTable_Data
    *obj\orm_isNew = #True
    *obj\orm_isDirty = #False
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Groupe(*obj.Groupe_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Contact()
  Protected *obj.Contact_Inst = AllocateStructure(Contact_Inst)
  If *obj
    *obj\VTable = ?Contact_VTable_Data
    *obj\orm_isNew = #True
    *obj\orm_isDirty = #False
    *obj\telephones = EntitySet::New()
    *obj\groupes = EntitySet::New()
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Contact(*obj.Contact_Inst)
  If *obj
    If *obj\telephones : *obj\telephones\Free() : EndIf
    If *obj\groupes : *obj\groupes\Free() : EndIf
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 5.5 ORM ENTITY SERIALIZATION, DESERIALIZATION & REGISTRATION
; ----------------------------------------------------------------------------

Procedure Telephone_Serialize(*This.Telephone_Inst, Map values.s())
  ClearMap(values())
  values("numero") = *This\numero
  values("type") = *This\type
  values("contact_id") = Str(*This\contact_id)
EndProcedure

Procedure Telephone_Deserialize(*This.Telephone_Inst, Map values.s())
  If FindMapElement(values(), "id") : *This\id = Val(values()) : EndIf
  If FindMapElement(values(), "numero") : *This\numero = values() : EndIf
  If FindMapElement(values(), "type") : *This\type = values() : EndIf
  If FindMapElement(values(), "contact_id") : *This\contact_id = Val(values()) : EndIf
EndProcedure

Procedure Groupe_Serialize(*This.Groupe_Inst, Map values.s())
  ClearMap(values())
  values("titre") = *This\titre
EndProcedure

Procedure Groupe_Deserialize(*This.Groupe_Inst, Map values.s())
  If FindMapElement(values(), "id") : *This\id = Val(values()) : EndIf
  If FindMapElement(values(), "titre") : *This\titre = values() : EndIf
EndProcedure

Procedure Contact_Serialize(*This.Contact_Inst, Map values.s())
  ClearMap(values())
  values("nom") = *This\nom
  values("email") = *This\email
EndProcedure

Procedure Contact_Deserialize(*This.Contact_Inst, Map values.s())
  If FindMapElement(values(), "id") : *This\id = Val(values()) : EndIf
  If FindMapElement(values(), "nom") : *This\nom = values() : EndIf
  If FindMapElement(values(), "email") : *This\email = values() : EndIf
EndProcedure

Procedure Contact_SaveChildren_telephones(*This.Contact_Inst, db.i)
  Protected targetDb.DatabaseEngine::IDatabase = Database::WrapHandle(db)
  If Not targetDb : targetDb = Database::GetDefault() : EndIf
  If Not targetDb : ProcedureReturn : EndIf
  If *This\telephones
    Protected count.i = *This\telephones\Count()
    Protected i.i
    For i = 0 To count - 1
      Protected item.DatabaseEntities::IDatabaseEntity = *This\telephones\Get(i)
      If item
        Protected *itemInst.Telephone_Inst = item
        *itemInst\contact_id = *This\id
        item\Save(targetDb)
      EndIf
    Next
    count = *This\telephones\GetRemovedCount()
    For i = 0 To count - 1
      Protected remItem.DatabaseEntities::IDatabaseEntity = *This\telephones\GetRemovedItem(i)
      If remItem : remItem\Delete(targetDb) : EndIf
    Next
    *This\telephones\ResetTracking()
  EndIf
EndProcedure

Procedure Contact_SaveChildren_groupes(*This.Contact_Inst, db.i)
  Protected targetDb.DatabaseEngine::IDatabase = Database::WrapHandle(db)
  If Not targetDb : targetDb = Database::GetDefault() : EndIf
  If Not targetDb : ProcedureReturn : EndIf
  If *This\groupes And *This\id > 0
    ORM_Relations::SyncManyToManyLinks(db, "contact_groupes", "contact_id", *This\id, "groupe_id", *This\groupes)
  EndIf
EndProcedure

Procedure Register_All_Entities()
  NewList currentFields.ORM_Schema::ORM_FieldDef()
  NewList currentRelations.ORM_Schema::ORM_RelationDef()

  ; Register entity Telephone
  ClearList(currentFields())
  ClearList(currentRelations())
  AddElement(currentFields()) : currentFields()\name = "numero" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "type" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "contact_id" : currentFields()\typeCode = ORM_Entity::#ORM_Type_Integer
  ORM_Schema::RegisterEntity("Telephone", "telephones", currentFields(), currentRelations(), @Telephone_Serialize(), @Telephone_Deserialize(), @New_Telephone(), #True)

  ; Register entity Groupe
  ClearList(currentFields())
  ClearList(currentRelations())
  AddElement(currentFields()) : currentFields()\name = "titre" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  ORM_Schema::RegisterEntity("Groupe", "groupes", currentFields(), currentRelations(), @Groupe_Serialize(), @Groupe_Deserialize(), @New_Groupe(), #True)

  ; Register entity Contact
  ClearList(currentFields())
  ClearList(currentRelations())
  AddElement(currentFields()) : currentFields()\name = "nom" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "email" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentRelations())
  currentRelations()\relationType = ORM_Entity::#ORM_Rel_OneToMany
  currentRelations()\propertyName = "telephones"
  currentRelations()\childEntityType = "Telephone"
  currentRelations()\childTable = "telephones"
  currentRelations()\fkColumn = "contact_id"
  currentRelations()\joinTable = ""
  currentRelations()\parentFkColumn = "contact_id"
  currentRelations()\childFkColumn = "telephone_id"
  currentRelations()\cascadeSave = #True
  currentRelations()\saveChildrenProc = @Contact_SaveChildren_telephones()
  AddElement(currentRelations())
  currentRelations()\relationType = ORM_Entity::#ORM_Rel_ManyToMany
  currentRelations()\propertyName = "groupes"
  currentRelations()\childEntityType = "Groupe"
  currentRelations()\childTable = "groupes"
  currentRelations()\fkColumn = "contact_id"
  currentRelations()\joinTable = "contact_groupes"
  currentRelations()\parentFkColumn = "contact_id"
  currentRelations()\childFkColumn = "groupe_id"
  currentRelations()\cascadeSave = #True
  currentRelations()\saveChildrenProc = @Contact_SaveChildren_groupes()
  ORM_Schema::RegisterEntity("Contact", "contacts", currentFields(), currentRelations(), @Contact_Serialize(), @Contact_Deserialize(), @New_Contact(), #True)

EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

Register_All_Entities()

; =============================================================================
; test_orm_relations.pbo - End-to-End ORM Relations Test
; PureBasic OOP Framework - Alpha 1.4 (Phase 2)
; =============================================================================




; =============================================================================
; MAIN TEST EXECUTION
; =============================================================================

OpenConsole()
PrintN("=================================================================")
PrintN("  ORM ALPHA 1.4 - END-TO-END RELATIONS & ENTITY TEST")
PrintN("=================================================================")

; 1. Initialisation de la base de données
DeleteFile("test_crm_orm.db")
Define *db.DatabaseEngine::IDatabase = Database::NewSQLite("test_crm_orm.db")
If Not *db
  PrintN("[FAIL] Cannot initialize SQLite database.")
  End 1
EndIf

; Set active default database
Database::SetDefault(*db)

; Auto-migration (creates contacts, telephones, groupes, and contact_groupes)
If Not *db\AutoMigrate()
  PrintN("[FAIL] AutoMigrate failed.")
  End 1
EndIf
PrintN("[PASS] AutoMigrate created all tables and junction tables.")

; 2. Création et association des entités
Define *contact.Contact_vt = New_Contact()
*contact\Set_nom("Alice Dupont")
*contact\Set_email("alice@example.com")

Define *t1.Telephone_vt = New_Telephone()
*t1\Set_numero("0123456789")
*t1\Set_type("Mobile")
*contact\Add_telephones(*t1)

Define *t2.Telephone_vt = New_Telephone()
*t2\Set_numero("0987654321")
*t2\Set_type("Bureau")
*contact\Add_telephones(*t2)

Define *g1.Groupe_vt = New_Groupe()
*g1\Set_titre("Clients VIP")
*contact\Add_groupes(*g1)

; 3. Sauvegarde en cascade via *contact\Save() (Active Record style)
Define ok.b = *contact\Save()
If Not ok
  PrintN("[FAIL] *contact\Save() returned False.")
  End 1
EndIf
PrintN("[PASS] *contact\Save() succeeded.")

; 4. Vérification des identifiants générés
If *contact\GetId() <= 0
  PrintN("[FAIL] Contact ID is <= 0: " + Str(*contact\GetId()))
  End 1
EndIf
PrintN("[PASS] Contact saved with ID: " + Str(*contact\GetId()))

If *t1\GetId() <= 0 Or *t2\GetId() <= 0
  PrintN("[FAIL] Telephones IDs not generated.")
  End 1
EndIf
PrintN("[PASS] Cascade 1-N saved telephones with IDs: " + Str(*t1\GetId()) + ", " + Str(*t2\GetId()))

If *g1\GetId() <= 0
  PrintN("[FAIL] Groupe ID not generated.")
  End 1
EndIf
PrintN("[PASS] ManyToMany saved groupe with ID: " + Str(*g1\GetId()))

; 5. Vérification directe en base SQL
Define q.i = *db\Query("SELECT COUNT(*) FROM telephones WHERE contact_id = " + Str(*contact\GetId()) + ";")
If q
  If NextDatabaseRow(*db\GetHandle())
    Define phoneCount.i = GetDatabaseLong(*db\GetHandle(), 0)
    If phoneCount = 2
      PrintN("[PASS] Verified 2 telephones in DB for contact_id = " + Str(*contact\GetId()))
    Else
      PrintN("[FAIL] Expected 2 telephones, got " + Str(phoneCount))
      End 1
    EndIf
  EndIf
  FinishDatabaseQuery(*db\GetHandle())
EndIf

Define qJunc.i = *db\Query("SELECT COUNT(*) FROM contact_groupes WHERE contact_id = " + Str(*contact\GetId()) + ";")
If qJunc
  If NextDatabaseRow(*db\GetHandle())
    Define juncCount.i = GetDatabaseLong(*db\GetHandle(), 0)
    If juncCount = 1
      PrintN("[PASS] Verified 1 link in junction table contact_groupes")
    Else
      PrintN("[FAIL] Expected 1 link in contact_groupes, got " + Str(juncCount))
      End 1
    EndIf
  EndIf
  FinishDatabaseQuery(*db\GetHandle())
EndIf

; 6. Nettoyage
FreeStructure(*contact)
FreeStructure(*t1)
FreeStructure(*t2)
FreeStructure(*g1)
*db\Disconnect()

PrintN("=================================================================")
PrintN("  ALL TESTS PASSED SUCCESSFULLY! (100% OK)")
PrintN("=================================================================")
