; =============================================================================
; ORM.pbi - Public API entry point for the PureBasic OOP Data Engine
; PureBasic OOP Framework - Alpha 1.4
; =============================================================================
; This is the ONLY file you need to include in your project:
;
;   XIncludeFile "framework/database/ORM.pbi"
;
; Then:
;   1. Configure the database engine
;   2. Register your entities
;   3. Call AutoMigrate()
;   4. Use entities via their methods (Save, Load, Lock, Delete...)
;
; See examples/06_database_crm/ for a complete working demo.
; =============================================================================

XIncludeFile "ORM_Entity.pbi"
XIncludeFile "ORM_Dialect_SQLite.pbi"
XIncludeFile "ORM_Transaction.pbi"
XIncludeFile "ORM_Schema.pbi"
XIncludeFile "ORM_LockManager.pbi"
XIncludeFile "ORM_AsyncWorker.pbi"

DeclareModule ORM

  ; ---------------------------------------------------------------------------
  ; Global state (one database connection per application for the UI thread)
  ; Workers get their own connections in ORM_AsyncWorker.
  ; ---------------------------------------------------------------------------
  Global orm_mainDb.i   = 0       ; Main DB handle (used for sync ops & schema)
  Global orm_dbPath.s   = ""      ; Path to SQLite file
  Global orm_mainWindow.i = 0     ; Main window handle for async PostEvent

  ; ---------------------------------------------------------------------------
  ; --- DATABASE CONFIGURATION ---
  ; ---------------------------------------------------------------------------

  ; Configure the engine to use an SQLite database file.
  ; Call this ONCE in main.pb before Register() or AutoMigrate().
  ;   filePath.s : full or relative path to the .db file
  ;                e.g. "app_data.db" or GetPathPart(ProgramFilename()) + "data\crm.db"
  Declare ConfigureSQLite(filePath.s)

  ; Configure for MySQL / MariaDB (Phase 2 - not yet implemented in Alpha 1.4)
  ;   host.s     : server IP or hostname (e.g. "192.168.1.100")
  ;   port.i     : TCP port (default 3306)
  ;   dbName.s   : database/schema name
  ;   user.s     : login username
  ;   password.s : login password
  Declare ConfigureMySQL(host.s, port.i, dbName.s, user.s, password.s)

  ; Set the main window handle so async callbacks can PostEvent to it.
  ; Call this after OpenWindow().
  Declare SetMainWindow(windowId.i)

  ; ---------------------------------------------------------------------------
  ; --- ENTITY REGISTRATION ---
  ; ---------------------------------------------------------------------------

  ; Register an entity metadata descriptor so AutoMigrate can manage its table.
  ; Each entity class has a companion *_Meta() procedure generated by the OOP
  ; transpiler, which fills the field list. You pass that procedure's address here.
  ;
  ; Example:
  ;   ORM::Register("Client", "clients", @Client_Meta())
  ;
  ; Parameters:
  ;   entityName.s  : class name (e.g. "Client")
  ;   tableName.s   : SQL table name (e.g. "clients") - auto-derived if ""
  ;   metaProc.i    : pointer to the entity meta-registration procedure
  Declare Register(entityName.s, tableName.s = "", metaProc.i = 0)

  ; ---------------------------------------------------------------------------
  ; --- SCHEMA AUTO-MIGRATION ---
  ; ---------------------------------------------------------------------------

  ; Create or update all registered entity tables in the database.
  ; Safe to call on every startup: existing tables are never dropped.
  ; New columns discovered in the class definition are added with ALTER TABLE.
  Declare.b AutoMigrate()

  ; ---------------------------------------------------------------------------
  ; --- SYNCHRONOUS OPERATIONS (use with care - may block UI for small DBs) ---
  ; ---------------------------------------------------------------------------

  ; Find a single entity by primary key. Returns pointer to entity or 0.
  ; Declare.i FindById(entityType.s, recordId.i)

  ; Execute a query and return a list of entities.
  ; Declare QueryList(entityType.s, whereClause.s, List *results())

  ; ---------------------------------------------------------------------------
  ; --- ASYNCHRONOUS OPERATIONS (recommended - never blocks UI) ---
  ; ---------------------------------------------------------------------------

  ; Load one entity by id in the background.
  ; Callback signature: Procedure OnLoaded(*entity, result.i) : EndProcedure
  Declare FindByIdAsync(entityType.s, recordId.i, callbackPtr.i)

  ; Load a list of entities matching a WHERE clause in the background.
  ; Callback signature: Procedure OnList(List *results(), result.i) : EndProcedure
  Declare QueryAsync(entityType.s, whereClause.s, callbackPtr.i)

  ; ---------------------------------------------------------------------------
  ; --- SHUTDOWN ---
  ; ---------------------------------------------------------------------------

  ; Close the database and stop all worker threads cleanly.
  ; Call this at application exit (in the CloseWindow or End block).
  Declare Shutdown()

EndDeclareModule

Module ORM

  ; ---------------------------------------------------------------------------
  ; Configure SQLite
  ; ---------------------------------------------------------------------------
  Procedure ConfigureSQLite(filePath.s)
    orm_dbPath = filePath

    ; Activate the SQLite driver
    UseSQLiteDatabase()

    ; Open the main connection (creates the file if it does not exist)
    orm_mainDb = OpenDatabase(#PB_Any, filePath, "", "", #PB_Database_SQLite)
    If Not IsDatabase(orm_mainDb)
      MessageRequester("ORM Error",
                       "Cannot open SQLite database:" + #CRLF$ + filePath + #CRLF$ + #CRLF$ +
                       "Check that the path exists and you have write permission.",
                       #PB_MessageRequester_Error)
      End
    EndIf

    ; Enable WAL mode for better concurrent performance
    ORM_Transaction::Execute(orm_mainDb, "PRAGMA journal_mode=WAL;")
    ORM_Transaction::Execute(orm_mainDb, "PRAGMA foreign_keys=ON;")

    Debug "ORM: SQLite database opened: " + filePath
  EndProcedure

  ; ---------------------------------------------------------------------------
  ; Configure MySQL (stub - Phase 2)
  ; ---------------------------------------------------------------------------
  Procedure ConfigureMySQL(host.s, port.i, dbName.s, user.s, password.s)
    Debug "ORM: ConfigureMySQL() - NOT YET IMPLEMENTED in Alpha 1.4"
    Debug "     Planned for next release with UseMySQLDatabase() + libmariadb.dll"
    MessageRequester("ORM Info",
                     "MySQL/MariaDB support is planned for the next release." + #CRLF$ +
                     "Please use ConfigureSQLite() for Alpha 1.4.",
                     #PB_MessageRequester_Info)
  EndProcedure

  ; ---------------------------------------------------------------------------
  ; Set main window handle for async PostEvent dispatch
  ; ---------------------------------------------------------------------------
  Procedure SetMainWindow(windowId.i)
    orm_mainWindow = windowId
    Debug "ORM: Main window set to " + Str(windowId)
  EndProcedure

  ; ---------------------------------------------------------------------------
  ; Register an entity
  ; ---------------------------------------------------------------------------
  Procedure Register(entityName.s, tableName.s = "", metaProc.i = 0)
    ; Auto-derive table name if not provided ("Client" -> "clients")
    If tableName = ""
      tableName = ORM_Schema::TableNameFromEntity(entityName)
    EndIf

    ; If a meta procedure is provided, call it to populate field/relation lists
    ; The meta procedure signature is: Procedure EntityMeta(entityName.s, tableName.s)
    If metaProc <> 0
      Protected metaFn.i = metaProc
      CallFunctionFast(metaFn, @entityName, @tableName)
    Else
      ; Manual registration with empty field list (developer fills later)
      Protected emptyFields.ORM_FieldDef
      Protected emptyRelations.ORM_Schema::ORM_RelationDef
      NewList tempFields.ORM_FieldDef()
      NewList tempRelations.ORM_Schema::ORM_RelationDef()
      ORM_Schema::RegisterEntity(entityName, tableName, tempFields(), tempRelations())
    EndIf

    Debug "ORM: Registered entity '" + entityName + "' -> '" + tableName + "'"
  EndProcedure

  ; ---------------------------------------------------------------------------
  ; Run AutoMigrate
  ; ---------------------------------------------------------------------------
  Procedure.b AutoMigrate()
    If Not IsDatabase(orm_mainDb)
      Debug "ORM::AutoMigrate() ERROR: No database configured. Call ConfigureSQLite() first."
      ProcedureReturn #False
    EndIf
    Protected ok.b = ORM_Schema::Migrate(orm_mainDb)
    If ok
      Debug "ORM: AutoMigrate completed successfully."
      ; Start the async worker pool (2 workers, sharing the same SQLite file via WAL)
      ORM_AsyncWorker::Init(orm_dbPath, 2, orm_mainWindow)
    Else
      Debug "ORM: AutoMigrate completed WITH ERRORS."
    EndIf
    ProcedureReturn ok
  EndProcedure

  ; ---------------------------------------------------------------------------
  ; Async find by id
  ; ---------------------------------------------------------------------------
  Procedure FindByIdAsync(entityType.s, recordId.i, callbackPtr.i)
    ORM_AsyncWorker::FindByIdAsync(entityType, recordId, callbackPtr, orm_mainWindow)
  EndProcedure

  ; ---------------------------------------------------------------------------
  ; Async query
  ; ---------------------------------------------------------------------------
  Procedure QueryAsync(entityType.s, whereClause.s, callbackPtr.i)
    ORM_AsyncWorker::QueryAsync(entityType, whereClause, callbackPtr, orm_mainWindow)
  EndProcedure

  ; ---------------------------------------------------------------------------
  ; Shutdown: close DB and stop workers
  ; ---------------------------------------------------------------------------
  Procedure Shutdown()
    ORM_AsyncWorker::Shutdown()
    If IsDatabase(orm_mainDb)
      CloseDatabase(orm_mainDb)
      Debug "ORM: Database closed."
    EndIf
  EndProcedure

EndModule

; =============================================================================
; EOF ORM.pbi
; =============================================================================
