; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Animals_Animal_vt
  GetName.s()
  GetAge.i()
  Speak()
  DisplayInfo()
  Free()
EndInterface

Interface Animals_Dog_vt Extends Animals_Animal_vt
EndInterface

Interface Animals_Cat_vt Extends Animals_Animal_vt
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Animals_Animal_Inst
  *VTable.Animals_Animal_vt
  name.s
  age.i
EndStructure

Structure Animals_Dog_Inst Extends Animals_Animal_Inst
  breed.s
EndStructure

Structure Animals_Cat_Inst Extends Animals_Animal_Inst
  isLazy.b
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare Animals_Animal_Init(*This.Animals_Animal_Inst, name_p.s, age_p.i)
Declare.s Animals_Animal_GetName(*This.Animals_Animal_Inst)
Declare.i Animals_Animal_GetAge(*This.Animals_Animal_Inst)
Declare Animals_Animal_DisplayInfo(*This.Animals_Animal_Inst)
Declare Animals_Animal_Free(*This.Animals_Animal_Inst)
Declare Animals_Dog_Init(*This.Animals_Dog_Inst, name_p.s, age_p.i, breed_p.s)
Declare Animals_Dog_Speak(*This.Animals_Dog_Inst)
Declare Animals_Cat_Init(*This.Animals_Cat_Inst, name_p.s, age_p.i, isLazy_p.b)
Declare Animals_Cat_Speak(*This.Animals_Cat_Inst)

Declare.i New_Animals_Dog(name_p.s, age_p.i, breed_p.s)
Declare Free_Animals_Dog(*obj.Animals_Dog_Inst)
Declare.i New_Animals_Cat(name_p.s, age_p.i, isLazy_p.b)
Declare Free_Animals_Cat(*obj.Animals_Cat_Inst)

Procedure Animals_Animal_Init(*This.Animals_Animal_Inst, name_p.s, age_p.i)
  Protected *This_vt.Animals_Animal_vt = *This
        *This\name = name_p
        *This\age  = age_p
EndProcedure

Procedure.s Animals_Animal_GetName(*This.Animals_Animal_Inst)
  Protected *This_vt.Animals_Animal_vt = *This
        ProcedureReturn *This\name
EndProcedure

Procedure.i Animals_Animal_GetAge(*This.Animals_Animal_Inst)
  Protected *This_vt.Animals_Animal_vt = *This
        ProcedureReturn *This\age
EndProcedure

Procedure Animals_Animal_DisplayInfo(*This.Animals_Animal_Inst)
  Protected *This_vt.Animals_Animal_vt = *This
        Debug "Animal [" + *This\name + "] - Age: " + Str(*This\age) + " year(s)"
EndProcedure

Procedure Animals_Animal_Free(*This.Animals_Animal_Inst)
  Protected *This_vt.Animals_Animal_vt = *This
        Debug "Destroying Animal instance: " + *This\name
EndProcedure

Procedure Animals_Dog_Init(*This.Animals_Dog_Inst, name_p.s, age_p.i, breed_p.s)
  Protected *This_vt.Animals_Dog_vt = *This
        Animals_Animal_Init(*This, name_p, age_p)
        *This\breed = breed_p
EndProcedure

Procedure Animals_Dog_Speak(*This.Animals_Dog_Inst)
  Protected *This_vt.Animals_Dog_vt = *This
        Debug *This\name + " (" + *This\breed + ") says: Woof! Woof!"
EndProcedure

Procedure Animals_Cat_Init(*This.Animals_Cat_Inst, name_p.s, age_p.i, isLazy_p.b)
  Protected *This_vt.Animals_Cat_vt = *This
        Animals_Animal_Init(*This, name_p, age_p)
        *This\isLazy = isLazy_p
EndProcedure

Procedure Animals_Cat_Speak(*This.Animals_Cat_Inst)
  Protected *This_vt.Animals_Cat_vt = *This
        Debug *This\name + " says: Meow..."
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Animals_Dog_VTable_Data:
    Data.i @Animals_Animal_GetName()
    Data.i @Animals_Animal_GetAge()
    Data.i @Animals_Dog_Speak()
    Data.i @Animals_Animal_DisplayInfo()
    Data.i @Animals_Animal_Free()
  Animals_Cat_VTable_Data:
    Data.i @Animals_Animal_GetName()
    Data.i @Animals_Animal_GetAge()
    Data.i @Animals_Cat_Speak()
    Data.i @Animals_Animal_DisplayInfo()
    Data.i @Animals_Animal_Free()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Animals_Dog(name_p.s, age_p.i, breed_p.s)
  Protected *obj.Animals_Dog_Inst = AllocateStructure(Animals_Dog_Inst)
  If *obj
    *obj\VTable = ?Animals_Dog_VTable_Data
    Animals_Dog_Init(*obj, name_p, age_p, breed_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Animals_Dog(*obj.Animals_Dog_Inst)
  If *obj
    Animals_Animal_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Animals_Cat(name_p.s, age_p.i, isLazy_p.b)
  Protected *obj.Animals_Cat_Inst = AllocateStructure(Animals_Cat_Inst)
  If *obj
    *obj\VTable = ?Animals_Cat_VTable_Data
    Animals_Cat_Init(*obj, name_p, age_p, isLazy_p)
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Animals_Cat(*obj.Animals_Cat_Inst)
  If *obj
    Animals_Animal_Free(*obj)
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

; ============================================================================
; PureBasic OOP - Example 01: Basics of Object-Oriented Programming
; Covers: Classes, Encapsulation, Constructors (Init), Destructors (Free),
;         Inheritance (Extends), Polymorphism and Super\Init()
; ============================================================================

EnableExplicit

; --- Abstract Base Class ---


  ; --- Derived Class: Dog ---

  ; --- Derived Class: Cat ---


; --- Main Demonstration ---
OpenConsole("PureBasic OOP - Basics Demonstration")

PrintN("=== 1. Instantiating Objects ===")
Define *dog.Animals_Dog_vt = New_Animals_Dog("Rex", 3, "German Shepherd")
Define *cat.Animals_Cat_vt = New_Animals_Cat("Felix", 2, #True)

PrintN("=== 2. Polymorphic Calls ===")
*dog\DisplayInfo()
*dog\Speak()

PrintN("")
*cat\DisplayInfo()
*cat\Speak()

PrintN("=== 3. Memory Cleanup ===")
*dog\Free()
*cat\Free()

PrintN("")
PrintN("Press Enter to exit...")
Input()
CloseConsole()
