; ============================================================================
; Generated by PureBasic OOP Transpiler (Native OOP Engine - ALPHA 1.2)
; Do not edit directly - modify the corresponding .pbo source file.
; ============================================================================

EnableExplicit

#OOP_PROJECT_DIR = "examples\06_database_crm\"
#OOP_WORKSPACE_DIR = "C:\PB\PB_PROJECT\PB_OOP_WORKSPACE\PUREBASIC_OOP_WORKSPACE\"

; PureBasic OOP Framework - Database & ORM Engine Integration
XIncludeFile #OOP_WORKSPACE_DIR + "framework/database/ORM.pbi"
UseModule Database
UseModule DatabaseEngine
UseModule DatabaseEntities
UseModule EntitySet
UseModule ORM_Schema

; ----------------------------------------------------------------------------
; 0.5 GLOBAL TYPE DECLARATIONS, STRUCTURES & CONSTANTS
; ----------------------------------------------------------------------------

#DB_FILE = "crm_demo.db"

; ----------------------------------------------------------------------------
; 1. PUREBASIC INTERFACES (VTABLE PROTOTYPES)
; ----------------------------------------------------------------------------

Interface Contact_vt Extends DatabaseEntities::IDatabaseEntity
  Get_firstName.s()
  Set_firstName(val.s)
  Get_lastName.s()
  Set_lastName(val.s)
  Get_email.s()
  Set_email(val.s)
  Get_isPrimary.b()
  Set_isPrimary(val.b)
EndInterface

Interface Client_vt Extends DatabaseEntities::IDatabaseEntity
  Get_companyName.s()
  Set_companyName(val.s)
  Get_email.s()
  Set_email(val.s)
  Get_phone.s()
  Set_phone(val.s)
  Get_city.s()
  Set_city(val.s)
  Get_isActive.b()
  Set_isActive(val.b)
  contacts.i()
  Add_contacts(*item)
  Count_contacts.i()
EndInterface

; ----------------------------------------------------------------------------
; 2. INSTANCE STRUCTURES
; ----------------------------------------------------------------------------

Structure Contact_Inst
  *VTable.Contact_vt
  id.i
  orm_isDirty.b
  orm_isNew.b
  firstName.s
  lastName.s
  email.s
  isPrimary.b
  client_id.i
EndStructure

Structure Client_Inst
  *VTable.Client_vt
  id.i
  orm_isDirty.b
  orm_isNew.b
  companyName.s
  email.s
  phone.s
  city.s
  isActive.b
  contacts.EntitySet::IEntitySet
EndStructure

; ----------------------------------------------------------------------------
; 2.5 GLOBAL VARIABLES, MAPS, LISTS & FORWARD DECLARATIONS
; ----------------------------------------------------------------------------


Declare Contact_Serialize(*This.Contact_Inst, Map values.s())
Declare Contact_Deserialize(*This.Contact_Inst, Map values.s())
Declare Client_Serialize(*This.Client_Inst, Map values.s())
Declare Client_Deserialize(*This.Client_Inst, Map values.s())
Declare Client_SaveChildren_contacts(*This.Client_Inst, db.i)
Declare Register_All_Entities()

; ----------------------------------------------------------------------------
; 3. METHOD PROCEDURES IMPLEMENTATION
; ----------------------------------------------------------------------------

Declare.s Contact_Get_firstName(*This.Contact_Inst)
Declare Contact_Set_firstName(*This.Contact_Inst, val.s)
Declare.s Contact_Get_lastName(*This.Contact_Inst)
Declare Contact_Set_lastName(*This.Contact_Inst, val.s)
Declare.s Contact_Get_email(*This.Contact_Inst)
Declare Contact_Set_email(*This.Contact_Inst, val.s)
Declare.b Contact_Get_isPrimary(*This.Contact_Inst)
Declare Contact_Set_isPrimary(*This.Contact_Inst, val.b)
Declare.i Contact_GetId(*This.Contact_Inst)
Declare Contact_SetId(*This.Contact_Inst, id.i)
Declare.b Contact_IsDirty(*This.Contact_Inst)
Declare Contact_SetDirty(*This.Contact_Inst, dirty.b)
Declare.b Contact_IsNew(*This.Contact_Inst)
Declare Contact_SetNew(*This.Contact_Inst, isNew.b)
Declare.b Contact_Save(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Contact_Delete(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Contact_Reload(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.s Contact_GetTableName(*This.Contact_Inst)
Declare.s Contact_GetEntityName(*This.Contact_Inst)
Declare.s Client_Get_companyName(*This.Client_Inst)
Declare Client_Set_companyName(*This.Client_Inst, val.s)
Declare.s Client_Get_email(*This.Client_Inst)
Declare Client_Set_email(*This.Client_Inst, val.s)
Declare.s Client_Get_phone(*This.Client_Inst)
Declare Client_Set_phone(*This.Client_Inst, val.s)
Declare.s Client_Get_city(*This.Client_Inst)
Declare Client_Set_city(*This.Client_Inst, val.s)
Declare.b Client_Get_isActive(*This.Client_Inst)
Declare Client_Set_isActive(*This.Client_Inst, val.b)
Declare.i Client_contacts(*This.Client_Inst)
Declare Client_Add_contacts(*This.Client_Inst, *item)
Declare.i Client_Count_contacts(*This.Client_Inst)
Declare.i Client_GetId(*This.Client_Inst)
Declare Client_SetId(*This.Client_Inst, id.i)
Declare.b Client_IsDirty(*This.Client_Inst)
Declare Client_SetDirty(*This.Client_Inst, dirty.b)
Declare.b Client_IsNew(*This.Client_Inst)
Declare Client_SetNew(*This.Client_Inst, isNew.b)
Declare.b Client_Save(*This.Client_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Client_Delete(*This.Client_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.b Client_Reload(*This.Client_Inst, db.DatabaseEngine::IDatabase = 0)
Declare.s Client_GetTableName(*This.Client_Inst)
Declare.s Client_GetEntityName(*This.Client_Inst)

Declare.i New_Contact()
Declare Free_Contact(*obj.Contact_Inst)
Declare.i New_Client()
Declare Free_Client(*obj.Client_Inst)

Procedure.s Contact_Get_firstName(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\firstName
EndProcedure

Procedure Contact_Set_firstName(*This.Contact_Inst, val.s)
  Protected *This_vt.Contact_vt = *This
  *This\firstName = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.s Contact_Get_lastName(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\lastName
EndProcedure

Procedure Contact_Set_lastName(*This.Contact_Inst, val.s)
  Protected *This_vt.Contact_vt = *This
  *This\lastName = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.s Contact_Get_email(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\email
EndProcedure

Procedure Contact_Set_email(*This.Contact_Inst, val.s)
  Protected *This_vt.Contact_vt = *This
  *This\email = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.b Contact_Get_isPrimary(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\isPrimary
EndProcedure

Procedure Contact_Set_isPrimary(*This.Contact_Inst, val.b)
  Protected *This_vt.Contact_vt = *This
  *This\isPrimary = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.i Contact_GetId(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\id
EndProcedure

Procedure Contact_SetId(*This.Contact_Inst, id.i)
  Protected *This_vt.Contact_vt = *This
  *This\id = id
EndProcedure

Procedure.b Contact_IsDirty(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\orm_isDirty
EndProcedure

Procedure Contact_SetDirty(*This.Contact_Inst, dirty.b)
  Protected *This_vt.Contact_vt = *This
  *This\orm_isDirty = dirty
EndProcedure

Procedure.b Contact_IsNew(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn *This\orm_isNew
EndProcedure

Procedure Contact_SetNew(*This.Contact_Inst, isNew.b)
  Protected *This_vt.Contact_vt = *This
  *This\orm_isNew = isNew
EndProcedure

Procedure.b Contact_Save(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Contact_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Save(*This)
EndProcedure

Procedure.b Contact_Delete(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Contact_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Delete(*This)
EndProcedure

Procedure.b Contact_Reload(*This.Contact_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Contact_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 Or *This\id = 0 : ProcedureReturn #False : EndIf
  NewMap vals.s()
  If ORM_CRUD::SelectById(targetDb\GetHandle(), "Contact", *This\id, vals())
    Contact_Deserialize(*This, vals())
    *This\orm_isDirty = #False
    *This\orm_isNew = #False
    ProcedureReturn #True
  EndIf
  ProcedureReturn #False
EndProcedure

Procedure.s Contact_GetTableName(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn "contacts"
EndProcedure

Procedure.s Contact_GetEntityName(*This.Contact_Inst)
  Protected *This_vt.Contact_vt = *This
  ProcedureReturn "Contact"
EndProcedure

Procedure.s Client_Get_companyName(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\companyName
EndProcedure

Procedure Client_Set_companyName(*This.Client_Inst, val.s)
  Protected *This_vt.Client_vt = *This
  *This\companyName = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.s Client_Get_email(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\email
EndProcedure

Procedure Client_Set_email(*This.Client_Inst, val.s)
  Protected *This_vt.Client_vt = *This
  *This\email = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.s Client_Get_phone(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\phone
EndProcedure

Procedure Client_Set_phone(*This.Client_Inst, val.s)
  Protected *This_vt.Client_vt = *This
  *This\phone = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.s Client_Get_city(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\city
EndProcedure

Procedure Client_Set_city(*This.Client_Inst, val.s)
  Protected *This_vt.Client_vt = *This
  *This\city = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.b Client_Get_isActive(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\isActive
EndProcedure

Procedure Client_Set_isActive(*This.Client_Inst, val.b)
  Protected *This_vt.Client_vt = *This
  *This\isActive = val
  *This\orm_isDirty = #True
EndProcedure

Procedure.i Client_contacts(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\contacts
EndProcedure

Procedure Client_Add_contacts(*This.Client_Inst, *item)
  Protected *This_vt.Client_vt = *This
  If *This\contacts : *This\contacts\Add(*item) : EndIf
EndProcedure

Procedure.i Client_Count_contacts(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  If *This\contacts : ProcedureReturn *This\contacts\Count() : EndIf : ProcedureReturn 0
EndProcedure

Procedure.i Client_GetId(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\id
EndProcedure

Procedure Client_SetId(*This.Client_Inst, id.i)
  Protected *This_vt.Client_vt = *This
  *This\id = id
EndProcedure

Procedure.b Client_IsDirty(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\orm_isDirty
EndProcedure

Procedure Client_SetDirty(*This.Client_Inst, dirty.b)
  Protected *This_vt.Client_vt = *This
  *This\orm_isDirty = dirty
EndProcedure

Procedure.b Client_IsNew(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn *This\orm_isNew
EndProcedure

Procedure Client_SetNew(*This.Client_Inst, isNew.b)
  Protected *This_vt.Client_vt = *This
  *This\orm_isNew = isNew
EndProcedure

Procedure.b Client_Save(*This.Client_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Client_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Save(*This)
EndProcedure

Procedure.b Client_Delete(*This.Client_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Client_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 : ProcedureReturn #False : EndIf
  ProcedureReturn targetDb\Delete(*This)
EndProcedure

Procedure.b Client_Reload(*This.Client_Inst, db.DatabaseEngine::IDatabase = 0)
  Protected *This_vt.Client_vt = *This
  Protected targetDb.DatabaseEngine::IDatabase = db
  If targetDb = 0 : targetDb = Database::GetDefault() : EndIf
  If targetDb = 0 Or *This\id = 0 : ProcedureReturn #False : EndIf
  NewMap vals.s()
  If ORM_CRUD::SelectById(targetDb\GetHandle(), "Client", *This\id, vals())
    Client_Deserialize(*This, vals())
    *This\orm_isDirty = #False
    *This\orm_isNew = #False
    ProcedureReturn #True
  EndIf
  ProcedureReturn #False
EndProcedure

Procedure.s Client_GetTableName(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn "clients"
EndProcedure

Procedure.s Client_GetEntityName(*This.Client_Inst)
  Protected *This_vt.Client_vt = *This
  ProcedureReturn "Client"
EndProcedure

; ----------------------------------------------------------------------------
; 4. VTABLE DATASECTIONS (DYNAMIC DISPATCH)
; ----------------------------------------------------------------------------

DataSection
  Contact_VTable_Data:
    Data.i @Contact_GetId()
    Data.i @Contact_SetId()
    Data.i @Contact_IsDirty()
    Data.i @Contact_SetDirty()
    Data.i @Contact_IsNew()
    Data.i @Contact_SetNew()
    Data.i @Contact_Save()
    Data.i @Contact_Delete()
    Data.i @Contact_Reload()
    Data.i @Contact_GetTableName()
    Data.i @Contact_GetEntityName()
    Data.i @Contact_Get_firstName()
    Data.i @Contact_Set_firstName()
    Data.i @Contact_Get_lastName()
    Data.i @Contact_Set_lastName()
    Data.i @Contact_Get_email()
    Data.i @Contact_Set_email()
    Data.i @Contact_Get_isPrimary()
    Data.i @Contact_Set_isPrimary()
  Client_VTable_Data:
    Data.i @Client_GetId()
    Data.i @Client_SetId()
    Data.i @Client_IsDirty()
    Data.i @Client_SetDirty()
    Data.i @Client_IsNew()
    Data.i @Client_SetNew()
    Data.i @Client_Save()
    Data.i @Client_Delete()
    Data.i @Client_Reload()
    Data.i @Client_GetTableName()
    Data.i @Client_GetEntityName()
    Data.i @Client_Get_companyName()
    Data.i @Client_Set_companyName()
    Data.i @Client_Get_email()
    Data.i @Client_Set_email()
    Data.i @Client_Get_phone()
    Data.i @Client_Set_phone()
    Data.i @Client_Get_city()
    Data.i @Client_Set_city()
    Data.i @Client_Get_isActive()
    Data.i @Client_Set_isActive()
    Data.i @Client_contacts()
    Data.i @Client_Add_contacts()
    Data.i @Client_Count_contacts()
EndDataSection

; ----------------------------------------------------------------------------
; 5. CONSTRUCTORS & FACTORY FUNCTIONS
; ----------------------------------------------------------------------------

Procedure.i New_Contact()
  Protected *obj.Contact_Inst = AllocateStructure(Contact_Inst)
  If *obj
    *obj\VTable = ?Contact_VTable_Data
    *obj\orm_isNew = #True
    *obj\orm_isDirty = #False
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Contact(*obj.Contact_Inst)
  If *obj
    FreeStructure(*obj)
  EndIf
EndProcedure

Procedure.i New_Client()
  Protected *obj.Client_Inst = AllocateStructure(Client_Inst)
  If *obj
    *obj\VTable = ?Client_VTable_Data
    *obj\orm_isNew = #True
    *obj\orm_isDirty = #False
    *obj\contacts = EntitySet::New()
  EndIf
  ProcedureReturn *obj
EndProcedure

Procedure Free_Client(*obj.Client_Inst)
  If *obj
    If *obj\contacts : *obj\contacts\Free() : EndIf
    FreeStructure(*obj)
  EndIf
EndProcedure

; ----------------------------------------------------------------------------
; 5.5 ORM ENTITY SERIALIZATION, DESERIALIZATION & REGISTRATION
; ----------------------------------------------------------------------------

Procedure Contact_Serialize(*This.Contact_Inst, Map values.s())
  ClearMap(values())
  values("firstName") = *This\firstName
  values("lastName") = *This\lastName
  values("email") = *This\email
  values("isPrimary") = Str(*This\isPrimary)
  values("client_id") = Str(*This\client_id)
EndProcedure

Procedure Contact_Deserialize(*This.Contact_Inst, Map values.s())
  If FindMapElement(values(), "id") : *This\id = Val(values()) : EndIf
  If FindMapElement(values(), "firstName") : *This\firstName = values() : EndIf
  If FindMapElement(values(), "lastName") : *This\lastName = values() : EndIf
  If FindMapElement(values(), "email") : *This\email = values() : EndIf
  If FindMapElement(values(), "isPrimary") : *This\isPrimary = Val(values()) : EndIf
  If FindMapElement(values(), "client_id") : *This\client_id = Val(values()) : EndIf
EndProcedure

Procedure Client_Serialize(*This.Client_Inst, Map values.s())
  ClearMap(values())
  values("companyName") = *This\companyName
  values("email") = *This\email
  values("phone") = *This\phone
  values("city") = *This\city
  values("isActive") = Str(*This\isActive)
EndProcedure

Procedure Client_Deserialize(*This.Client_Inst, Map values.s())
  If FindMapElement(values(), "id") : *This\id = Val(values()) : EndIf
  If FindMapElement(values(), "companyName") : *This\companyName = values() : EndIf
  If FindMapElement(values(), "email") : *This\email = values() : EndIf
  If FindMapElement(values(), "phone") : *This\phone = values() : EndIf
  If FindMapElement(values(), "city") : *This\city = values() : EndIf
  If FindMapElement(values(), "isActive") : *This\isActive = Val(values()) : EndIf
EndProcedure

Procedure Client_SaveChildren_contacts(*This.Client_Inst, db.i)
  Protected targetDb.DatabaseEngine::IDatabase = Database::WrapHandle(db)
  If Not targetDb : targetDb = Database::GetDefault() : EndIf
  If Not targetDb : ProcedureReturn : EndIf
  If *This\contacts
    Protected count.i = *This\contacts\Count()
    Protected i.i
    For i = 0 To count - 1
      Protected item.DatabaseEntities::IDatabaseEntity = *This\contacts\Get(i)
      If item
        Protected *itemInst.Contact_Inst = item
        *itemInst\client_id = *This\id
        item\Save(targetDb)
      EndIf
    Next
    count = *This\contacts\GetRemovedCount()
    For i = 0 To count - 1
      Protected remItem.DatabaseEntities::IDatabaseEntity = *This\contacts\GetRemovedItem(i)
      If remItem : remItem\Delete(targetDb) : EndIf
    Next
    *This\contacts\ResetTracking()
  EndIf
EndProcedure

Procedure Register_All_Entities()
  NewList currentFields.ORM_Schema::ORM_FieldDef()
  NewList currentRelations.ORM_Schema::ORM_RelationDef()

  ; Register entity Contact
  ClearList(currentFields())
  ClearList(currentRelations())
  AddElement(currentFields()) : currentFields()\name = "firstName" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "lastName" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "email" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "isPrimary" : currentFields()\typeCode = ORM_Entity::#ORM_Type_Bool
  AddElement(currentFields()) : currentFields()\name = "client_id" : currentFields()\typeCode = ORM_Entity::#ORM_Type_Integer
  ORM_Schema::RegisterEntity("Contact", "contacts", currentFields(), currentRelations(), @Contact_Serialize(), @Contact_Deserialize(), @New_Contact(), #True)

  ; Register entity Client
  ClearList(currentFields())
  ClearList(currentRelations())
  AddElement(currentFields()) : currentFields()\name = "companyName" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "email" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "phone" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "city" : currentFields()\typeCode = ORM_Entity::#ORM_Type_String
  AddElement(currentFields()) : currentFields()\name = "isActive" : currentFields()\typeCode = ORM_Entity::#ORM_Type_Bool
  AddElement(currentRelations())
  currentRelations()\relationType = ORM_Entity::#ORM_Rel_OneToMany
  currentRelations()\propertyName = "contacts"
  currentRelations()\childEntityType = "Contact"
  currentRelations()\childTable = "contacts"
  currentRelations()\fkColumn = "client_id"
  currentRelations()\joinTable = ""
  currentRelations()\parentFkColumn = "client_id"
  currentRelations()\childFkColumn = "contact_id"
  currentRelations()\cascadeSave = #True
  currentRelations()\saveChildrenProc = @Client_SaveChildren_contacts()
  ORM_Schema::RegisterEntity("Client", "clients", currentFields(), currentRelations(), @Client_Serialize(), @Client_Deserialize(), @New_Client(), #True)

EndProcedure

; ----------------------------------------------------------------------------
; 6. MAIN PROGRAM EXECUTION
; ----------------------------------------------------------------------------

Register_All_Entities()

; =============================================================================
; 06_database_crm / main.pbo
; PureBasic OOP Framework - Alpha 1.4 - Modern ORM Entity Demo
; =============================================================================
; Demonstrates PureBasic OOP Phase 2 modern entity architecture:
;   - Native entity classes implementing IDatabaseEntity
;   - Declaring 1-N relation: HasMany contacts.Contact_vt
;   - Zero manual boilerplate: Auto-generated serialization, schemas, methods
;   - Active Record saving: *client\Save() or *client\Save(*db)
;   - Cascade save: saving client automatically cascades and saves contacts
;   - AutoMigrate creates all SQLite tables and relations
; =============================================================================

; -----------------------------------------------------------------------------
; 1. ENTITY DEFINITIONS
; -----------------------------------------------------------------------------



; -----------------------------------------------------------------------------
; 2. APPLICATION EXECUTION
; -----------------------------------------------------------------------------

OpenConsole()
PrintN("=================================================================")
PrintN("   PureBasic OOP - 06 Database CRM Demo (Modern ORM Engine)")
PrintN("=================================================================")

; Database initialization
DeleteFile(#DB_FILE)

Define *db.DatabaseEngine::IDatabase = Database::NewSQLite(#DB_FILE)
If Not *db
  PrintN("[ERROR] Failed to open database: " + #DB_FILE)
  End 1
EndIf

; Set default database connection for Active Record style operations
Database::SetDefault(*db)

; Auto-migration generates schema directly from class declarations
If Not *db\AutoMigrate()
  PrintN("[ERROR] Schema AutoMigrate failed!")
  End 1
EndIf
PrintN("[SUCCESS] Database tables (clients, contacts) created automatically.")

; -----------------------------------------------------------------------------
; 3. CREATING AND PERSISTING ENTITY WITH RELATIONS
; -----------------------------------------------------------------------------

PrintN("")
PrintN("Creating Client 'Acme Corp' with 2 contacts...")

Define *client.Client_vt = New_Client()
*client\Set_companyName("Acme Corporation")
*client\Set_email("contact@acme.corp")
*client\Set_phone("+33 1 23 45 67 89")
*client\Set_city("Paris")
*client\Set_isActive(#True)

; Contact 1
Define *c1.Contact_vt = New_Contact()
*c1\Set_firstName("Jean")
*c1\Set_lastName("Dupont")
*c1\Set_email("j.dupont@acme.corp")
*c1\Set_isPrimary(#True)
*client\Add_contacts(*c1)

; Contact 2
Define *c2.Contact_vt = New_Contact()
*c2\Set_firstName("Sophie")
*c2\Set_lastName("Martin")
*c2\Set_email("s.martin@acme.corp")
*c2\Set_isPrimary(#False)
*client\Add_contacts(*c2)

; Active Record style save: *client\Save()
; Automatically inserts Client into 'clients', generates ID,
; and cascades to save *c1 and *c2 into 'contacts' with foreign key client_id.
If *client\Save()
  PrintN("[SUCCESS] Client saved with ID: " + Str(*client\GetId()))
  PrintN("[SUCCESS] Contact 1 saved with ID: " + Str(*c1\GetId()))
  PrintN("[SUCCESS] Contact 2 saved with ID: " + Str(*c2\GetId()))
Else
  PrintN("[ERROR] Failed to save Client!")
EndIf

; -----------------------------------------------------------------------------
; 4. DIRECT DATABASE VERIFICATION
; -----------------------------------------------------------------------------

PrintN("")
PrintN("Verifying data directly in SQLite...")

Define query.i = *db\Query("SELECT id, companyName, city FROM clients WHERE id = " + Str(*client\GetId()) + ";")
If query
  If NextDatabaseRow(*db\GetHandle())
    PrintN("  Client row found: ID=" + Str(GetDatabaseLong(*db\GetHandle(), 0)) + ", Name=" + GetDatabaseString(*db\GetHandle(), 1) + ", City=" + GetDatabaseString(*db\GetHandle(), 2))
  EndIf
  FinishDatabaseQuery(*db\GetHandle())
EndIf

query = *db\Query("SELECT id, firstName, lastName, client_id FROM contacts WHERE client_id = " + Str(*client\GetId()) + ";")
If query
  While NextDatabaseRow(*db\GetHandle())
    PrintN("  Contact row found: ID=" + Str(GetDatabaseLong(*db\GetHandle(), 0)) + " -> " + GetDatabaseString(*db\GetHandle(), 1) + " " + GetDatabaseString(*db\GetHandle(), 2) + " (client_id=" + Str(GetDatabaseLong(*db\GetHandle(), 3)) + ")")
  Wend
  FinishDatabaseQuery(*db\GetHandle())
EndIf

; -----------------------------------------------------------------------------
; 5. CLEANUP
; -----------------------------------------------------------------------------

FreeStructure(*client)
FreeStructure(*c1)
FreeStructure(*c2)
*db\Disconnect()

PrintN("")
PrintN("=================================================================")
PrintN("   Demo completed successfully! Press Enter to exit.")
PrintN("=================================================================")
CloseConsole()
